if( GetLocale() ~= "ptBR" ) then return end
local L = {}
L["2D"] = "2D"
L["3D"] = "3D"
L["A"] = "A"
L["Abbreviates unit names above 10 characters, \"Dark Rune Champion\" becomes \"D.R.Champion\" and \"Dark Rune Commoner\" becomes \"D.R.Commoner\"."] = "Abrevia os nomes das unidades com mais de 10 caracteres, \"Dark Rune Champion\" passa a \"D.R.Champion\" e \"Dark Rune Commoner\" passa a  \"D.R.Commoner\"."
L["Absolute incoming heal value, if 10,000 healing is incoming it will show 10,000."] = "Valor absoluto de cura a receber, se vai receber 10,000 de cura, então mostrará 10,000."
L["Add"] = "Adiciona"
L["Add new tag"] = "Adicionar nova tag"
L["Add new text"] = "Adicionar novo texto"
L["Adds a bar indicating how much time is left on your ghoul timer, only used if you do not have a permanent ghoul."] = "Adiciona uma barra a indicar quanto tempo resta no temporizador da ghoul, apenas é usado se não tiver uma ghoul permanente." -- Needs review
L["Adds an empty bar that you can put text into as a way of uncluttering other bars."] = "Adiciona uma barra onde pode por texto como forma de desatafulhar outras barras." -- Needs review
L["Adds another mana bar to the player frame when you are in Bear or Cat form showing you how much mana you have."] = "Adiciona uma outra barra de mana à moldura quando está em forma de Gato ou Urso indicando a mana que possui." -- Needs review
L["Adds rune bars and timers before runes refresh to the player frame."] = "Adiciona à moldura do jogador temporizadores de tempo restante para as runes refrescarem e barras de runes." -- Needs review
L["Adds %s to the list of units to be modified when you change values in this tab."] = "Adiciona %s à lista de unidades que vão ser modificadas quando muda valores neste separador." -- Needs review
L["Adds temporary enchants to the buffs for the player."] = "Adiciona encantamentos temporários aos feitiços benéficos para o jogador." -- Needs review
L["Adds totem bars with timers before they expire to the player frame."] = "Adiciona à moldura do jogador barras de totems com temporizadores de tempo restante para expirarem." -- Needs review
L["Advanced"] = "Avançadas"
L["Advanced tag management, allows you to add your own custom tags."] = "Gestão avançada de tags, permite-lhe adicionar as suas próprias tags." -- Needs review
L["AFK"] = "LDT"
L["AFK:%s"] = "LDT:%s"
L["AFK status"] = "estado LDT"
L["AFK timer"] = "temporizador LDT"
L["After you hit export, you can give the below code to other Shadowed Unit Frames users and they will get your exact layout."] = "Depois de clicar em exportar, pode dar o código abaixo a outros utilizadores do Shadowed Unit Frames e eles irão ficar com a disposição das molduras igual à sua." -- Needs review
L["Aggro"] = "Aggro" -- Needs review
L["Alpha to use for bar backgrounds."] = "Alpha para usar no background da barra." -- Needs review
L["Ammo"] = "Munições" -- Needs review
L["Amount of health missing, if none is missing nothing is shown. Uses a short format, -18500 is shown as -18.5k, values below 10000 are formatted as is."] = "Quantidade de vida em falta, se há 0 em falta nada é mostrado. Utiliza um formato curto, -18500 é mostrado como -18.5k, valores abaixo de 10000 são formatados assim mesmo." -- Needs review
L["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Quantidade de power em falta, se faltar 0 nada será mostrado. Usa um formato curto, -13850 é mostrado como 13.8k, valores abaixo de 10000 são formatados assim mesmo." -- Needs review
L["Anchor point"] = "Ponto de ancoragem" -- Needs review
L["Anchor to"] = "Ancorar a" -- Needs review
L["Anchor to another frame"] = "Ancorar a outra moldura" -- Needs review
L["Anchor to buffs"] = "Ancorar aos buffs" -- Needs review
L["Anchor to debuffs"] = "Ancorar aos debuffs" -- Needs review
L["Aquatic"] = "Aquantico" -- Needs review
L["Arena"] = "Arena" -- Needs review
L["Arenas"] = "Arenas" -- Needs review
L["Are you sure you want to delete this filter?"] = "Tem a certeza que pretende remover este filtro?" -- Needs review
L["Are you sure you want to delete this tag?"] = "Tem a certeza que quer apagar esta tag?" -- Needs review
L["Are you sure you want to delete this text? All settings for it will be deleted."] = "Tem a certeza que quer apagar este texto? Todas as definições do mesmo serão apagadas." -- Needs review
L["Ascending"] = "Ascendente" -- Needs review
L["Aura border style"] = "Estilo da aura da aresta" -- Needs review
L["Aura filters"] = "Filtros de aura" -- Needs review
L["Auras"] = "Auras" -- Needs review
L["Aura types to filter"] = "Tipos de filtros de aura" -- Needs review
L["B"] = "B" -- Needs review
L["Background"] = "Background" -- Needs review
L["Background alpha"] = "Alpha de background" -- Needs review
L["Background/border"] = "Background/border" -- Needs review
L["Background color"] = "Cor de background" -- Needs review
L["Bag indicator for master looters."] = "Indicador de saco para master looters" -- Needs review
L["Bars"] = "Barras" -- Needs review
L["Bar spacing"] = "Espaçamento da barra" -- Needs review
L["Bar texture"] = "Textura da barra" -- Needs review
L["Battlegrounds"] = "Battlegrounds" -- Needs review
L["Bear"] = "Urso" -- Needs review
L["Blacklist"] = "Lista negra" -- Needs review
L["Blacklist filters"] = "Filtros de lista negra" -- Needs review
L["Blacklists"] = "Lista negra" -- Needs review
L["Blizzard"] = "Blizzard" -- Needs review
L["Border"] = "Borda" -- Needs review
L["Border alpha"] = "Alpha da aresta" -- Needs review
L["Border color"] = "Cor da borda" -- Needs review
L["Border highlighting"] = "Border highlighting" -- Needs review
L["Border thickness"] = "Grossura da borda" -- Needs review
L["Boss"] = "Chefe" -- Needs review
L["Boss Target"] = "Alvo do Chefe" -- Needs review
L["Both"] = "Ambos" -- Needs review
L["Bottom"] = "Botão" -- Needs review
L["C"] = "C" -- Needs review
L["Cannot find any profiles named \"%s\"."] = "Nenhum profile encontrado com o nome \"%s\"." -- Needs review
L["Cat"] = "Gato" -- Needs review
L["Category"] = "Categoria" -- Needs review
L["Center"] = "Centro" -- Needs review
L["Class"] = "Classe" -- Needs review
L["Classes"] = "Classes" -- Needs review
L["Classification"] = "Classificação" -- Needs review
L["Classifications"] = "Classficações" -- Needs review
L["Class (Smart)"] = "Classe (curto)" -- Needs review
L["Class Specific"] = "Classe Específica" -- Needs review
L["Code"] = "Código" -- Needs review
L["Color by class"] = "Classe por cor" -- Needs review
L["Colors"] = "Cores" -- Needs review
L["Color to use to show how much damage will be absorbed."] = "Cor para exibir o quanto de dano for absorvido" -- Needs review
L["Column spacing"] = "Espaçamento da coluna" -- Needs review
L["Create"] = "Criar" -- Needs review
L["Creature type"] = "Tipo de criatura" -- Needs review
L["Cur/Max HP (Absolute)"] = "Atual/Máximo Vida (absoluto)" -- Needs review
L["Current HP (Absolute)"] = "Vida atual (Absoluta)" -- Needs review
L["Currently modifying"] = "Modificando atualmente" -- Needs review
L["Dead"] = "Morto" -- Needs review
L["Default color"] = "Cor padrão" -- Needs review
L["Delete"] = "Apagar" -- Needs review
L["Delete filter"] = "Remover Filtro" -- Needs review
L["Disabled"] = "Desabilitado" -- Needs review
L["Disabled in %s"] = "Desabilitado em %s" -- Needs review
L["Disable vehicle swap"] = "Desabilitar troca de veículo" -- Needs review
L["DND"] = "Não Perturbe" -- Needs review
L["DND:%s"] = "Não Perturbe: %s" -- Needs review
L["Documentation"] = "Documentação" -- Needs review
L["Don't hide when empty"] = "Não ocultar enquanto vazio" -- Needs review
L["Down"] = "Baixo" -- Needs review
L["Editing %s"] = "Editando %s" -- Needs review
L["Enabled in %s"] = "Habilitado em %s" -- Needs review
L["Enable %s"] = "Habilitar %s" -- Needs review
L["Energy"] = "Energia" -- Needs review
L["Error"] = "Erro" -- Needs review
L["Events"] = "Eventos" -- Needs review
L["Export"] = "Exportar" -- Needs review
L["F"] = "F" -- Needs review
L["Failed to load ShadowedUF_Options, cannot open configuration. Error returned: %s"] = "Falha ao carregar ShadowedUF_Options, impossível abrir configuração. Erro reportado: %s" -- Needs review
L["Female"] = "Fêmea" -- Needs review
L["Filter type"] = "Tipo de filtro" -- Needs review
L["Focus"] = "Foco" -- Needs review
L["Font"] = "Fonte" -- Needs review
L["Fuel"] = "Combustivel" -- Needs review
L["General"] = "Geral" -- Needs review
L["Ghost"] = "Fantasma" -- Needs review
L["Global"] = "Global" -- Needs review
L["Group by"] = "Agrupar por" -- Needs review
L["Group %d"] = "Grupo %d" -- Needs review
L["Group number"] = "Grupo número" -- Needs review
L["Groups"] = "Grupos" -- Needs review
L["Health"] = "Vida" -- Needs review
L["Health bar"] = "Barra de Vida" -- Needs review
L["Help"] = "Ajuda" -- Needs review
L["Hide Blizzard"] = "Ocultar Blizzard" -- Needs review
L["Hide in >5-man raids"] = "Ocultar >5man raid" -- Needs review
L["Hide %s"] = "Ocultar %s" -- Needs review
L["Hide %s frames"] = "Ocultar %s" -- Needs review
L["High"] = "Alto" -- Needs review
L["Hostile"] = "Hostil" -- Needs review
L["How many auras to show in a single row."] = "Quantas auras para exibir em uma coluna simples" -- Needs review
L["How many Chi points you currently have."] = "Quantos pontos de Chi você tem no momento" -- Needs review
L["How much spacing should be between each new row of groups."] = "Quanto de espaço entre cada nova célula de grupo" -- Needs review
L["Import"] = "Importar" -- Needs review
L["Indicators"] = "Indicadores" -- Needs review
L["Invert colors"] = "Inverter cores" -- Needs review
L["Layout manager"] = "Gerenciador de Visual" -- Needs review
L["Left"] = "Esquerdo" -- Needs review
L["Left Bottom"] = "Botão esquerdo" -- Needs review
L["Level"] = "Nível" -- Needs review
L["Level %s - %s: %s/%s (%.2f%% done)"] = "Nível %s - %s: %s/%s (%.2f%% atingido)" -- Needs review
L["Level %s - %s: %s/%s (%.2f%% done), %s rested."] = "Nível %s - %s: %s/%s (%.2f%% done), %s restante." -- Needs review
L["M"] = "M" -- Needs review
L["Male"] = "Masculino" -- Needs review
L["Mana"] = "Mana" -- Needs review
L["Manual position"] = "Posição Manual" -- Needs review
L["Max columns"] = "Máximo de colunas" -- Needs review
L["Miscellaneous"] = "Miscelânea" -- Needs review
L["Name"] = "Nome" -- Needs review
L["Name (Abbreviated)"] = "Nome" -- Needs review
L["Neutral"] = "Neutro" -- Needs review
L["Never (Disabled)"] = "Never (desabilitado)" -- Needs review
L["New filter"] = "Novo Filtro" -- Needs review
L["None"] = "Nenhum" -- Needs review
L["Offline"] = "Desconectado" -- Needs review
L["Offline timer"] = "Tempo desconectado" -- Needs review
L["Off:%s"] = "desconectado:%s" -- Needs review
L["Ok"] = "ok" -- Needs review
L["Order"] = "Ordenar" -- Needs review
L["Outside bar limit"] = "Fora da barra limite" -- Needs review
L["Party"] = "Grupo" -- Needs review
L["Per column"] = "Por coluna" -- Needs review
L["Player"] = "Jogador" -- Needs review
L["Position"] = "Posição" -- Needs review
L["Power"] = "Energia" -- Needs review
L["Power bar"] = "Barra de energia" -- Needs review
L["PvP Flag"] = "Bandeira JxJ" -- Needs review
L["PVP:%s"] = "JxJ:%s" -- Needs review
L["Race"] = "Raça" -- Needs review
L["Red (>70% HP)"] = "Vermelho (>70% Vida)" -- Needs review
L["Scale"] = "Escala" -- Needs review
L["Search"] = "Busca" -- Needs review
L["Sex"] = "Sexo" -- Needs review
L["%s frames"] = "%s moldura"
L["Show Heal Absorbs"] = "Exibir cura absorvida" -- Needs review
L["Size"] = "Tamanho" -- Needs review
L["%s member"] = "%s membro"
L["%s (%s): %s/%s (%.2f%% done)"] = "%s (%s): %s/%s (%.2f%% terminado)"
L["T"] = "T" -- Needs review
L["Target"] = "Alvo" -- Needs review
L["Target of Target"] = "Alvo do Alvo" -- Needs review
L["Target of Target of Target"] = "Alvo do Alvo do Alvo" -- Needs review
L["Text"] = "Texto" -- Needs review
L["Text Management"] = "Gerenciamento de texto" -- Needs review
L["This bar will automatically hide when you are at the level cap, or you do not have any reputations tracked."] = "Essa barra será oculta automaticamente quando você atingir o nível máximo, ou se você não tiver alguma reputação." -- Needs review
L["Top"] = "Topo" -- Needs review
L["Top Center"] = "Topo Centro" -- Needs review
L["Top Left"] = "Topo Esquerdo" -- Needs review
L["Top Right"] = "Topo Direito" -- Needs review
L["Up"] = "Cima" -- Needs review
L["Update interval"] = "Intervalo de atualização" -- Needs review
L["Vehicle"] = "Veículo" -- Needs review
L["Vehicles"] = "Veículos" -- Needs review
L["View"] = "Ver" -- Needs review
L["Visibility"] = "Visibilidade" -- Needs review
L["Yellow (>30% HP)"] = "Amarelo (>30% Vida)" -- Needs review
L["You must enter a number that is 0 or higher, negative numbers are not allowed."] = "Você precisa por um número, 0 ou maior, número negativos não serão aceitos." -- Needs review
L["Zone Configuration"] = "Configuração de Zona" -- Needs review

local ShadowUF = select(2, ...)
ShadowUF.L = setmetatable(L, {__index = ShadowUF.L})
