--[[
	Language Localization: deDE
	Translated by: Chiaki EU-Frostwolf <chiakiaccess@hotmail.com>
	Version: 0,1
	-- ƒ = \195\132
	-- ÷ = \195\150
	-- ‹ = \195\156
	-- ﬂ = \195\159
	-- ‰ = \195\164
	-- ˆ = \195\182
	-- ¸ = \195\188
]]

WIM.AddLocale("deDE", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM ist ein AddOn, welches einem das vertraute Gef\195\188hl \195\188ber ein Chatsystem zu kommunizieren zur\195\188ckbringt. In diesem Fenster kannst du WIM individualisieren, um es deinen Bed\195\188rfnissen anzupassen. Wenn du Fragen, Kommentare oder Vorschl\195\164ge hast, dann besuche doch bitte die Seite http://www.WIMAddon.com.",
	
	
    ["_DemoText"] = "Dies ist ein Demonstrationsfenster und ist nicht voll funktionsf\195\164hig. Platziere dieses Fenster an die Stelle, an der du alle anderen Fenster erzeugen m\195\182chtest. Sobald du fertig bist kannst du das Fenster schlie\195\159en, um die Einstellungen zu speichern.",
	
	
    ["_DateFormat"] = "%d/%m/%Y",

    ["Yes"] = "Ja",
    ["No"] = "Nein",
    ["None"] = "Kein(e)",
    ["<Right-Click>"] = "<Rechts-Klick>",
    ["<Left-Click>"] = "<Links-Klick>",
    ["OK"] = true,
    ["Cancel"] = "Abbrechen",
    ["Unknown"] = "Unbekannt",
    ["Click to update..."] = "Klicke um ein Update zu starten...",
    ["Usage"] = "Gebrauch",
    
    ["state_resting"] = "Ruhend",
    ["state_combat"] = "Kampf",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Gruppeninstanz",
    ["state_raid"] = "Schlachtzuginstanz",
    ["state_other"] = "Normal (Sonstiges)",
    
    ["<Shift-Click> to close window."] = "<Shift-Klick> zum Schlie\195\159en des Fensters.",
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "Eine neue Version von WIM ist verf\195\188gbar!\nDu kannst die neueste Version auf http://www.wimaddon.com/ herunterladen.",
    
    ["Options"] = "Einstellungen",
    
    ["Icon Position"] = true,
    ["Font Size"] = "Schriftgr\195\182\195\159e",
    ["Window Scale (Percent)"] = "Fensterskalierung (Prozent)",
    ["Transparency (Percent)"] = "Transparenz (Prozent)",
    ["Window Width"] = "Fensterbreite",
    ["Window Height"] = "Fensterh\195\182he",
    ["(Limited by shortcut bar)"] = "(Begrenzt durch die Funktionsleiste rechts)",
    ["ERROR"] = "FEHLER",
    ["Invalid Name!"] = "Ung\195\188ltiger Name!",
    ["Name is already used!"] = "Name wird bereits verwendet!",
    ["Invalid Alias!"] = "Ung\195\188ltiges Alias!",
    ["Invalid Keyword/Phrase!"] = "Ung\195\188ltiges Password/Phrase!",
    ["Keyword/Phrase is already used!"] = "Password/Phrase wird bereits verwendet!",
    
    ["Day"] = "Tag",
    ["Week"] = "Woche",
    ["Month"] = "Monat",
    ["Drag to set default spawn/position for message windows."] = "Ziehe um die Ausgangsposition f\195\188r die Erzeugung von Nachrichtenfenstern festzulegen.",
    ["Up"] = "Oben",
    ["Down"] = "Unten",
    ["Left"] = "Links",
    ["Right"] = "Rechts",
    ["Ignore"] = "Ignorieren",
    ["Block"] = "Blockieren",
    ["Enable WIM"] = "WIM aktivieren",
    
    ["Auto Close Friends after:"] = "Schlie\195\159e Freundesnachrichten automatisch nachdem:",
    ["Auto Close Non-Friends after:"] = "Schlie\195\159e Nicht-Freundesnachrichten automatisch nachdem:",
    
    ["Display"] = "Anzeige",
    ["Incoming Messages"] = "Eingehende Nachrichten",
    ["Outgoing Messages"] = "Ausgehende Nachrichten",
    ["System Messages"] = "Systemnachrichten",
    ["Error Messages"] = "Fehlernachrichten",
    ["Web URLs"] = "Internet-Adressen",
    ["Enable"] = "Aktivieren",
    ["Disable"] = "Deaktivieren",
    ["Enabled"] = "Aktiviert",
    ["Disabled"] = "Deaktiviert",
    ["Display character information."] = "Zeige Charakterinformationen an.",
    ["Display time stamps"] = "Zeige Zeitstempel an",
    ["This setting limits the\nwindow's minimum height."] = "Diese Einstellung begrenzt die\n Minimalh\195\182he des Fensters.",
    ["Requires /who querying."] = "Ben\195\182tigt /who Abfragen.",
    ["Enable window fading effects."] = "Fenster-Verblassungseffekte aktivieren.",
    ["Enable window animations."] = "Fenster-Animationen aktivieren.",
    
    ["Display minimap icon."] = "Minimap-Symbol anzeigen.",
    
    ["General"] = "Allgemein",
    ["History"] = "Verlauf",
    ["Filters"] = "Filter",
    ["Plugins"] = true,
    
    ["Auto focus when window is shown."] = "Automatischer Textcursor-Fokus wenn sich ein Fenster \195\182ffnet.",
    ["Preserve focus after sending messages."] = "Textcursor-Fokus nach der Nachrichtenversendung beibehalten.",
    ["Display tooltips."] = "Tooltips anzeigen.",
    ["Show window when sending a message."] = "Fenster anzeigen, wenn eine Nachricht gesendet wird.",
    ["Show window when message has been received."] = "Fenster anzeigen, wenn eine Nachricht erhalten wurde.",
    ["Supress messages from default chat frame."] = "Nachrichten vom Standard-Chatfenster unterdr\195\188cken.",
    ["Play sound when message is received."] = "Ger\195\164usch abspielen, wenn eine Nachricht erhalten wurde.",
    ["Play sound when message is sent."] = "Ger\195\164usch abspielen, wenn eine Nachricht versendet wurde.",
    ["Sort alphabetically."] = "Alphabetisch sortieren.",
    ["Use <Escape> to close windows."] = "<Escape> benutzen k\195\182nnen, um Fenster zu schlie\195\159en.",
    ["Windows will close when opening the world map."] = "Fenster sollen sich schlie\195\159en, sobald Weltkarte ge\195\182ffnet wird.",
    ["Intercept slash commands."] = "Slash-Befehle abfangen.",
    ["Ignore arrow keys while typing."] = "Pfeiltasten ignorieren, w\195\164hrend getippt wird.",
    ["Requires using <Alt> to navigate text."] = "Ben\195\182tigt gedr\195\188ckte <Alt>-Taste um durch den Text zu navigieren.",
    ["Display emoticons."] = "Zeige Emoticons/Smileys an.",
    ["Display URLs as item links."] = "Zeige Internet-Adressen als Itemlinks an.",
    ["Display floating item links."] = "Zeige schwebende Itemlinks.",
    
    ["Cascade windows."] = "Fenster hintereinanderschalten.",
    ["Direction:"] = "Richtung:",
    ["Tabs"] = true,
    ["Sort tabs by:"] = "Sortiere Tabs:",
    ["Alphabetical"] = "Alphabetisch",
    ["Recent Activity"] = "Letzte Aktion",
    ["Keep windows on top of your UI."] = "Fenster im Vordergrund des Interface halten.",
    
    -- Class Names --
    ["Druid"] = "Druide",
    ["Hunter"] = "J\195\164ger",
    ["Mage"] = "Magier",
    ["Paladin"] = "Paladin",
    ["Priest"] = "Priester",
    ["Rogue"] = "Schurke",
    ["Shaman"] = "Schamane",
    ["Warlock"] = "Hexenmeister",
    ["Warrior"] = "Krieger",
    ["Death Knight"] = "Todesritter",
    
    -- Female Class Names --
    ["DruidF"] = "Druidin",
    ["HunterF"] = "J\195\164gerin",
    ["MageF"] = "Magierin",
    ["PaladinF"] = "Paladin",
    ["PriestF"] = "Priesterin",
    ["RogueF"] = "Schurkin",
    ["ShamanF"] = "Schamanin",
    ["WarlockF"] = "Hexenmeisterin",
    ["WarriorF"] = "Kriegerin",
    ["Death KnightF"] = "Todesritter",
    
    ["Game Master"] = true,
    
    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Schalte WIM 'Ein' oder 'Aus'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Schalte Debugging Modus 'Ein' oder 'Aus'",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM ist zur Zeit aktiv. Um die breite Auswahl an Einstellungen vornehmen zu k\195\182nnen, gebe ein:",
    
    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Fl\195\188sternachrichten gesendet durch AddOns",
    ["WhisperSelect Part 1"] = "Fl\195\188sterAuswahl Teil 1",
    ["Example Spam Blocker"] = "Beispiel Spamblocker",
    ["WhisperSelect Part 2"] = "Fl\195\188sterAuswahl Teil 2",
    ["Filter Name"] = true,
    ["Filter By"] = "Filtern nach",
    ["Pattern"] = "Muster",
    ["User Type"] = "Spielertyp",
    ["Level"] = "Level",
    ["Friends"] = "Freunde",
    ["Guild Members"] = "Gildenmitglieder",
    ["Party Members"] = "Gruppenmitglieder",
    ["Raid Members"] = "Schlachtzugsmitglieder",
    ["Cross-Realm"] = "Realm-\195\156bergreifend",
    ["Everyone"] = "Alle",
    ["User must be at least level:"] = "Spieler muss mindestens diesen Level haben:",
    ["Apply to messages received."] = "F\195\188r eingehende Nachrichten \195\188bernehmen.",
    ["Apply to messages sent."] = "F\195\188r ausgehende Nachrichten \195\188bernehmen.",
    ["Action to Perform:"] = "Durchzuf\195\188hrende Aktion:",
    ["Allow"] = "Erlauben",
    ["Ignore"] = "Ignorieren",
    ["Blocked"] = "Blockieren",
    ["Save"] = "Speichern",
    ["Cancel"] = "Abbrechen",
    ["Edit Filter"] = "Filter bearbeiten",
    ["Add Filter"] = "Filter hinzuf\195\188gen",
    
    -- History.lua --
    ["WIM History Button"] = "WIM Verlaufsbutton",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Das Klicken auf den %s Button auf dem Nachrichtenfenster zeigt den Nachrichtenverlauf mit dem Spieler in der WIM Verlaufsanzeige.",
    ["Click to view message history."] = "Klicken um den Nachrichtenverlauf anzuzeigen.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM hat %d |4message:messages; von deinem Nachrichtenverlauf gel\195\182scht.",
    ["History Viewer"] = "Verlaufsanzeige",
    ["Filters"] = "Filter",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Bist du sicher, dass du s\195\164mtliche Nachrichtenverl\195\164ufe gespeichert f\195\188r %s auf %s l\195\182schen m\195\182chtest?",
    ["Search resulted in %d |4message:messages;."] = "Ergebnis der Suche resultiert in %d |4message:messages;.",
    ["No results found!"] = "Keine Ergebnisse gefunden!",
    ["Search"] = "Suche",
    ["Show All"] = "Alle anzeigen",
    ["Loading History"] = "Verlauf wird geladen",
    ["Chat View"] = "Chatansicht",
    ["Text View"] = "Textansicht",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM Verlaufsanzeige kann jederzeit aufgerufen werden durch dr\195\188cken von:",
    ["WIM History Viewer"] = "WIM Verlaufsanzeige",
    ["Display history viewer."] = "Verlaufsanzeige anzeigen",
    
    -- ldb.lua --
    ["No New Messages"] = "Keine neuen Nachrichten",
    
    -- Menu.lua --
    ["Whispers"] = "Fl\195\188sternachrichten",
    ["Chat"] = true,
    
    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM Update verf\195\188gbar!",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "Es ist eine neuere Version von WIM zum Download verf\195\188gbar. Du kannst sie herunterladen auf %s.",
    
    -- ShortcutBar.lua --
    ["Player Location"] = "Spieler Standort",
    ["Unknown"] = "Unbekannt",
    ["Click to update..."] = "Klicke um ein Update zu starten...",
    ["Coordinates"] = "Koordinaten",
    ["Invite to Party"] = "In die Gruppe einladen",
    ["Add Friend"] = "Freund hinzuf\195\188gen",
    ["Ignore User"] = "Spieler ignorieren",
    ["Are you sure you want to\nignore %s?"] = "Bist du sicher, dass du \n %s ignorieren willst?",
    
    -- Tutorials.lua --
    ["Display WIM tips"] = "WIM Tipps anzeigen",
    
    -- W2W.lua --
    ["%s is typing..."] = "%s tippt...",
    ["W2W Profile"] = "W2W Profil",
    
    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Fl\195\188sternachricht erhalten!",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Du hast eine Fl\195\188sternachricht erhalten, welche aufgrund deines Charakterzustandes zu dem Zeitpunkt nicht angezeigt wurde. Du kannst das Verhalten der Anzeige von Fl\195\188sternachrichten in bestimmten Situationen in den WIM Optionen \195\164ndern durch Dr\195\188cken von",
    
    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Du bist dabei den gesamten WIM Nachrichtenverlauf zu l\195\182schen!",
    ["This action will reload your user interface."] = "Dieser Vorgang wird dein Interface neu laden.",
    ["Do you want to continue?"] = "Willst du fortfahren?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Du bist dabei die WIM Filtereinstellungen auf die Standardeinstellungen zur\195\188ckzusetzen!",
    ["Usage"] = "Gebrauch",
    ["Clear various WIM data."] = "L\195\182sche diverse WIM Daten.",
    
    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM Slash-Befehle",
    ["To see a list of available WIM slash commands type:"] = "Um eine Liste von verf\195\188gbaren WIM-Befehlen zu erhalten gebe ein:",
    ["Display available slash commands."] = "Zeige verf\195\188gbare Slash-Befehle an.",
    ["Reload User Interface."] = "Lade Spieler-Interface neu.",
    
    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipulation von Tabs",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "<Shift-Klick> auf einen Tab erlaubt dir ihn aus dem eigenen Fenster zu ziehen.",
    
    -- WindowHandler.lua --
    ["Window Resized!"] = "Fenstergr\195\182\195\159e angepasst!",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Wenn du m\195\182chtest, dass alle Fenster diese Gr\195\182\195\159e haben, dann kannst du die Standardgr\195\182\195\159e von Fenstern in den WIM Optionen einstellen.",
    ["Creating Tab Groups"] = "Erstellung von Tab-Gruppen",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Du kannst zwei oder mehrere Fenster zusammengruppieren indem du ein Fenster <Shift-Klickst> und es auf ein anderes ziehst.",
    ["Resizing Windows"] = "Gr\195\182\195\159enanpassung von Fenstern",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Du kannst die Gr\195\182\195\159e eines Fensters anpassen, indem du <Shift> gedr\195\188ckt h\195\164ltst und die obere rechte Ecke des Fensters ziehst.",
    ["Demo Window"] = "Demonstrationsfenster",
    ["<Shift-Click> to close window."] = "<Shift-Klicken> um Fenster zu schlie\195\159en.",
    ["Message Window Hidden"] = "Nachrichtenfenster versteckt",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "WIMs Nachrichtenfenster wurde im WIM Minimap-Symbol versteckt. Wenn du eine Konversation beenden m\195\182chtest, kannst du das durch einen <Shift-Klick> auf den Schlie\195\159en-Button tun.",
    ["Default"] = "Standard",
    ["%s is Away From Keyboard: %s"] = "%s ist AFK (Away From Keyboard/Abwesend): %s",
    ["%s does not wish to be disturbed: %s"] = "%s m\195\182chte nicht gest\195\182rt werden: %s",
    
    -- Options.lua --
    ["Display WIM's options."] = "WIM Optionen anzeigen.",
    ["Resetting WIM will clear all of your settings!"] = "Das Zur\195\188cksetzen von WIM wird s\195\164mtliche deiner Einstellungen l\195\182schen!",
    ["Reset all options to default."] = "Alle Einstellungen zur\195\188cksetzen.",
    
    -- CoreOptions --
    ["Created by:"] = "Kreiert von:",
    ["Special Thanks:"] = "Besonderer Dank:",
    ["Welcome!"] = "Willkommen!",
    ["Enable WIM"] = "WIM aktivieren",
    ["Display Minimap Icon"] = "Minimap-Symbol anzeigen",
    ["<Right-Click> to show unread messages."] = "<Rechts-Klick> um ungelesene Nachrichten anzuzeigen.",
    ["Display Tutorials"] = "Tutorials anzeigen",
    ["Reset Tutorials"] = "Tutorials zur\195\188cksetzen",
    ["Credits"] = true,
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Dies ist eine lange Nachricht, die sowohl Emoticons/Smileys, als auch Internetadressen enth\195\164lt 8). WIMs Homepage ist www.WIMAddon.com.",
    ["Message Formatting"] = "Nachrichtenformatierung",
    ["Manipulate how WIM displays messages."] = "Stelle ein, wie WIM Nachrichten darstellen soll.",
    ["Preview"] = "Vorschau",
    ["Display Time Stamps"] = "Zeitstempel anzeigen",
    ["Display Emoticons"] = "Emoticons/Smileys anzeigen",
    ["Display URLs as Links"] = "Internetadressen als Links anzeigen",
    ["Indent long messages."] = "Lange Nachrichten einr\195\188cken.",
    ["Window Behavior"] = "Fensterverhalten",
    ["You can control how windows behave while you are in different situations."] = "Du kannst das Verhalten von Fenstern in verschiedenen Situationen einstellen.",
    ["Intercept Slash Commands"] = "Slash-Befehle abfangen",
    ["Use the same rules for all states."] = "Dieselben Regeln f\195\188r alle Situationen anwenden.",
    ["Behaviors for state:"] = "Verhalten f\195\188r Situation:",
    ["Pop-Up window when message is sent."] = "Fenster als Pop-Up sobald Nachricht versendet wurde.",
    ["Pop-Up window when message is received."] = "Fenster als Pop-Up sobald Nachricht erhalten wurde.",
    ["Auto focus a window when it is shown."] = "Automatischer Textcursor-Fokus wenn sich ein Fenster \195\182ffnet.",
    ["Keep focus on window after sending a message."] = "Textcursor-Fokus nach der Nachrichtenversendung beibehalten.",
    ["Suppress messages from the default chat frame."] = "Nachrichten vom Standard-Chatfenster unterdr\195\188cken.",
    ["Window Settings"] = "Fenstereinstellungen",
    ["Some settings may be limited by certain skins."] = "Manche Einstellungen k\195\182nnen auf bestimmte Skins begrenzt sein.",
    ["Default Width"] = "Standardbreite",
    ["Default Height"] = "Standardh\195\182he",
    ["Window Scale"] = "Fensterskalierung",
    ["Window Alpha"] = "Fenstertransparenz",
    ["Set Window Spawn Location"] = "Stelle Erzeugungspunkt f\195\188r Fenster ein",
    ["Up"] = "Oben",
    ["Down"] = "Unten",
    ["Left"] = "Links",
    ["Right"] = "Rechts",
    ["Cascade overlapping windows."] = "\195\156berlappende Fenster hintereinanderschalten.",
    ["Ignore arrow keys in message box."] = "Pfeiltasten im Nachrichtenfenster ignorieren.",
    ["Allow <ESC> to hide windows."] = "<ESC> zum verstecken von Fenstern erlauben.",
    ["Display Settings"] = "Anzeige-Einstellungen",
    ["Configure general window display settings."] = "Allgemeine Einstellungen zur Fensteranzeige konfigurieren.",
    ["Window Skin:"] = "Fenster-Skin:",
    ["Version"] = true,
    ["Color: System Messages"] = "Farbe: Systemnachrichten",
    ["Color: Error Messages"] = "Farbe: Fehlernachrichten",
    ["Color: URL - Web Addresses"] = "Farbe: Internetadressen",
    ["Color: History Messages Sent"] = "Farbe: Versendete Nachrichten im Nachrichtenverlauf",
    ["Color: History Messages Received"] = "Farbe: Empfangene Nachrichten im Nachrichtenverlauf",
    ["Use colors suggested by skin."] = "Verwende f\195\188r den Skin empfohlene Farben.",
    ["Enable window fading effects."] = "Fenster-Verblassungseffekte aktivieren.",
    ["Enable window animation effects."] = "Fenster-Animationseffekte aktivieren.",
    ["Display item links when hovering over them."] = "Itemlinks bei Mouseover anzeigen.",
    ["Fonts"] = "Schriftarten",
    ["Configure the fonts used in WIM's message windows."] = "Schriftarten in den WIM Nachrichtenfenstern konfigurieren.",
    ["Font Outline"] = "Schriftart-Au\195\159enlinie",
    ["Thin"] = "D\195\188nn",
    ["Thick"] = "Dick",
    ["Use font suggested by skin."] = "Verwende f\195\188r den Skin empfohlene Schriftart.",
    ["Chat Font Size"] = "Chat Schriftgr\195\182\195\159e",
    ["Configure general display settings when dealing with whispers."] = "Konfiguriere allgemeine Darstellungsoptionen bei Fl\195\188sternachrichten.",
    ["Color: Messages Sent"] = "Farbe: Gesendete Nachrichten",
    ["Color: Messages Received"] = "Farbe: Empfangene Nachrichten",
    ["Use colors suggested by skin."] = "Verwende f\195\188r den Skin empfohlene Farben.",
    ["Display user class icons and details."] = "Zeige Spieler Klassensymbole und Details an.",
    ["Requires who lookups."] = "Ben\195\182tigt /wer Abfragen.",
    ["Display Shortcut Bar"] = "Zeige Funktionsleiste (rechts) an.",
    ["Allow"] = "Erlauben",
    ["Ignore"] = "Ignorieren",
    ["Block"] = "Blockieren",
    ["Filtering"] = "Filterung",
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = "Filtern erlaubt dir die Kontrolle dar\195\188ber zu haben welche Nachrichten wie von WIM gehandhabt werden.",
    ["Enable Filtering"] = "Filterung aktivieren.",
    ["Protected"] = "Gesichert",
    ["Action:"] = "Aktion:",
    ["Occurrences:"] = "Vorf\195\164lle:",
    ["Delete Filter"] = "Filter l\195\182schen",
    ["History"] = "Nachrichtenverlauf",
    ["WIM can store conversations to be viewed at a later time."] = "WIM kann Konversationen speichern, um sie zu einem sp\195\164teren Zeitpunkt wieder anzuzeigen.",
    ["Enable History"] = "Nachrichtenverlauf aktivieren.",
    ["Messages"] = "Nachrichten",
    ["Preview history inside message windows."] = "Vorschau des Nachrichtenverlaufs innerhalb \n der Nachrichtenfenster anzeigen.",
    ["Record Whispers"] = "Fl\195\188sternachrichten \n aufzeichnen von",
    ["Record Friends"] = "Freunden",
    ["Record Guild"] = "Gildenmitgliedern",
    ["Record Everyone"] = "Allen",
    ["Record Chat"] = "Chat aufzeichnen",
    ["Maintenance"] = "Wartung",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Wenn du deinen Nachrichtenverl\195\164ufen erm\195\182glichst \n zu lang/gro\195\159 zu werden, k\195\182nnte dies die Performance des Spiels beeintr\195\164chtigen, deswegen ist es empfehlenswert, dass du folgende Einstellungen nutzt.",
    ["Save a maximum number of messages per person."] = "Speichere eine Maximalzahl an Nachrichten pro Spieler.",
    ["%d |4Week:Weeks;"] = true,
    ["Automatically delete old messages."] = "Automatisch alte Nachrichten l\195\182schen.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM ist eine Funktion, die WIM erlaubt mit Spielern, die ebenfalls WIM nutzen, auf bestimmte Arten zu interagieren, die \195\188ber normales Fl\195\188stern nicht m\195\182glich sind.",
    ["Enable WIM-2-WIM"] = "WIM-2-WIM aktivieren",
    ["Privacy"] = "Privatsph\195\164re",
    ["Restrict the data that is shared."] = "Austauschbare Daten eingrenzen.",
    ["Allow others to see me typing."] = "Erlaube Anderen zu sehen, wann ich tippe.",
    ["Allow others to see my location."] = "Erlaube Anderen meinen Standort zu sehen.",
    ["Main"] = "Haupteinstellungen",
    ["General"] = "Allgemein",
    ["User Level"] = "Spielerlevel",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Fenster werden ebenfalls versteckt, sobald andere Fenster, wie etwa die Weltkarte, angezeigt werden.",
    
    -- TabManagement.lua --
    ["Tab Management"] = true,
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Manage automatisch deine offenen Fenster und platziere sie in angemessene Tabgruppen.",
    ["Automatically group whispers."] = "Automatische Gruppen-Fl\195\188sternachrichten.",
    ["Place friends in their own group."] = "Platziere Freunde in ihre eigene Gruppe.",
    ["Place guild members in their own group."] = "Platziere Gildenmitglieder in ihre eigene Gruppe.",
    ["Does not apply to windows already opened."] = "Wird nicht f\195\188r Fenster \195\188bernommen, die bereits ge\195\182ffnet sind.",
    
    
    -- Talent Specs --
    ["Affliction"] = "Gebrechen",
    ["Arcane"] = "Arkan",
    ["Arms"] = "Waffen",
    ["Assassination"] = "Meucheln",
    ["Balance"] = "Gleichgewicht",
    ["Beast Mastery"] = "Tierherrschaft",
    ["Blood"] = "Blut",
    ["Combat"] = "Kampf",
    ["Demonology"] = "Dämonologie",
    ["Destruction"] = "Zerstörung",
    ["Discipline"] = "Disziplin",
    ["Elemental"] = "Elementar",
    ["Enhancement"] = "Verstärkung",
    ["Feral Combat"] = "Wilder Kampf",
    ["Fire"] = "Feuer",
    ["Frost"] = "Frost",
    ["Fury"] = "Furor",
    ["Holy"] = "Heilig",
    ["Hybrid"] = "Hybride",
    ["Marksmanship"] = "Treffsicherheit",
    ["Protection"] = "Schutz",
    ["Restoration"] = "Wiederherstellung",
    ["Retribution"] = "Vergeltung",
    ["Shadow"] = "Schatten",
    ["Subtlety"] = "Täuschung",
    ["Survival"] = "Überleben",
    ["Unholy"] = "Unheilig",

    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Zeige ungelesene Nachrichten",
    ["Show All Windows"] = "Zeige alle Fenster",
    ["Hide All Windows"] = "Verberge alle Fenster",
    
});