--[[
    Language Localization: enUS
    Translated by: name <email address>
]]

WIM.AddLocale("enUS", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM is an addon that brings a familiar feel to communicating through chat in The World of Warcraft. On this screen you will be able to customize WIM to tailor it to your needs. If you have any questions, comments or suggestions please go to http://www.WIMAddon.com.",

    ["_DemoText"] = "This is a demonstration window and is not fully functional. Place this window in the location where you want all other windows to spawn. When finished, you may close this window and your settings will be saved.",

    ["_DateFormat"] = "%m/%d/%Y",

    ["Yes"] = true,
    ["No"] = true,
    ["None"] = true,
    ["<Right-Click>"] = true,
    ["<Left-Click>"] = true,
    ["OK"] = true,
    ["Cancel"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Usage"] = true,
    
    ["state_resting"] = "Resting",
    ["state_combat"] = "Combat",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arena",
    ["state_party"] = "Party Instance",
    ["state_raid"] = "Raid Instance",
    ["state_other"] = "Normal (Other)",
    
    ["<Shift-Click> to close window."] = true,
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = true,
    
    ["Options"] = true,
    
    ["Icon Position"] = true,
    ["Font Size"] = true,
    ["Window Scale (Percent)"] = true,
    ["Transparency (Percent)"] = true,
    ["Window Width"] = true,
    ["Window Height"] = true,
    ["(Limited by shortcut bar)"] = true,
    ["ERROR"] = true,
    ["Invalid Name!"] = true,
    ["Name is already used!"] = true,
    ["Invalid Alias!"] = true,
    ["Invalid Keyword/Phrase!"] = true,
    ["Keyword/Phrase is already used!"] = true,
    
    ["Day"] = true,
    ["Week"] = true,
    ["Month"] = true,
    ["Drag to set default spawn/position for message windows."] = true,
    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Enable WIM"] = true,
    
    ["Auto Close Friends after:"] = true,
    ["Auto Close Non-Friends after:"] = true,
    
    ["Display"] = true,
    ["Incoming Messages"] = true,
    ["Outgoing Messages"] = true,
    ["System Messages"] = true,
    ["Error Messages"] = true,
    ["Web URLs"] = true,
    ["Enable"] = true,
    ["Disable"] = true,
    ["Enabled"] = true,
    ["Disabled"] = true,
    ["Display character information."] = true,
    ["Display time stamps"] = true,
    ["This setting limits the\nwindow's minimum height."] = true,
    ["Requires /who querying."] = true,
    ["Enable window fading effects."] = true,
    ["Enable window animations."] = true,
    
    ["Display minimap icon."] = true,
    
    ["General"] = true,
    ["History"] = true,
    ["Filters"] = true,
    ["Plugins"] = true,
    
    ["Auto focus when window is shown."] = true,
    ["Preserve focus after sending messages."] = true,
    ["Display tooltips."] = true,
    ["Show window when sending a message."] = true,
    ["Show window when message has been received."] = true,
    ["Supress messages from default chat frame."] = true,
    ["Play sound when message is received."] = true,
    ["Play sound when message is sent."] = true,
    ["Sort alphabetically."] = true,
    ["Use <Escape> to close windows."] = true,
    ["Windows will close when opening the world map."] = true,
    ["Intercept slash commands."] = true,
    ["Ignore arrow keys while typing."] = true,
    ["Requires using <Alt> to navigate text."] = true,
    ["Display emoticons."] = true,
    ["Display URLs as item links."] = true,
    ["Display floating item links."] = true,
    
    ["Cascade windows."] = true,
    ["Direction:"] = true,
    ["Tabs"] = true,
    ["Sort tabs by:"] = true,
    ["Alphabetical"] = true,
    ["Recent Activity"] = true,
    ["Keep windows on top of your UI."] = true,
    
    ["Enable/Disable addon messages."] = true,
    
    -- Class Names --
    ["Druid"] = true,
    ["Hunter"] = true,
    ["Mage"] = true,
    ["Paladin"] = true,
    ["Priest"] = true,
    ["Rogue"] = true,
    ["Shaman"] = true,
    ["Warlock"] = true,
    ["Warrior"] = true,
    ["Death Knight"] = true,
    
    -- Female Class Names --
    ["DruidF"] = "Druid",
    ["HunterF"] = "Hunter",
    ["MageF"] = "Mage",
    ["PaladinF"] = "Paladin",
    ["PriestF"] = "Priest",
    ["RogueF"] = "Rogue",
    ["ShamanF"] = "Shaman",
    ["WarlockF"] = "Warlock",
    ["WarriorF"] = "Warrior",
    ["Death KnightF"] = "Death Knight",
    
    ["Game Master"] = true,
    
    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = true,
    ["Toggle Debugging Mode 'On' and 'Off'."] = true,
    ["WIM is currently running. To access WIM's wide array of options type:"] = true,
    
    -- Filters.lua --
    ["Whispers Sent by Addons"] = true,
    ["WhisperSelect Part 1"] = true,
    ["Example Spam Blocker"] = true,
    ["WhisperSelect Part 2"] = true,
    ["Filter Name"] = true,
    ["Filter By"] = true,
    ["Pattern"] = true,
    ["User Type"] = true,
    ["Level"] = true,
    ["Friends"] = true,
    ["Guild Members"] = true,
    ["Party Members"] = true,
    ["Raid Members"] = true,
    ["Cross-Realm"] = true,
    ["Everyone"] = true,
    ["User must be at least level:"] = true,
    ["Apply to messages received."] = true,
    ["Apply to messages sent."] = true,
    ["Action to Perform:"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Blocked"] = true,
    ["Save"] = true,
    ["Cancel"] = true,
    ["Edit Filter"] = true,
    ["Add Filter"] = true,
    
    -- History.lua --
    ["WIM History Button"] = true,
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = true,
    ["Click to view message history."] = true,
    ["WIM pruned %d |4message:messages; from your history."] = true,
    ["History Viewer"] = true,
    ["Filters"] = true,
    ["Are you sure you want to delete all history saved for %s on %s?"] = true,
    ["Search resulted in %d |4message:messages;."] = true,
    ["No results found!"] = true,
    ["Search"] = true,
    ["Show All"] = true,
    ["Loading History"] = true,
    ["Chat View"] = true,
    ["Text View"] = true,
    ["WIM History Viewer can be accessed any time by typing:"] = true,
    ["WIM History Viewer"] = true,
    ["Display history viewer."] = true,
    
    -- ldb.lua --
    ["No New Messages"] = true,
    
    -- Menu.lua --
    ["Whispers"] = true,
    ["Chat"] = true,
    
    -- Negotiate.lua --
    ["WIM Update Available!"] = true,
    ["There is a newer version of WIM available for download. You can download it at %s."] = true,
    
    -- ShortcutBar.lua --
    ["Player Location"] = true,
    ["Unknown"] = true,
    ["Click to update..."] = true,
    ["Coordinates"] = true,
    ["Invite to Party"] = true,
    ["Add Friend"] = true,
    ["Ignore User"] = true,
    ["Are you sure you want to\nignore %s?"] = true,
    ["Right-Click for profile links..."] = true,
    ["Profile Links"] = true,
    
    -- Tutorials.lua --
    ["Display WIM tips"] = true,
    
    -- W2W.lua --
    ["%s is typing..."] = true,
    ["W2W Profile"] = true,
    ["Talent Spec"] = true,
    
    -- WhisperEngine.lua --
    ["Whisper Received!"] = true,
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = true,
    ["Recently Sent Messages"] = true,
    
    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = true,
    ["This action will reload your user interface."] = true,
    ["Do you want to continue?"] = true,
    ["You are about to restore WIM's filters to it's default settings!"] = true,
    ["Usage"] = true,
    ["Clear various WIM data."] = true,
    
    -- SlashHandler.lua --
    ["WIM Slash Commands"] = true,
    ["To see a list of available WIM slash commands type:"] = true,
    ["Display available slash commands."] = true,
    ["Reload User Interface."] = true,
    
    -- TabHandler.lua --
    ["Manipulating Tabs"] = true,
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = true,
    
    -- WindowHandler.lua --
    ["Window Resized!"] = true,
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = true,
    ["Creating Tab Groups"] = true,
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = true,
    ["Resizing Windows"] = true,
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = true,
    ["Demo Window"] = true,
    ["<Shift-Click> to close window."] = true,
    ["Message Window Hidden"] = true,
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = true,
    ["Default"] = true,
    ["%s is Away From Keyboard: %s"] = true,
    ["%s does not wish to be disturbed: %s"] = true,
    ["Right-Mouse Click!"] = true,
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = true,
    
    
    -- Options.lua --
    ["Display WIM's options."] = true,
    ["Resetting WIM will clear all of your settings!"] = true,
    ["Reset all options to default."] = true,
    
    -- CoreOptions --
    ["Created by:"] = true,
    ["Special Thanks:"] = true,
    ["Welcome!"] = true,
    ["Enable WIM"] = true,
    ["Display Minimap Icon"] = true,
    ["<Right-Click> to show unread messages."] = true,
    ["Display Tutorials"] = true,
    ["Reset Tutorials"] = true,
    ["Credits"] = true,
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = true,
    ["Message Formatting"] = true,
    ["Manipulate how WIM displays messages."] = true,
    ["Preview"] = true,
    ["Display Time Stamps"] = true,
    ["Display Emoticons"] = true,
    ["Display URLs as Links"] = true,
    ["Indent long messages."] = true,
    ["Window Behavior"] = true,
    ["You can control how windows behave while you are in different situations."] = true,
    ["Intercept Slash Commands"] = true,
    ["Use the same rules for all states."] = true,
    ["Behaviors for state:"] = true,
    ["Pop-Up window when message is sent."] = true,
    ["Pop-Up window when message is received."] = true,
    ["Auto focus a window when it is shown."] = true,
    ["Keep focus on window after sending a message."] = true,
    ["Suppress messages from the default chat frame."] = true,
    ["Window Settings"] = true,
    ["Some settings may be limited by certain skins."] = true,
    ["Default Width"] = true,
    ["Default Height"] = true,
    ["Window Scale"] = true,
    ["Window Alpha"] = true,
    ["Set Window Spawn Location"] = true,
    ["Up"] = true,
    ["Down"] = true,
    ["Left"] = true,
    ["Right"] = true,
    ["Cascade overlapping windows."] = true,
    ["Ignore arrow keys in message box."] = true,
    ["Allow <ESC> to hide windows."] = true,
    ["Display Settings"] = true,
    ["Configure general window display settings."] = true,
    ["Window Skin:"] = true,
    ["Version"] = true,
    ["Color: System Messages"] = true,
    ["Color: Error Messages"] = true,
    ["Color: URL - Web Addresses"] = true,
    ["Color: History Messages Sent"] = true,
    ["Color: History Messages Received"] = true,
    ["Use colors suggested by skin."] = true,
    ["Enable window fading effects."] = true,
    ["Enable window animation effects."] = true,
    ["Display item links when hovering over them."] = true,
    ["Fonts"] = true,
    ["Configure the fonts used in WIM's message windows."] = true,
    ["Font Outline"] = true,
    ["Thin"] = true,
    ["Thick"] = true,
    ["Use font suggested by skin."] = true,
    ["Chat Font Size"] = true,
    ["Configure general display settings when dealing with whispers."] = true,
    ["Color: Messages Sent"] = true,
    ["Color: Messages Received"] = true,
    ["Use colors suggested by skin."] = true,
    ["Display user class icons and details."] = true,
    ["Requires who lookups."] = true,
    ["Display Shortcut Bar"] = true,
    ["Allow"] = true,
    ["Ignore"] = true,
    ["Block"] = true,
    ["Filtering"] = true,
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = true,
    ["Enable Filtering"] = true,
    ["Protected"] = true,
    ["Action:"] = true,
    ["Occurrences:"] = true,
    ["Delete Filter"] = true,
    ["History"] = true,
    ["WIM can store conversations to be viewed at a later time."] = true,
    ["Enable History"] = true,
    ["Messages"] = true,
    ["Preview history inside message windows."] = true,
    ["Record Whispers"] = true,
    ["Record Friends"] = true,
    ["Record Guild"] = true,
    ["Record Everyone"] = true,
    ["Record Chat"] = true,
    ["Maintenance"] = true,
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = true,
    ["Save a maximum number of messages per person."] = true,
    ["%d |4Week:Weeks;"] = true,
    ["Automatically delete old messages."] = true,
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = true,
    ["Enable WIM-2-WIM"] = true,
    ["Privacy"] = true,
    ["Restrict the data that is shared."] = true,
    ["Allow others to see me typing."] = true,
    ["Allow others to see my location."] = true,
    ["Main"] = true,
    ["General"] = true,
    ["User Level"] = true,
    ["Windows will also be hidden when frames such as the world map are shown."] = true,
    ["Sounds"] = true,
    ["Configure various sound events and how they are triggered."] = true,
    ["Play sound when a whisper is received."] = true,
    ["Play special sound for friends."] = true,
    ["Play special sound for guild members."] = true,
    ["Play sound when a whisper is sent."] = true,
    ["Allow others to see my talent spec."] = true,
    ["Window Strata:"] = true,
    ["Unlock from Minimap"] = true,
    ["Press <Tab> to advance to next tell target."] = true,
    ["Colorize names."] = true,
    ["Clamp window to screen."] = true,
    ["Group with whisper windows."] = true,
    
    -- TabManagement.lua --
    ["Tab Management"] = true,
    ["Automatically manage your open windows and place them into appropriate tab groups."] = true,
    ["Automatically group whispers."] = true,
    ["Place friends in their own group."] = true,
    ["Place guild members in their own group."] = true,
    ["Does not apply to windows already opened."] = true,
    
    
    -- Talent Specs --
    ["Affliction"] = true,
    ["Arcane"] = true,
    ["Arms"] = true,
    ["Assassination"] = true,
    ["Balance"] = true,
    ["Beast Mastery"] = true,
    ["Blood"] = true,
    ["Combat"] = true,
    ["Demonology"] = true,
    ["Destruction"] = true,
    ["Discipline"] = true,
    ["Elemental"] = true,
    ["Enhancement"] = true,
    ["Feral Combat"] = true,
    ["Fire"] = true,
    ["Frost"] = true,
    ["Fury"] = true,
    ["Holy"] = true,
    ["Hybrid"] = true,
    ["Marksmanship"] = true,
    ["Protection"] = true,
    ["Restoration"] = true,
    ["Retribution"] = true,
    ["Shadow"] = true,
    ["Subtlety"] = true,
    ["Survival"] = true,
    ["Unholy"] = true,
    
    -- ChangeLog.lua --
    ["Change Log"] = true,
    ["View WIM's change log."] = true,
    ["Available For Download!"] = true,
    
    -- Filters.lua --
    ["Show Alert"] = true,
    ["WIM has blocked a message from %s."] = true,
    ["View Blocked Message"] = true,
    ["Blocked Message"] = true,
    
    -- MinimapIcon.lua
    ["Show Unread Messages"] = true,
    ["Show All Windows"] = true,
    ["Hide All Windows"] = true,
    
    --Emoticons.lua
    ["Also"] = true,
    ["More"] = true,
    ["Emoticons"] = true,
    
    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = true,
    ["Expose"] = true,
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = true,
    ["Auto hide/restore windows during combat."] = true,
    ["Border Size"] = true,
    ["Only while in an instance."] = true,
    ["Show Border"] = true,
    ["Animation Direction:"] = true,
    
    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = true,
    ["Show Minimap Alerts"] = true,
    ["Never pop-up on my screen."] = true,
    ["Never suppress messages."] = true,
    ["Have WIM monitor this channel."] = true,
    ["Never Pop"] = true,
    ["Never have this window pop-up on my screen."] = true,
    ["Never Supress"] = true,
    ["Never suppress messages from the default chat frame."] = true,
    ["Show unread message alert on minimap."] = true,
    ["No History"] = true,
    ["Do not record history for this channel."] = true,
    ["World Chat"] = true,
    ["Custom Chat"] = true,
    ["Chat"] = true,
    ["Play special sound for %s."] = true,
    ["Play sound when a message is received."] = true,
    ["Play sound when a message is sent."] = true,
    ["Do not play sounds for this channel."] = true,
    ["No Sound"] = true,
    ["Sensitivity"] = true,
    ["Enable WorldFrame Click Detection."] = true,
    ["The UI must be reloaded in order to disable this module fully. Reload UI now?"] = true,
    
    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = true,
    ["Click to reposition."] = true,
    
    --Misc
    ["WIM has detected that you are playing on a private server. Some servers can not process ChatAddonMessages. Would you like to enable them anyway?"] = true,
    
});