--[[
    Language Localization: frFR
    Translated by: name <email address>
]]

WIM.AddLocale("frFR", {

    ["WIM (WoW Instant Messenger)"] = "",
    ["_Description"] = "WIM est un addon qui apporte un sens familier à la communication par le chat dans World of Warcraft. Sur cet écran, vous serez en mesure de personnaliser WIM de l'adapter à vos besoins. Si vous avez des questions, commentaires ou suggestions s'il vous plaît aller à http://www.WIMAddon.com.",

    ["_DemoText"] = "C'est une fenêtre de démonstration elle n'est pas entièrement fonctionnel. Placez cette fenêtre à l'endroit où vous voulez que toutes les autres fenêtres s'ouvrent. Quand c'est bon, vous pouvez fermer cette fenêtre et vos vos réglages seront sauvegardés.",

    ["_DateFormat"] = "%d/%m/%Y",
    
     ["Yes"] = "Oui",
    ["No"] = "Non",
    ["None"] = "Aucun",
    ["<Right-Click>"] = "<Clic-droit>",
    ["<Left-Click>"] = "<Clic-gauche>",
    ["OK"] = "Ok",
    ["Cancel"] = "Annuler",
    ["Unknown"] = "Inconnu",
    ["Click to update..."] = "Cliquez pour mettre à jour ...",
    ["Usage"] = "Usage",
    
    ["state_resting"] = "Repos",
    ["state_combat"] = "Combat",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "Arène",
    ["state_party"] = "Instance de Groupe",
    ["state_raid"] = "Raid Instance",
    ["state_other"] = "Normal (Divers)",
    
    ["<Shift-Click> to close window."] = "<Clic-Shift> pour fermer la fenêtre.",
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "Une nouvelle version de WIM est disponible!\n Vous pouvez télécharger la dernière version en allant sur: \n\n http://www.wimaddon.com",
    
    ["Options"] = "Options",
    
    ["Icon Position"] = "Icône de position",
    ["Font Size"] = "Taille de la police",
    ["Window Scale (Percent)"] = "Échelle de la Fenêtre (en pourcentage)",
    ["Transparency (Percent)"] = "Transparence (en pourcentage)",
    ["Window Width"] = "Largeur de la fenêtre",
    ["Window Height"] = "Hauteur de la fenêtre",
    ["(Limited by shortcut bar)"] = "(Limité par la barre de raccourcis)",
    ["ERROR"] = "Erreur",
    ["Invalid Name!"] = "Nom incorrect!",
    ["Name is already used!"] = "Nom est déjà utilisé!",
    ["Invalid Alias!"] = "Alias incorrect",
    ["Invalid Keyword/Phrase!"] = "Mot-clé Incorrect/ phrase!",
    ["Keyword/Phrase is already used!"] = "Mot-cle/phrase est déjà utilisé!",
    
    ["Day"] = "Jour",
    ["Week"] = "Semaine",
    ["Month"] = "Mois",
    ["Drag to set default spawn/position for message windows."] = "Faites glisser pour régler par défaut la multitude/position pour les fenêtres de message.",
    ["Up"] = "Haut",
    ["Down"] = "Bas",
    ["Left"] = "Gauche",
    ["Right"] = "Droit",
    ["Ignore"] = "Ignore",
    ["Block"] = "Bloque",
    ["Enable WIM"] = "Activer WIM",
    
    ["Auto Close Friends after:"] = "Ferme automatiquement les ami(e)s après",
    ["Auto Close Non-Friends after:"] = "Ferme automatiquement non amis après",
    
    ["Display"] = "Afficher",
    ["Incoming Messages"] = "Les messages entrants",
    ["Outgoing Messages"] = "Les messages sortants",
    ["System Messages"] = "Messages système",
    ["Error Messages"] = "Messages d'erreur",
    ["Web URLs"] = "Lien Web",
    ["Enable"] = "Active",
    ["Disable"] = "Désactiver",
    ["Enabled"] = "Activé",
    ["Disabled"] = "Désactiver",
    ["Display character information."] = "Affiche les inforamtions du personnage",
    ["Display time stamps"] = "Affichage de l'heure",
    ["This setting limits the\nwindow's minimum height."] = "Ce paramètre limite la hauteur minimale de la \nfenêtre.",
    ["Requires /who querying."] = "Nécessite /qui interroge ",
    ["Enable window fading effects."] = "Active les effets ",
    ["Enable window animations."] = "Activer les animations de la fenêtre.",
    
    ["Display minimap icon."] = "Affiche l'icône sur la minicarte",
    
    ["General"] = "Général",
    ["History"] = "Historique",
    ["Filters"] = "Filtres",
    ["Plugins"] = "Plugins",
    
    ["Auto focus when window is shown."] = "Auto focus lorsque la fenêtre est affichée.",
    ["Preserve focus after sending messages."] = "Préserver le focus après envoi de messages.",
    ["Display tooltips."] = "Afficher les info-bulles.",
    ["Show window when sending a message."] = "Afficher la fenêtre lors de l'envoi d'un message",
    ["Show window when message has been received."] = "Afficher la fenêtre lorsque le message a été reçu.",
    ["Supress messages from default chat frame."] = "Supprimer les messages de discussion par défaut du cadre.",
    ["Play sound when message is received."] = "Jouer un son lorsque le message est reçu.",
    ["Play sound when message is sent."] = "Jouer un son lorsque le message est envoyé.",
    ["Sort alphabetically."] = "Tri par ordre alphabétique.",
    ["Use <Escape> to close windows."] = "Utilisez <Escape> pour fermer les fenêtres.",
    ["Windows will close when opening the world map."] = "La fenêtre se ferme lorsque vous ouvrez la carte du monde.",
    ["Intercept slash commands."] = "Intercepter les commandes slash.",
    ["Ignore arrow keys while typing."] = "",
    ["Requires using <Alt> to navigate text."] = "Nécessite l'utilisation de <Alt> pour naviguer sur le texte",
    ["Display emoticons."] = "Affiche les emoticons.",
    ["Display URLs as item links."] = "Affiche l'URL des objets sous forme de lien",
    ["Display floating item links."] = "Affiche les liens d'objets flottant",
    
    ["Cascade windows."] = "Fenêtres en cascade.",
    ["Direction:"] = "Direction:",
    ["Tabs"] = "Onglets",
    ["Sort tabs by:"] = "Onglets Trier par:",
    ["Alphabetical"] = "Alphabétique",
    ["Recent Activity"] = "Activité récente",
    ["Keep windows on top of your UI."] = "Gardez les fenêtres en haut de votre interface d'utilisateur.",


  -- Class Names --
    ["Druid"] = "Druide",
    ["Hunter"] = "Chasseur",
    ["Mage"] = "Mage",
    ["Paladin"] = "Paladin",
    ["Priest"] = "Prêtre",
    ["Rogue"] = "Voleur",
    ["Shaman"] = "Chaman",
    ["Warlock"] = "Démoniste",
    ["Warrior"] = "Guerrier",
    ["Death Knight"] = "Chevalier de la mort",

    -- Female Class Names --
    ["DruidF"] = "Druidesse",
    ["HunterF"] = "Chasseresse",
    ["MageF"] = "Mage",
    ["PaladinF"] = "Paladin",
    ["PriestF"] = "Prêtresse",
    ["RogueF"] = "Voleuse",
    ["ShamanF"] = "Chamane",
    ["WarlockF"] = "Démoniste",
    ["WarriorF"] = "Guerrière",
    ["Death KnightF"] = "Chevalier de la mort",
    
    ["Game Master"] = "GM",
    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "Basculer WIM 'On' et 'Off'.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "Basculer en débogage 'On' et 'Off'.",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM est en cours d'exécution. Accéder aux options de WIM:",
    
    -- Filters.lua --
    ["Whispers Sent by Addons"] = "Chuchotements envoyés par l'addons",
    ["WhisperSelect Part 1"] = "Chuchotement select partie 1",
    ["Example Spam Blocker"] = "Exemple de spam bloquer",
    ["WhisperSelect Part 2"] = "Chuchotement select partie 2",
    ["Filter Name"] = "Nom du filtre",
    ["Filter By"] = "Filtre par",
    ["Pattern"] = "Style",
    ["User Type"] = "Type d'utilisateur",
    ["Level"] = "Level",
    ["Friends"] = "Ami(e)s",
    ["Guild Members"] = "Membres de guilde",
    ["Party Members"] = "Membres du groupe",
    ["Raid Members"] = "Membres du Raid",
    ["Cross-Realm"] = "Inter-royaumes",
    ["Everyone"] = "Tout le monde",
    ["User must be at least level:"] = "L'utilisateur doit être d'au moins:",
    ["Apply to messages received."] = "S'appliquent aux messages reçus.",
    ["Apply to messages sent."] = "S'appliquent aux messages envoyés.",
    ["Action to Perform:"] = "Action à exécuter:",
    ["Allow"] = "Autoriser",
    ["Ignore"] = "Ignorer",
    ["Blocked"] = "Bloqué",
    ["Save"] = "Sauver",
    ["Cancel"] = "Annuler",
    ["Edit Filter"] = "Modifier le filtre",
    ["Add Filter"] = "Ajouter un filtre",
    
    -- History.lua --
    ["WIM History Button"] = "WIM bouton de l'historique",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Cliquer sur %s le bouton de la fenêtre du message, indiquera que l'historique du chuchotement de l'utilisateur sera gardé",
    ["Click to view message history."] = "Cliquez pour voir l'historique des messages.",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM taille %d |4message: messages, à partir de votre histoire.",
    ["History Viewer"] = "Voir l'historique",
    ["Filters"] = "Filtres",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Etes-vous sûr de vouloir supprimer toute l'historique enregistrée de %s sur %s?",
    ["Search resulted in %d |4message:messages;."] = "Résultat des recherches dans %d |4message:messages;.", 
    ["No results found!"] = "Aucun résultat!",
    ["Search"] = "Recherche",
    ["Show All"] = "Tout voir",
    ["Loading History"] = "Chargement de l'historique",
    ["Chat View"] = "Voir le chat",
    ["Text View"] = "Voir le texte",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM historique peut être accessible à tout moment en tapant:",
    ["WIM History Viewer"] = "WIM voir l'historique",
    ["Display history viewer."] = "Affichage de l'historique du personnage",
    
    -- ldb.lua --
    ["No New Messages"] = "Pas de nouveaux messages",
    
    -- Menu.lua --
    ["Whispers"] = "Chuchotement",
    ["Chat"] = "Chat",
    
    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM Mise à jour disponible!",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "Il existe une version plus récente de WIM disponible en téléchargement. Vous pouvez le télécharger à %s.",
    
    -- ShortcutBar.lua --
    ["Player Location"] = "Lieu du joueur",
    ["Unknown"] = "Inconnu",
    ["Click to update..."] = "Cliquez pour mettre à jour...",
    ["Coordinates"] = "Coordonnées",
    ["Invite to Party"] = "Inviter pour groupage",
    ["Add Friend"] = "Ajouter un ami",
    ["Ignore User"] = "Ignorer cet utilisateur",
    ["Are you sure you want to\nignore %s?"] = "Êtes-vous sûr de vouloir ignorer %s?",
    ["Right-Click for profile links..."] = "Clic droit pour link le Profil...",
    ["Profile Links"] = "Liens du profil",
    
    -- Tutorials.lua --
    ["Display WIM tips"] = "Annonce d'astuces WIM",
    
    -- W2W.lua --
    ["%s is typing..."] = "%s tape ...",
    ["W2W Profile"] = "W2W profil",
    ["Talent Spec"] = "Talent Spec",
    
    -- WhisperEngine.lua --
    ["Whisper Received!"] = "Chuchoetment reçu",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Vous avez reçu un chuchotement qui était caché en raison de votre activité actuelle. Vous pouvez changer la façon de se comportent dans les options de chuchotements WIM en tapant",
    ["Recently Sent Messages"] = "Messages Récemment Envoyés",
    
    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "Vous êtes sur le point d'effacer toutes l'historiques!",
    ["This action will reload your user interface."] = "Cette action se rechargera dans votre interface utilisateur.",
    ["Do you want to continue?"] = "Voulez-vous continuer?",
    ["You are about to restore WIM's filters to it's default settings!"] = "Vous êtes sur le point de rétablir les filtres WIM à ses paramètres par défaut!",
    ["Usage"] = "Traitement",
    ["Clear various WIM data."] = "Nettoyer les données diverses de WIM",
    
    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM Commandes slash",
    ["To see a list of available WIM slash commands type:"] = "Pour voir une liste de commande slash WIM tapez:",
    ["Display available slash commands."] = "Affichage des commandes slash disponibles.",
    ["Reload User Interface."] = "Recharger l'interface utilisateur.",
    
    -- TabHandler.lua --
    ["Manipulating Tabs"] = "",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "Vous pouvez faire <Shift-Click> sur un onglet et faites-la glisser sur sa propre fenêtre.",
    
    
    -- WindowHandler.lua --
    ["Window Resized!"] = "Fenêtre redimensionnée!",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Si vous voulez que toutes les fenêtres doit être de cette taille, vous pouvez définir la taille de la fenêtre par défaut dans les options de Wim's.",
    ["Creating Tab Groups"] = "Création de Groupes d'onglets",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Vous pouvez regrouper deux ou plusieurs fenêtres <Shift-Clicking> ensemble par une fenêtre et en le faisant glisser sur le dessus de l'autre.",
    ["Resizing Windows"] = "Redimensionner les fenêtres",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Vous pouvez redimensionner une fenêtre en maintenant la touche <Maj> et en faisant glisser le coin inférieur droit de la fenêtre.",
    ["Demo Window"] = "Démonstration de fenêtre",
    ["<Shift-Click> to close window."] = "<Shift-Click> Pour fermer la fenêtre.",
    ["Message Window Hidden"] = "Fenêtre de message masquée",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "WIM fenêtre de message a été caché sur l'icon de la Minimap. Si vous souhaitez mettre fin à une conversation, Vous pouvez faire <clique-shift> pour fermer le bouton",
    ["Default"] = "Défaut",
    ["%s is Away From Keyboard: %s"] = "%s est Loin du Clavier : %s",
    ["%s does not wish to be disturbed: %s"] = "%s ne veut pas être dérangé: %s",
    ["Right-Mouse Click!"] = "Clique droit de la souris",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Il pourrait y avoir des outils utiles cachés sous la boîte de message. Le clique droit pour les voir!",
    
    
    -- Options.lua --
    ["Display WIM's options."] = "Affichez les options de WIM.",
    ["Resetting WIM will clear all of your settings!"] = "Réinitialisation de WIM et efface la totalité des paramètres!",
    ["Reset all options to default."] = "Réinitialiser toutes les options par défaut.",
    
    -- CoreOptions --
    ["Created by:"] = "Créé par:",
    ["Special Thanks:"] = "Merci spécial:",
    ["Welcome!"] = "Bienvenue!",
    ["Enable WIM"] = "Activer WIM",
    ["Display Minimap Icon"] = "Affiche l'icon sur la minimap",
    ["<Right-Click> to show unread messages."] = "<Clique-droit> Pour afficher les messages non lus.",
    ["Display Tutorials"] = "Affiche le tutorial",
    ["Reset Tutorials"] = "Efface le tutorial",
    ["Credits"] = "Credits",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Il s'agit d'un long message qui contient à la fois des émoticônes et des URL 8). WIM's l'adresse www.WIMAddon.com.",
    ["Message Formatting"] = "Format d'un message",
    ["Manipulate how WIM displays messages."] = "Comment manipuler WIM et l'affichage des messages.",
    ["Preview"] = "Présenter",
    ["Display Time Stamps"] = "Afficher le temps",
    ["Display Emoticons"] = "Affiche les Emoticons",
    ["Display URLs as Links"] = "Affichez URLs comme les Liens",
    ["Indent long messages."] = "découper les longs messages.",
    ["Window Behavior"] = "Comportement des fenêtres",
    ["You can control how windows behave while you are in different situations."] = "Vous pouvez contrôler la façon dont se comportent les fenêtres lorsque vous êtes dans des situations différentes.",
    ["Intercept Slash Commands"] = "Interception des commandes slash",
    ["Use the same rules for all states."] = "Utilisez les mêmes règles pour tous les Etats.",
    ["Behaviors for state:"] = "Comportements pour l'Etat:",
    ["Pop-Up window when message is sent."] = "Fenêtre pop-up lorsque le message est envoyé.",
    ["Pop-Up window when message is received."] = "Fenêtre pop-up lorsque le message est reçu.",
    ["Auto focus a window when it is shown."] = "Auto focus d'une fenêtre quand elle est montrée.",
    ["Keep focus on window after sending a message."] = "Garder le focus sur la fenêtre après l'envoi d'un message.",
    ["Suppress messages from the default chat frame."] = "Supprimer les messages de la discussion par défaut.",
    ["Window Settings"] = "Réglages de la fenêtre",
    ["Some settings may be limited by certain skins."] = "Quelques cadres peuvent être limités par certain skin.",
    ["Default Width"] = "Largeur par défaut",
    ["Default Height"] = "Hauteur par défaut",
    ["Window Scale"] = "Échelle de la fenêtre",
    ["Window Alpha"] = "Alpha de la Fenêtre",
    ["Set Window Spawn Location"] = "Fenêtre du lieu de multiplication définit",
    ["Up"] = "Haut",
    ["Down"] = "Bas",
    ["Left"] = "Gauche",
    ["Right"] = "Droit",
    ["Cascade overlapping windows."] = "Cascade de fenêtres superposées.",
    ["Ignore arrow keys in message box."] = "Ignorer les touches de direction dans un message.",
    ["Allow <ESC> to hide windows."] = "Allouer <ESC> pour cacher les fenêtres",
    ["Display Settings"] = "Paramètres d'affichage",
    ["Configure general window display settings."] = "Configuration Général des paramètres d'affichage des fenêtres.",
    ["Window Skin:"] = "Skin de la fenêtre",
    ["Version"] = "Version",
    ["Color: System Messages"] = "Couleur : Messages du Système",
    ["Color: Error Messages"] = "Couleur : Messages d'erreur",
    ["Color: URL - Web Addresses"] = "Couleur : URL - Adresses de Web",
    ["Color: History Messages Sent"] = "Couleur: historique des messages envoyés",
    ["Color: History Messages Received"] = "Couleur: historique des messages reçus",
    ["Use colors suggested by skin."] = "Utilisez des couleurs proposé pour le skin",
    ["Enable window fading effects."] = "Activer la fenêtre des effets.",
    ["Enable window animation effects."] = "Activer les effets d'animation de la fenêtre.",
    ["Display item links when hovering over them."] = "Affiche le lien vers les objets lors du survol de la souris.",
    ["Fonts"] = "Polices",
    ["Configure the fonts used in WIM's message windows."] = "Configurez les polices utilisées dans les fenêtres de message Wim's.",
    ["Font Outline"] = "Contour de la police",
    ["Thin"] = "Amincir",
    ["Thick"] = "Gros",
    ["Use font suggested by skin."] = "Utiliser la police suggérée par le skin",
    ["Chat Font Size"] = "Taille du texte",
    ["Configure general display settings when dealing with whispers."] = "Configurer les paramètres d'affichage général lorsqu'il s'agit de chuchotements.",
    ["Color: Messages Sent"] = "Coleur: Messages envoyés",
    ["Color: Messages Received"] = "Coleur: Messages reçus",
    ["Use colors suggested by skin."] = "Utilisez des couleurs proposées par le skin",
    ["Display user class icons and details."] = "Affichez les icônes de classe et les détails",
    ["Requires who lookups."] = "Besoin de recherches qui",
    ["Display Shortcut Bar"] = "Affichez la Barre Rapide",
    ["Allow"] = "Autoriser",
    ["Ignore"] = "Ignore",
    ["Block"] = "Bloquer",
    ["Filtering"] = "Filtrage",
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = "Le filtrage vous permet de contrôler quels messages sont transformés, ainsi que la façon dont ils seront traités WIM",
    ["Enable Filtering"] = "Activer le filtrage",
    ["Protected"] = "Protégées",
    ["Action:"] = "Action:",
    ["Occurrences:"] = "Occurrences :",
    ["Delete Filter"] = "Effacez le Filtre",
    ["History"] = "Historique",
    ["WIM can store conversations to be viewed at a later time."] = "WIM permet de stocker les conversations pour être affichées à une date ultérieure.",
    ["Enable History"] = "Activer l'historique",
    ["Messages"] = "Messages",
    ["Preview history inside message windows."] = "Extrait l'historique à l'intérieur des fenêtres de message.",
    ["Record Whispers"] = "Enregistrement des Chuchotements",
    ["Record Friends"] = "Enregistrement des ami(e)s",
    ["Record Guild"] = "Enregistrement guilde",
    ["Record Everyone"] = "Enregistre tout le monde",
    ["Record Chat"] = "Enregistre le chat",
    ["Maintenance"] = "Maintenance",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "L'enregistrement de l'historique de tous les messages, va devenir trop volumineux et affectera la performance du jeu, il est donc recommandé d'utiliser les options suivantes.",
    ["Save a maximum number of messages per person."] = "Enregistrer un nombre maximal de messages par personne.",
    ["%d |4Week:Weeks;"] = "%d |4semaines: Semaines;",
    ["Automatically delete old messages."] = "Supprimer automatiquement les anciens messages.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM est une fonctionnalité qui permet à des joueurs qui utilisent aussi WIM d'interagir de manière à chuchoter normalement s'ils ne peuvent pas.",
    ["Enable WIM-2-WIM"] = "Activer WIM-2-WIM",
    ["Privacy"] = "Confidentialité",
    ["Restrict the data that is shared."] = "Restreindre les données qui sont partagées.",
    ["Allow others to see me typing."] = "Permettre aux autres de me voir taper",
    ["Allow others to see my location."] = "Permettre aux autres de voir ma position.",
    ["Main"] = "Principal",
    ["General"] = "Général",
    ["User Level"] = "Niveau du joueur",
    ["Windows will also be hidden when frames such as the world map are shown."] = "La fenêtre va également se cacher lorsque les cadres telles que la carte mondiale sera montrés.",
    ["Sounds"] = "Son",
    ["Configure various sound events and how they are triggered."] = "Configurer le son de divers événements et la façon dont ils sont déclenchés.",
    ["Play sound when a whisper is received."] = "Lecture sonore quand un murmure est reçu.",
    ["Play special sound for friends."] = "Lecture sonore spécial pour les amis.",
    ["Play special sound for guild members."] = "Lecture sonore spécial pour les membres de la guilde.",
    ["Play sound when a whisper is sent."] = "Lecture sonore quand un murmure est envoyé.",
    ["Allow others to see my talent spec."] = "Permettre aux autres de voir mes talents.",
    ["Window Strata:"] = "Strates de Fenêtre :",
    ["Unlock from Minimap"] = "Déverrouiller Minimap",
    
-- TabManagement.lua --
    ["Tab Management"] = "Gestion d'onglet",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Gérer automatiquement les fenêtres ouvertes et les places dans des groupes d'onglet appropriés.",
    ["Automatically group whispers."] = "Groupe automatiquement le chuchotement",
    ["Place friends in their own group."] = "Place un(e) ami(e) dans le groupe.",
    ["Place guild members in their own group."] = "Place des membres de la guilde dans le groupe.",
    ["Does not apply to windows already opened."] = "Ne s'applique pas à la fenêtre déjà ouverte.",


    -- Talent Specs --
    ["Affliction"] = "Affliction",
    ["Arcane"] = "Arcane",
    ["Arms"] = "Armes",
    ["Assassination"] = "Assassinat",
    ["Balance"] = "Equilibre",
    ["Beast Mastery"] = "Maîtrise des bêtes",
    ["Blood"] = "Sang",
    ["Combat"] = "Combat",
    ["Demonology"] = "Démonologie",
    ["Destruction"] = "Destruction",
    ["Discipline"] = "Discipline",
    ["Elemental"] = "Elémentaire",
    ["Enhancement"] = "Amélioration",
    ["Feral Combat"] = "Combat farouche",
    ["Fire"] = "Feu",
    ["Frost"] = "Givre",
    ["Fury"] = "Fureur",
    ["Holy"] = "Sacré",
    ["Hybrid"] = "Hybride",
    ["Marksmanship"] = "Précision",
    ["Protection"] = "Protection",
    ["Restoration"] = "Restauration",
    ["Retribution"] = "Vindicte",
    ["Shadow"] = "Ombre",
    ["Subtlety"] = "Finesse",
    ["Survival"] = "Survie",
    ["Unholy"] = "Impie",

-- ChangeLog.lua --
    ["Change Log"] = "Historique des news",
    ["View WIM's change log."] = "Connectez-vous changer la vue Wim's.",
    ["Available For Download!"] = "Disponible en téléchargement!",
    
    -- Filters.lua --
    ["Show Alert"] = "",
    ["WIM has blocked a message from %s."] = "Afficher une alerte",
    ["View Blocked Message"] = "Voir Message bloqué",
    ["Blocked Message"] = "Message bloqué",
    
    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Afficher les messages non lus",
    ["Show All Windows"] = "Afficher tous les Fenêtres",
    ["Hide All Windows"] = "Masquer toutes les fenêtres",
    
    --Emoticons.lua
    ["Also"] = "Également",
    ["More"] = "Plus",
    ["Emoticons"] = "Emoticons",
    
    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat.To disable this feature type"] = "Vos conversations ont été cachés afin de vider votre écran tout en combat. Mettre hors de service ce type de fonction",
    ["Expose"] = "Exposé",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Exposé est inspiré d'une application Mac OS X, fonction qui permet de masquer temporairement toutes les fenêtres, puis les remets à leurs position initiale.",
    ["Auto hide/restore windows during combat."] = "Auto masquer / restaurer les fenêtres pendant le combat.",
    ["Border Size"] = "Taille de la bordure",
    ["Only while in an instance."] = "Seulement dans une instance.",
    ["Show Border"] = "Montre la bordure",
    ["Animation Direction:"] = "Direction de l'animation",
    
    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM gére ce type de chat au sein de ses propre fenêtres de message.",
    ["Show Minimap Alerts"] = "Montre une alerte sur la minimap",
    ["Never pop-up on my screen."] = "Jamais de pop-up sur mon écran.",
    ["Never suppress messages."] = "Jamais supprimer des messages.",
    ["Have WIM monitor this channel."] = "WIM surveille ce canal.",
    ["Never Pop"] = "Jamais de Pop",
    ["Never have this window pop-up on my screen."] = "Jamais voir cette fenêtre pop-up sur mon écran.",
    ["Never Supress"] = "Jamais supprimer",
    ["Never suppress messages from the default chat frame."] = "Jamais supprimer les messages de la discussion par défaut",
    ["Show unread message alert on minimap."] = "Voir la signalisation des messages non lus sur la minicarte.",
    ["No History"] = "Aucun historique",
    ["Do not record history for this channel."] = "Ne pas enregistrer l'historique de ce canal.",
    ["World Chat"] = "Chat serveur",
    ["Custom Chat"] = "Conversation Personnalisée",
    ["Chat"] = "Chat",
    ["Play special sound for %s."] = "Jouez le son spécial pour %s.",
    ["Play sound when a message is received."] = "Jouer un son quand un message est reçu.",
    ["Play sound when a message is sent."] = "Jouer un son quand un message est envoyé.",
    

});