--[[
    Language Localization: koKR
    Translated by: BlueNyx <bluenyx@gmail.com>
]]

WIM.AddLocale("koKR", {
    ["WIM (WoW Instant Messenger)"] = "WIM (와우 메신저)",
    ["_Description"] = "WIM is an addon that brings a familiar feel to communicating through chat in The World of Warcraft. On this screen you will be able to customize WIM to tailor it to your needs. If you have any questions, comments or suggestions please go to http://www.WIMAddon.com.",

    ["_DemoText"] = "현재의 창은 미리 보기 창 모드입니다. 이 창의 위치를 움직여서 정하면 다음에 뜨는 창이 해당 위치부터 보여지게 됩니다. 이 창을 닫는 순간 창의 위치가 저장됩니다.",

    ["_DateFormat"] = "%Y/%m/%d",

    ["Yes"] = "예",
    ["No"] = "아니오",
    ["None"] = "없음",
    ["<Right-Click>"] = "오른쪽 클릭",
    ["<Left-Click>"] = "왼쪽 클릭",
    ["OK"] = "확인",
    ["Cancel"] = "취소",
    ["Unknown"] = "알 수 없음",
    ["Click to update..."] = "클릭 - 위치 정보 갱신",
    ["Usage"] = "사용",
    
    ["state_resting"] = "대도시",
    ["state_combat"] = "전투중",
    ["state_pvp"] = "전장",
    ["state_arena"] = "투기장",
    ["state_party"] = "파티",
    ["state_raid"] = "레이드",
    ["state_other"] = "일반 (기타)",
    
    ["<Shift-Click> to close window."] = "<Shift-Click> 창 닫기",
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "새로운 버전의 WIM이 확인되었습니다!\n가장 최신의 버전을 다운로드 하려면 사이트로 이동하세요:\n\n http://www.wimaddon.com 또는 http://wow.somegate.com",
    
    ["Options"] = "옵션",
    
    ["Icon Position"] = "아이콘 위치",
    ["Font Size"] = "글자 크기",
    ["Window Scale (Percent)"] = "창 크기 (%)",
    ["Transparency (Percent)"] = "창 투명도 (%)",
    ["Window Width"] = "창 넓이",
    ["Window Height"] = "창 높이",
    ["(Limited by shortcut bar)"] = "(단축바에 따른 제약이 있습니다.)",
    ["ERROR"] = "에러",
    ["Invalid Name!"] = "오류: 이름이 정확하지 않습니다.!",
    ["Name is already used!"] = "오류: 이미 사용 중인 이름입니다.!",
    ["Invalid Alias!"] = "오류: 별명이 정확하지 않습니다.!",
    ["Invalid Keyword/Phrase!"] = "오류: 키워드/어구가 정확하지 않습니다.!",
    ["Keyword/Phrase is already used!"] = "오류: 이미 사용 중인 키워드/어구 입니다.!",
    
    ["Day"] = "하루",
    ["Week"] = "일주일",
    ["Month"] = "한 달",
    ["Drag to set default spawn/position for message windows."] = "드래그해서 대화창이 생성될 \n기본 위치를 정하십시오.",
    ["Up"] = "위",
    ["Down"] = "아래",
    ["Left"] = "왼쪽",
    ["Right"] = "오른쪽",
    ["Ignore"] = "무시",
    ["Block"] = "차단",
    ["Enable WIM"] = "WIM 사용",
    
    ["Auto Close Friends after:"] = "친구와의 대화창 자동 종료 :",
    ["Auto Close Non-Friends after:"] = "친구 이외의 대화창 자동 종료 :",
    
    ["Display"] = "대화창 설정",
    ["Incoming Messages"] = "받은 메세지",
    ["Outgoing Messages"] = "보낸 메세지",
    ["System Messages"] = "시스템 메세지",
    ["Error Messages"] = "에러 메세지",
    ["Web URLs"] = "Web URLs",
    ["Enable"] = "켜기",
    ["Disable"] = "끄기",
    ["Enabled"] = "켜기",
    ["Disabled"] = "끄기",
    ["Display character information."] = "캐릭터 정보 보기",
    ["Display time stamps"] = "도착 시간 보기",
    ["This setting limits the\nwindow's minimum height."] = "이 설정은 대화창의 최대 높이에 제한을 줍니다.",
    ["Requires /who querying."] = "/who 질의 포함",
    ["Enable window fading effects."] = "창 투명화 효과 기능",
    ["Enable window animations."] = "창 애니메이션 기능",
    
    ["Display minimap icon."] = "미니맵 아이콘 표시",
    
    ["General"] = "일반",
    ["History"] = "대화기록",
    ["Filters"] = "필터",
    ["Plugins"] = "플러그인",
    
    ["Auto focus when window is shown."] = "대화창 팝업 시 자동으로 커서를 입력창에 위치",
    ["Preserve focus after sending messages."] = "메시지 전송 후 입력창에 커서 유지",
    ["Display tooltips."] = "툴팁을 표시합니다.",
    ["Show window when sending a message."] = "새 귓속말을 받을 때 대화창을 표시합니다.",
    ["Show window when message has been received."] = "답변을 받을 때 대화창을 표시합니다.",
    ["Supress messages from default chat frame."] = "기본 채팅창의 대화 메세지를 막습니다.",
    ["Play sound when message is received."] = "메시지 도착 시 효과음 재생",
    ["Play sound when message is sent."] = "메시지 보낼 때 효과음 재생",
    ["Sort alphabetically."] = "대화 목록을 가나다순으로 정렬",
    ["Use <Escape> to close windows."] = "ESC 키로 대화창 종료",
    ["Windows will close when opening the world map."] = "지도를 열어 두고 ESC 키 사용 시 대화창도 함께 종료됩니다.",
    ["Intercept slash commands."] = "귓속말 슬래시 명령어 사용 시 대화창 팝업",
    ["Ignore arrow keys while typing."] = "타이핑중 화살표키 사용을 무시합니다.",
    ["Requires using <Alt> to navigate text."] = "<Alt>키를 사용하여 텍스트 이동",
    ["Display emoticons."] = "이모티콘을 표시합니다.",
    ["Display URLs as item links."] = "웹 링크를 표시합니다.",
    ["Display floating item links."] = "아이템 링크를 표시합니다.",
    
    ["Cascade windows."] = "대화창 계단식 배열 사용",
    ["Direction:"] = "방향:",
    ["Tabs"] = "탭",
    ["Sort tabs by:"] = "탭 정렬 방식 :",
    ["Alphabetical"] = "가나다순",
    ["Recent Activity"] = "최근 대화 순",
    ["Keep windows on top of your UI."] = "대화창을 항상 위에 표시",
    
    -- Class Names --
    ["Druid"] = "드루이드",
    ["Hunter"] = "사냥꾼",
    ["Mage"] = "마법사",
    ["Paladin"] = "성기사",
    ["Priest"] = "사제",
    ["Rogue"] = "도적",
    ["Shaman"] = "주술사",
    ["Warlock"] = "흑마법사",
    ["Warrior"] = "전사",
    ["Death Knight"] = "죽음의 기사",
    
    -- Female Class Names --
    ["DruidF"] = "드루이드",
    ["HunterF"] = "사냥꾼",
    ["MageF"] = "마법사",
    ["PaladinF"] = "성기사",
    ["PriestF"] = "사제",
    ["RogueF"] = "도적",
    ["ShamanF"] = "주술사",
    ["WarlockF"] = "흑마법사",
    ["WarriorF"] = "전사",
    ["Death KnightF"] = "죽음의 기사",
    
    ["Game Master"] = "GM",
    
    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "WIM을 켜고 끕니다.",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "WIM 디버그모드를 켜고 끕니다.",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "현재 WIM이 사용중입니다. 사용할 수 있는 WIM의 옵션 :",
    
    -- Filters.lua --
    ["Whispers Sent by Addons"] = "애드온을 통해 귓속말",
    ["WhisperSelect Part 1"] = "귓속말 대상자 선택 파트 1",
    ["Example Spam Blocker"] = "스팸 차단 예제",
    ["WhisperSelect Part 2"] = "귓속말 대상자 선택 파트 2",
    ["Filter Name"] = "조건 이름",
    ["Filter By"] = "조건 만든이",
    ["Pattern"] = "패턴(반복적 형식)",
    ["User Type"] = "유저 타입",
    ["Level"] = "레벨",
    ["Friends"] = "친구",
    ["Guild Members"] = "길드 멤버",
    ["Party Members"] = "파티 멤버",
    ["Raid Members"] = "공대 멤버",
    ["Cross-Realm"] = "다른 서버",
    ["Everyone"] = "모두",
    ["User must be at least level:"] = "유저의 최소 레벨",
    ["Apply to messages received."] = "메세지 받기 허용",
    ["Apply to messages sent."] = "메세지 보내기 허용",
    ["Action to Perform:"] = "Action to Perform:",
    ["Allow"] = "허용",
    ["Ignore"] = "무시",
    ["Blocked"] = "차단",
    ["Save"] = "저장",
    ["Cancel"] = "취소",
    ["Edit Filter"] = "조건 수정",
    ["Add Filter"] = "조건 추가",
    
    -- History.lua --
    ["WIM History Button"] = "WIM 대화기록 버튼",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Clicking the %s button on the message window will show that user's history in WIM's History Viewer.",
    ["Click to view message history."] = "클릭하면 대화기록을 볼 수 있습니다.",
    ["WIM pruned %d |4message:messages; from your history."] = "당신의 대화 기록에서 WIM %d |4message:messages; 제거할 수 있습니다.",
    ["History Viewer"] = "대화기록 보기창",
    ["Filters"] = "조건",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "Are you sure you want to delete all history saved for %s on %s?",
    ["Search resulted in %d |4message:messages;."] = "검색 결과가 %d |4개 있습니다.",
    ["No results found!"] = "검색 결과가 없습니다.!",
    ["Search"] = "찾기",
    ["Show All"] = "모두 보기",
    ["Loading History"] = "대화기록 불러오기",
    ["Chat View"] = "대화 보기",
    ["Text View"] = "글 보기",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM History Viewer can be accessed any time by typing:",
    ["WIM History Viewer"] = "WIM 대화기록 보기창",
    ["Display history viewer."] = "대화기록 보기창 보기",
    
    -- ldb.lua --
    ["No New Messages"] = "새로운 메세지가 없습니다.",
    
    -- Menu.lua --
    ["Whispers"] = "귓속말",
    ["Chat"] = "대화",
    
    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM 업데이트가 있습니다.",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "There is a newer version of WIM available for download. You can download it at %s.",
    
    -- ShortcutBar.lua --
    ["Player Location"] = "현재 위치",
    ["Unknown"] = "알 수 없음",
    ["Click to update..."] = "클릭 - 위치 정보 갱신",
    ["Coordinates"] = "Coordinates",
    ["Invite to Party"] = "파티 초대",
    ["Add Friend"] = "친구 추가",
    ["Ignore User"] = "차단 설정",
    ["Are you sure you want to\nignore %s?"] = "당신은 %s 의 차단을 원합니까?",
    
    -- Tutorials.lua --
    ["Display WIM tips"] = "WIM 팁 보여주기",
    
    -- W2W.lua --
    ["%s is typing..."] = "%s님이 타이핑 중...",
    ["W2W Profile"] = "W2W(WIM to WIM) 프로필",
    ["Talent Spec"] = "특성 스팩",	
    
    -- WhisperEngine.lua --
    ["Whisper Received!"] = "귓속말 받기",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing",
    
    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "당신은 모든 WIM 대화기록을 삭제합니다!",
    ["This action will reload your user interface."] = "이 선택은 유저 인터페이스를 재시작 한 후에 실행됩니다.",
    ["Do you want to continue?"] = "계속 하시겠습니까?",
    ["You are about to restore WIM's filters to it's default settings!"] = "WIM 필터설정을 기본값으로 돌립니다!",
    ["Usage"] = "사용",
    ["Clear various WIM data."] = "WIM 데이타 삭제",
    
    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM /명령어",
    ["To see a list of available WIM slash commands type:"] = "To see a list of available WIM slash commands type:",
    ["Display available slash commands."] = "사용 가능한 명령어 보기",
    ["Reload User Interface."] = "유저 인터페이스 재시작",
    
    -- TabHandler.lua --
    ["Manipulating Tabs"] = "Manipulating Tabs",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "You can <Shift-Click> a tab and drag it out into it's own window.",
    
    -- WindowHandler.lua --
    ["Window Resized!"] = "창 크기 수정!",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "If you want all windows to be this size, you can set the default window size within WIM's options.",
    ["Creating Tab Groups"] = "Creating Tab Groups",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another.",
    ["Resizing Windows"] = "윈도우 크기 재설정",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "You can resize a window by holding <Shift> and dragging the bottom right corner of the window.",
    ["Demo Window"] = "미리보기 창",
    ["<Shift-Click> to close window."] = "<Shift-Click> 으로 창 닫기",
    ["Message Window Hidden"] = "메세지 창 숨기기",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button.",
    ["Default"] = "기본값",
    ["%s is Away From Keyboard: %s"] = "%s는 현재 화면 앞에 존재하지 않습니다: %s",
    ["%s does not wish to be disturbed: %s"] = "%s does not wish to be disturbed: %s",
    
    -- Options.lua --
    ["Display WIM's options."] = "WIM 옵션 보기",
    ["Resetting WIM will clear all of your settings!"] = "당신의 WIM 모든설정을 삭제합니다.",
    ["Reset all options to default."] = "초기화",
    
    -- CoreOptions --
    ["Created by:"] = "제작자:",
    ["Special Thanks:"] = "고마운분:",
    ["Welcome!"] = "환영합니다!",
    ["Enable WIM"] = "WIM 사용",
    ["Display Minimap Icon"] = "미니맵 아이콘 사용",
    ["<Right-Click> to show unread messages."] = "<Right-Click>으로 읽지 않은 메세지를 표시",
    ["Display Tutorials"] = "튜토리얼 보기",
    ["Reset Tutorials"] = "튜토리얼 초기화",
    ["Credits"] = "Credits",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com.",
    ["Message Formatting"] = "메세지 형식",
    ["Manipulate how WIM displays messages."] = "Manipulate how WIM displays messages.",
    ["Preview"] = "미리보기",
    ["Display Time Stamps"] = "메세지 시간보기",
    ["Display Emoticons"] = "이모티콘 보여주기",
    ["Display URLs as Links"] = "URL Link 보여주기",
    ["Indent long messages."] = "긴 메세지에 대한 들여쓰기 사용",
    ["Window Behavior"] = "창의 동작",
    ["You can control how windows behave while you are in different situations."] = "You can control how windows behave while you are in different situations.",
    ["Intercept Slash Commands"] = "/명령어 차단",
    ["Use the same rules for all states."] = "모든 상황에 대해 동일한 규칙을 사용.",
    ["Behaviors for state:"] = "Behaviors for state:",
    ["Pop-Up window when message is sent."] = "메세지를 보낼 때 창 띄우기",
    ["Pop-Up window when message is received."] = "메세지를 받을 때 창 띄우기",
    ["Auto focus a window when it is shown."] = "창이 뜨면 자동으로 입력 커서 이동",
    ["Keep focus on window after sending a message."] = "메세지를 보낸 후 창에 커서 유지",
    ["Suppress messages from the default chat frame."] = "Suppress messages from the default chat frame.",
    ["Window Settings"] = "창 설정",
    ["Some settings may be limited by certain skins."] = "Some settings may be limited by certain skins.",
    ["Default Width"] = "기본 넓이",
    ["Default Height"] = "기본 높이",
    ["Window Scale"] = "창 크기",
    ["Window Alpha"] = "창 투명도",
    ["Set Window Spawn Location"] = "창이 뜨는 위치 설정",
    ["Up"] = "위",
    ["Down"] = "아래",
    ["Left"] = "왼쪽",
    ["Right"] = "오른쪽",
    ["Cascade overlapping windows."] = "Cascade overlapping windows.",
    ["Ignore arrow keys in message box."] = "메세지 박스 안에서의 화살표 키 무시",
    ["Allow <ESC> to hide windows."] = "창 숨기기를 <ESC> 키로 사용",
    ["Display Settings"] = "설정 보기",
    ["Configure general window display settings."] = "일반적인 창 보기 셋팅 설정.",
    ["Window Skin:"] = "창 스킨",
    ["Version"] = "버전",
    ["Color: System Messages"] = "컬러: 시스템 메세지",
    ["Color: Error Messages"] = "컬러: 에러 메세지",
    ["Color: URL - Web Addresses"] = "컬러: URL - 웹 주소",
    ["Color: History Messages Sent"] = "컬러: 예전에 보냈던 메세지",
    ["Color: History Messages Received"] = "컬러: 예전에 받았던 메세지",
    ["Use colors suggested by skin."] = "스킨에서 제공하는 컬러 사용",
    ["Enable window fading effects."] = "창 페이딩 이펙트 사용",
    ["Enable window animation effects."] = "창 에니메이션 이펙트 사용",
    ["Display item links when hovering over them."] = "Display item links when hovering over them.",
    ["Fonts"] = "폰트",
    ["Configure the fonts used in WIM's message windows."] = "WIM 메세지 창의 폰트 구성",
    ["Font Outline"] = "폰트 아웃라인",
    ["Thin"] = "얇게",
    ["Thick"] = "굵게",
    ["Use font suggested by skin."] = "스킨에서 제안하는 폰드 사용",
    ["Chat Font Size"] = "채팅 폰트 사이즈",
    ["Configure general display settings when dealing with whispers."] = "Configure general display settings when dealing with whispers.",
    ["Color: Messages Sent"] = "컬러: 보낸 메세지",
    ["Color: Messages Received"] = "컬러: 받은 메세지",
    ["Use colors suggested by skin."] = "스킨에서 제안하는 컬러 사용",
    ["Display user class icons and details."] = "플레이어 직업 아이콘 및 기본정보 보기",
    ["Requires who lookups."] = "누구 보기 포함.",
    ["Display Shortcut Bar"] = "단축바 표시",
    ["Allow"] = "허용",
    ["Ignore"] = "무시",
    ["Block"] = "차단",
    ["Filtering"] = "필터링",
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = "Filtering allows you to control which messages are handled as well as how they are handlef by WIM.",
    ["Enable Filtering"] = "필터링 허용",
    ["Protected"] = "보호",
    ["Action:"] = "실행:",
    ["Occurrences:"] = "대상:",
    ["Delete Filter"] = "필터 삭제",
    ["History"] = "대화 기록",
    ["WIM can store conversations to be viewed at a later time."] = "WIM can store conversations to be viewed at a later time.",
    ["Enable History"] = "대화기록 허용",
    ["Messages"] = "메세지",
    ["Preview history inside message windows."] = "메세지 창에 대화기록 미리 보기",
    ["Record Whispers"] = "귓속말 대상자 기록",
    ["Record Friends"] = "친구목록 대상자 기록",
    ["Record Guild"] = "길드 대상자 기록",
    ["Record Everyone"] = "모든 대상자 기록",
    ["Record Chat"] = "대화 기록",
    ["Maintenance"] = "관리하기",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options.",
    ["Save a maximum number of messages per person."] = "유저당 최대 저장 메세지 갯수",
    ["%d |4Week:Weeks;"] = "%d |4Week:Weeks;",
    ["Automatically delete old messages."] = "오래된 메세지를 자동으로 지웁니다.",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not.",
    ["Enable WIM-2-WIM"] = "WIM 사용자간 대화 켜기",
    ["Privacy"] = "개인 정보 보호 정책",
    ["Restrict the data that is shared."] = "Restrict the data that is shared.",
    ["Allow others to see me typing."] = "타 유저가 나의 입력 상황을 볼 수 있도록 합니다.",
    ["Allow others to see my location."] = "타 유저가 내 현재 위치를 볼 수 있도록 합니다.",
    ["Main"] = "메인",
    ["General"] = "일반",
    ["User Level"] = "플레이어 레벨",
    ["Windows will also be hidden when frames such as the world map are shown."] = "Windows will also be hidden when frames such as the world map are shown.",
    ["Sounds"] = "사운드",
    ["Configure various sound events and how they are triggered."] = "Configure various sound events and how they are triggered.",
    ["Play sound when a whisper is received."] = "메시지 도착 시 효과음 재생",
    ["Play special sound for friends."] = "친구의 메세지가 도착할 경우 효과음 재생",
    ["Play special sound for guild members."] = "길드원의 메세지가 도착할 경우 효과음 재생",
    ["Play sound when a whisper is sent."] = "메시지 보낼 때 효과음 재생",
    ["Allow others to see my talent spec."] = "자신의 특성을 볼 수 있도록 허용.",	
    ["Window Strata:"] = "윈도우 층레벨",
    ["Unlock from Minimap"] = "미니맵 위치 잠금 풀기",    
    
    -- TabManagement.lua --
    ["Tab Management"] = "탭 관리",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "Automatically manage your open windows and place them into appropriate tab groups.",
    ["Automatically group whispers."] = "Automatically group whispers.",
    ["Place friends in their own group."] = "Place friends in their own group.",
    ["Place guild members in their own group."] = "Place guild members in their own group.",
    ["Does not apply to windows already opened."] = "Does not apply to windows already opened.",
    
	   -- Talent Specs --
    ["Affliction"] = "고통",
    ["Arcane"] = "비전",
    ["Arms"] = "무기",
    ["Assassination"] = "암살",
    ["Balance"] = "조화",
    ["Beast Mastery"] = true,
    ["Blood"] = true,
    ["Combat"] = true,
    ["Demonology"] = "악마",
    ["Destruction"] = true,
    ["Discipline"] = true,
    ["Elemental"] = "정기",
    ["Enhancement"] = "고양",
    ["Feral Combat"] = "야성",
    ["Fire"] = true,
    ["Frost"] = true,
    ["Fury"] = true,
    ["Holy"] = "신성",
    ["Hybrid"] = "하이브리드",
    ["Marksmanship"] = true,
    ["Protection"] = "보호",
    ["Restoration"] = "복원",
    ["Retribution"] = true,
    ["Shadow"] = true,
    ["Subtlety"] = true,
    ["Survival"] = true,
    ["Unholy"] = "부정",
    
    -- ChangeLog.lua --
    ["Change Log"] = "바뀐 부분",
    ["View WIM's change log."] = "WIM 바뀐 부분 보기",
    
    -- Filters.lua --
    ["Show Alert"] = "경고 보기",
    ["WIM has blocked a message from %s."] = "%s 의 메세지를 WIM이 차단하였습니다.",
    ["View Blocked Message"] = "차단한 메세지 보기",
    ["Blocked Message"] = "차단한 메세지",
});