--[[
    Language Localization: ruRU
    Translated by: StingerSoft <stingersoft@iti.lt>
]]

WIM.AddLocale("ruRU", {
	["WIM (WoW Instant Messenger)"] = "WIM (WoW Instant Messenger)",
	["_Description"] = "WIM - модификация, которая принесет Вам знакомое чувство удобства при общении в Мире Warcraft. На данном экране Вы сможете настроить WIM по своему вкусу. Если у Вас есть какие-нибудь вопросы, комментарии или предложения, пожалуйста обратитесь на сайт разработчка http://www. WIMAddon.com (английский).",

	["_DemoText"] = "Это демонстрационное окно! Разместите данное окно на Вашем экране там, где Вы хотели бы, чтобы появлялось окно WIM по умолчанию. После того, как Вы разместите данное окно в нужное место, закройте его и настройки будут сохранены автоматически.",

	["_DateFormat"] = "%m/%d/%Y",

	["Yes"] = "Да",
	["No"] = "Нет",
	["None"] = "Нету",
	["<Right-Click>"] = "<Правый-Клик>",
	["<Left-Click>"] = "<Левый-Клик>",
	["OK"] = "OK",
	["Cancel"] = "Отмена",
	["Unknown"] = "Неизвестно",
	["Click to update..."] = "Кликните для обновления...",
	["Usage"] = "Используется",
    
	["state_resting"] = "Отдыхает",
	["state_combat"] = "В бою",
	["state_pvp"] = "ПВП",
	["state_arena"] = "На арене",
	["state_party"] = "В групповом инстансе",
	["state_raid"] = "В рейдовом инстансе",
	["state_other"] = "Обычный (Другое)",
    
	["<Shift-Click> to close window."] = "<Shift-Клик> для закрытия окна.",
    
	["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "Доступна новая версия WIM!\nВы можете скачать её с сайта:\n\n http://www.wimaddon.com",
    
	["Options"] = "Настройки",
    
	["Icon Position"] = "Позиция иконки",
	["Font Size"] = "Размер шрифта",
	["Window Scale (Percent)"] = "Масштаб окна (процент)",
	["Transparency (Percent)"] = "Прозрачность (процент)",
	["Window Width"] = "Ширина окна",
	["Window Height"] = "Высота окна",
	["(Limited by shortcut bar)"] = "(ограничено панелью ярлыков)",
	["ERROR"] = "ОШИБКА",
	["Invalid Name!"] = "Неверное имя!",
	["Name is already used!"] = "Имя уже существует!",
	["Invalid Alias!"] = "Неверный псевдоним!",
	["Invalid Keyword/Phrase!"] = "Неверное ключевое слово/фраза!",
	["Keyword/Phrase is already used!"] = "Ключевое слово/фраза уже используются!",
    
	["Day"] = "День",
	["Week"] = "Неделя",
	["Month"] = "Месяц",
	["Drag to set default spawn/position for message windows."] = "Переместите для установки позиции\nокна сообщения по умолчанию.",
	["Up"] = "Вверх",
	["Down"] = "Вниз",
	["Left"] = "Влево",
	["Right"] = "Вправо",
	["Ignore"] = "Игнорировать",
	["Block"] = "Блокировать",
	["Enable WIM"] = "Включить WIM",
    
	["Auto Close Friends after:"] = "Авто закрытие друзей после:",
	["Auto Close Non-Friends after:"] = "Авто закрытие остальных после:",
    
	["Display"] = "Отображение",
	["Incoming Messages"] = "Входящий шепот",
	["Outgoing Messages"] = "Исходящий шепот",
	["System Messages"] = "Системные сообщения",
	["Error Messages"] = "Сообщения об ошибках",
	["Web URLs"] = "ВЕБ Ссылки",
	["Enable"] = "Включить",
	["Disable"] = "Выключить",
	["Enabled"] = "Включен",
	["Disabled"] = "Выключен",
	["Display character information."] = "Отображать информацию о персонаже.",
	["Display time stamps"] = "Отображать время",
	["This setting limits the\nwindow's minimum height."] = "Данная настройка ограничит\nминимальную высоту окна.",
	["Requires /who querying."] = "Требуется запрос /who.",
	["Enable window fading effects."] = "Включить затухание.",
	["Enable window animations."] = "Включить анимацию.",
    
	["Display minimap icon."] = "Отображать иконку у мини-карты.",
	
	["General"] = "Основное",
	["History"] = "История",
	["Filters"] = "Фильтры",
	["Plugins"] = "Плагины",
	
	["Auto focus when window is shown."] = "Авто фокус окна при открытии.",
	["Preserve focus after sending messages."] = "Сохранять фокус после отправки сообщения.",
	["Display tooltips."] = "Отображать подсказки.",
	["Show window when sending a message."] = "Отображать окно при отправке сообщения.",
	["Show window when message has been received."] = "Отображать окно при получении сообщения.",
	["Supress messages from default chat frame."] = "Вырезать шепот из стандартного окна чата.",
	["Play sound when message is received."] = "Издавать звук при полученном сообщении.",
	["Play sound when message is sent."] = "Издавать звук при отправке сообщении.",
	["Sort alphabetically."] = "Сортировать по алфавиту.",
	["Use <Escape> to close windows."] = "Использовать 'Escape' для закрытия окна.",
	["Windows will close when opening the world map."] = "Окно будет закрываться при открытии карты мира.",
	["Intercept slash commands."] = "Перехватывать слэш команды.",
	["Ignore arrow keys while typing."] = "Игнорировать клавиши курсора при наборе сообщения.",
	["Requires using <Alt> to navigate text."] = "Для навигации по тексту нужно использовать <Alt>.",
	["Display emoticons."] = "Отображать эмоции.",
	["Display URLs as Links"] = "Отображать URL-адрес как ссылку.",
	["Display floating item links."] = "Отображать ссылки на предмет.",

	["Cascade windows."] = "Каскад окон",
	["Direction:"] = "Направление",
	["Tabs"] = "Закладки",
	["Sort tabs by:"] = "Сортировка закладок:",
	["Alphabetical"] = "По алфавиту",
	["Recent Activity"] = "По активности",
	["Keep windows on top of your UI."] = "Сохранять окно поверх вашего UI.",
	
	["Enable/Disable addon messages."] = "Включение/отключения сообщений модификаций.",
    
    -- Class Names --
	["Druid"] = "Друид",
	["Hunter"] = "Охотник",
	["Mage"] = "Маг",
	["Paladin"] = "Паладин",
	["Priest"] = "Жрец",
	["Rogue"] = "Разбойник",
	["Shaman"] = "Шаман",
	["Warlock"] = "Чернокнижник",
	["Warrior"] = "Воин",
	["Death Knight"] = "Рыцарь cмерти",
    
    -- Female Class Names --
	["DruidF"] = "Друид",
	["HunterF"] = "Охотница",
	["MageF"] = "Маг",
	["PaladinF"] = "Паладин",
	["PriestF"] = "Жрица",
	["RogueF"] = "Разбойница",
	["ShamanF"] = "Шаманка",
	["WarlockF"] = "Чернокнижница",
	["WarriorF"] = "Воин",
	["Death KnightF"] = "Рыцарь cмерти",
    
	["Game Master"] = "ГМ",
	
	-- WIM.lua --
	["Toggle WIM 'On' and 'Off'."] = "Вкл/Выкл WIM",
	["Toggle Debugging Mode 'On' and 'Off'."] = "Вкл/Выкл режим отладки",
	["WIM is currently running. To access WIM's wide array of options type:"] = "WIM в настоящее время уже запущен. Для открытия настроек введите",
    
    -- Filters.lua --
	["Whispers Sent by Addons"] = "Шопот высылаемый аддонами",
	["WhisperSelect Part 1"] = "WhisperSelect Part 1",
	["Example Spam Blocker"] = "Example Spam Blocker",
	["WhisperSelect Part 2"] = "WhisperSelect Part 2",
	["Filter Name"] = "Название",
	["Filter By"] = "Фильтровать по",
	["Pattern"] = "Пример",
	["User Type"] = "Тип игрока",
	["Level"] = "Уровень",
	["Friends"] = "Друзья",
	["Guild Members"] = "Участники гильдии",
	["Party Members"] = "Участники группы",
	["Raid Members"] = "Участники рейда",
	["Cross-Realm"] = "Cross-Realm",
	["Everyone"] = "Все",
	["User must be at least level:"] = "",
	["Apply to messages sent."] = "К исходящим сообщениям",
	["Apply to messages received."] = "К входящим сообщениям",
	["Action to Perform:"] = "Выполняемое действие:",
	["Allow"] = "Разрешить",
	["Ignore"] = "Игнорировать",
	["Blocked"] = "Блокировать",
	["Save"] = "Сохранить",
	["Cancel"] = "Отмена",
	["Edit Filter"] = "Править фильтр",
	["Add Filter"] = "Добавить фильтр",
    
    -- History.lua --
	["WIM History Button"] = "Кнопка истории",
	["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "Кликните по %s кнопке в окне сообщения для отображения истории переписки с данным персонажем в просмотре истории.",
	["Click to view message history."] = "Нажмите для просмотра истории.",
	["WIM pruned %d |4message:messages; from your history."] = "WIM удалил %d |4сообщение:сообщения:сообщений; из вашей истории.",
	["History Viewer"] = "Просмотр истории",
	["Filters"] = "Фильтры",
	["Are you sure you want to delete all history saved for %s on %s?"] = "Вы действительно хотите удалить всю сохранённую историю %s на %s?",
	["Search resulted in %d |4message:messages;."] = "Результат поиска %d |4сообщение:сообщения:сообщений;.",
	["No results found!"] = "Ничего не найдено!",
	["Search"] = "Поиск",
	["Show All"] = "Показать всё",
	["Loading History"] = "Загрузка истории",
	["Chat View"] = "Вид чата",
	["Text View"] = "Вид текста",
	["WIM History Viewer can be accessed any time by typing:"] = "Доступ к просмотру истории можете получить введя команду:",
	["WIM History Viewer"] = "WIM просмотр истории",
	["Display history viewer."] = "Показывать просмотр истории",
    
    -- ldb.lua --
	["No New Messages"] = "Пусто",
    
    -- Menu.lua --
	["Whispers"] = "Сообщения",
	["Chat"] = "Чат",
    
    -- Negotiate.lua --
	["WIM Update Available!"] = "Доступно обновление WIMа!",
	["There is a newer version of WIM available for download. You can download it at %s."] = "Новая версия WIMа доступна для скачивания. Вы её можете скачать с %s.",
    
    -- ShortcutBar.lua --
	["Player Location"] = "Местонахождение персонажа",
	["Unknown"] = "Неизвестно",
	["Click to update..."] = "Кликните для обновления...",
	["Coordinates"] = "Координаты персонажа",
	["Invite to Party"] = "Пригласить в группу",
	["Add Friend"] = "Добавить в друзья",
	["Ignore User"] = "Игнорировать персонажа",
	["Are you sure you want to\nignore %s?"] = "Вы уверены что вы хотите добавить\nперсонажа %s в черный список?",
    ["Right-Click for profile links..."] = "[Правый-Клик] - ссылка на профиль...",
    ["Profile Links"] = "Ссылка на профиль",
    
    -- Tutorials.lua --
	["Display WIM tips"] = "Отображать подсказки WIMа",
    
    -- W2W.lua --
	["%s is typing..."] = "%s печатает..",
	["W2W Profile"] = "Профиль W2W",
    ["Talent Spec"] = "Таланты",
    
    -- WhisperEngine.lua --
	["Whisper Received!"] = "Входящее сообщение!",
	["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "Вы получили шепот, который был скрыт за счет текущей деятельности. Вы можете изменить параметры поведения шепота в WIMе, набрав",
	["Recently Sent Messages"] = "Недавно отосланные сообщения",
    
    -- Clear.lua --
	["You are about to clear all of WIM's history!"] = "Вы собираетесь удалить всю историю WIMа!",
	["This action will reload your user interface."] = "Данное действие перезагрузит ваш интерфейс.",
	["Do you want to continue?"] = "Вы хотите продолжить?",
	["You are about to restore WIM's filters to it's default settings!"] = "Вы собираетесь восстановить настройки фильтров WIMа на настройки по умолчанию!",
	["Usage"] = "Использование",
	["Clear various WIM data."] = "Очистка различных данных WIMа.",
    
    -- SlashHandler.lua --
	["WIM Slash Commands"] = "WIM слеш команды",
	["To see a list of available WIM slash commands type:"] = "Для просмотра списка доступных команд введите:",
	["Display available slash commands."] = "Отображать доступные слеш команды",
	["Reload User Interface."] = "Перезагрузить интерфейс",
    
    -- TabHandler.lua --
	["Manipulating Tabs"] = "Управление закладками",
	["You can <Shift-Click> a tab and drag it out into it's own window."] = "Вы можете нажать <Shift-Клик> на закладку и вытащить её в отдельное окно.",
    
    -- WindowHandler.lua --
	["Window Resized!"] = "Изменён размер окна!",
	["If you want all windows to be this size, you can set the default window size within WIM's options."] = "Если вы хотите чтобы все окна имели данный размер, вы можете установить размер по умолчанию в настройках WIM'а.",
	["Creating Tab Groups"] = "Создание групп закладок",
	["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "Вы можете группировать окна воедино нажав <Shift-Клик> по окну и натаскивая его один на другого.",
	["Resizing Windows"] = "Изменение размера",
	["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "Вы можете изменять размер окна удерживая <Shift> перемещать нижний правый угол окна.",
	["Demo Window"] = "Демо окно",
	["<Shift-Click> to close window."] = "<Shift-Клик> для закрытия окна.",
	["Message Window Hidden"] = "Окно сообщений - скрыто",
	["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = "Окно сообщений WIM'а будет скрыто в иконку WIM'а у мини карты. Если вы хотите закончить беседу, вы должны нажать <Shift-Клик> для закрытия окна.",
	["Default"] = "По умолчанию",
	["%s is Away From Keyboard: %s"] = "%s отсутствует: %s",
	["%s does not wish to be disturbed: %s"] = "%s в режиме \"не беспокоить\": %s",
	["Right-Mouse Click!"] = "Кликните правой кнопкой мыши!",
	["There might be useful tools hidden under the message box. Right-Click to see them!"] = "Полезные инструменты могут быть скрыты под окном. Кликните правой кнопкой мыши чтобы увидеть их!",
    
    
    -- Options.lua --
	["Display WIM's options."] = "Отображает настройки WIMа",
	["Resetting WIM will clear all of your settings!"] = "Сброс WIMа обнулит все ваши настройки!",
	["Reset all options to default."] = "Сброс всех настроек на стандартные значения.",
    
    -- CoreOptions --
	["Created by:"] = "Создатель:",
	["Special Thanks:"] = "Отдельно спасибо:",
	["Welcome!"] = "Добро пожаловать!",
	["Enable WIM"] = "Включить WIM",
	["Display Minimap Icon"] = "Отображать иконку у мини-карты",
	["<Right-Click> to show unread messages."] = "<Правый-Клик> открывает непрочитанные сообщения.",
	["Display Tutorials"] = "Показывать руководство",
	["Reset Tutorials"] = "Сброс руководства",
	["Credits"] = "Титры",
	["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "Это длинное сообщение, которое содержит и смайлики и адреса/ссылки 8). Домашняя страничка WIM'а: www.WIMAddon.com.",
	["Message Formatting"] = "формат сообщения",
	["Manipulate how WIM displays messages."] = "Управление отображением сообщений WIMом",
	["Preview"] = "Пред просмотр",
	["Display Time Stamps"] = "Отображать время",
	["Display Emoticons"] = "Отображать эмоции",
	["Display URLs as Links"] = "Отображать URL-адрес как ссылку",
	["Indent long messages."] = "Делать отступ в длинных сообщениях",
	["Window Behavior"] = "Поведение окна",
	["You can control how windows behave while you are in different situations."] = "Вы можете настроить поведения окна в различных ситуациях.",
	["Intercept Slash Commands"] = "Перехватывать слеш команды",
	["Use the same rules for all states."] = "Использовать одинаковые правила для всех состояний",
	["Behaviors for state:"] = "Поведение для:",
	["Pop-Up window when message is sent."] = "Всплывание окна при отсылке сообщения.",
	["Pop-Up window when message is received."] = "Всплывание окна при получении сообщения.",
	["Auto focus a window when it is shown."] = "Авто-фокус окна при его появлении.",
	["Keep focus on window after sending a message."] = "Сохранить фокус на окне после отправки сообщения.",
	["Suppress messages from the default chat frame."] = "Подавлять сообщения в стандартном окне чата.",
	["Window Settings"] = "Настройки окна",
	["Some settings may be limited by certain skins."] = "Некоторые настройку будут ограничены в определённых шкурках.",
	["Default Width"] = "Стандартная ширина",
	["Default Height"] = "Стандартная высота",
	["Window Scale"] = "Масштаб окна",
	["Window Alpha"] = "Прозрачность окна",
	["Set Window Spawn Location"] = "Установка места появления окна",
	["Up"] = "Вверх",
	["Down"] = "Вниз",
	["Left"] = "Влево",
	["Right"] = "Вправо",
	["Cascade overlapping windows."] = "Каскад окон с наложением.",
	["Ignore arrow keys in message box."] = "Игнорировать кнопки передвижения в строке ввода.",
	["Allow <ESC> to hide windows."] = "Позволить скрывать окно клавишей <ESC>.", 
	["Display Settings"] = "Настройки отображения",
	["Configure general window display settings."] = "Настройки отображения основного окна.",
	["Window Skin:"] = "Шкурка окна:",
	["Version"] = "Версия",
	["Color: System Messages"] = "Цвет: системных сообщений",
	["Color: Error Messages"] = "Цвет: ошибок",
	["Color: URL - Web Addresses"] = "Цвет: URL - интернет адресов",
	["Color: History Messages Sent"] = "Цвет: высылаемых сообщений в истории",
	["Color: History Messages Received"] = "Цвет: получаемых сообщений в истории",
	["Use colors suggested by skin."] = "Использовать цвета входящие в шкурку.",
	["Enable window fading effects."] = "Включить эффекты затухания окна",
	["Enable window animation effects."] = "Включить эффекты анимации окна",
	["Display item links when hovering over them."] = "Отображать ссылки предметов при зависании мышью над ними.",
	["Fonts"] = "Шрифты",
	["Configure the fonts used in WIM's message windows."] = "Настройка используемых шрифтов в окне сообщений WIMа.",
	["Font Outline"] = "Контур шрифта",
	["Thin"] = "Тонкий",
	["Thick"] = "Толстый",
	["Use font suggested by skin."] = "Использовать шрифт входящий в шкурку.",
	["Chat Font Size"] = "Размер шрифта чата",
	["Configure general display settings when dealing with whispers."] = "Настройка основного отображения когда происходит общение шепотом.",
	["Color: Messages Sent"] = "Цвет: высылаемых сообщений",
	["Color: Messages Received"] = "Цвет: получаемых сообщений",
	["Use colors suggested by skin."] = "Исп. встроенные цвета шкурки.",
	["Display user class icons and details."] = "Отображать иконку класса пользователя и другие детали.",
	["Requires who lookups."] = "Требует поиск через команду /who",
	["Display Shortcut Bar"] = "Отображать панель ярлыков",
	["Allow"] = "Разрешить",
	["Ignore"] = "Игнорировать",
	["Block"] = "Блокировать",
	["Filtering"] = "Фильтрация",
	["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = "Фильтрация позволяет вам контролировать, какие сообщения обрабатывать, а также каким образом они будут обрабатываться WIMом.",
	["Enable Filtering"] = "Включить фильтрацию",
	["Protected"] = "Под защитой",
	["Action:"] = "Действие",
	["Occurrences:"] = "Появление",
	["Delete Filter"] = "Удалить фильтр",
	["History"] = "История",
	["WIM can store conversations to be viewed at a later time."] = "WIM может хранить беседы, которые можно проссматривать в любое время.",
	["Enable History"] = "Включить историю",
	["Messages"] = "Сообщений",
	["Preview history inside message windows."] = "Пред просмотр истории в окне сообщения.",
	["Record Whispers"] = "Записывать шепот",
	["Record Friends"] = "Записывать друзей",
	["Record Guild"] = "Записывать гильдию",
	["Record Everyone"] = "Записывать всех",
	["Record Chat"] = "Записывать чат",
	["Maintenance"] = "Поддержка",
	["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "Позволяя вести журнал вашей истории, что может сильно повлиять на производительность вашей игры, поэтому рекомендуется использовать следующие настройки.",
	["Save a maximum number of messages per person."] = "Макс. количество сохраняемых сообщений на человека.",
	["%d |4Week:Weeks;"] = "%d |4ниделя: нидели:нидель;",
	["Automatically delete old messages."] = "Автоматически удалять старые сообщения.",
	["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM даёт возможность пользователям с WIM взаимодействовать таким образом, что нормальное перешептывание не может.",
	["Enable WIM-2-WIM"] = "Включить WIM-2-WIM",
	["Privacy"] = "Личное дело",
	["Restrict the data that is shared."] = "Ограничить разделение/вывод данных.",
	["Allow others to see me typing."] = "Позволить другим видеть когда вы печатаете.",
	["Allow others to see my location."] = "Позволить другим видеть ваше местоположение.",
	["Main"] = "Главное",
	["General"] = "Основное",
	["User Level"] = "Уровень игрока",
	["Windows will also be hidden when frames such as the world map are shown."] = "Окно будет также закрыто при открытии карты.",
	["Sounds"] = "Звуки",
	["Configure various sound events and how they are triggered."] = "настройка звуковых оповещений и когда они будут проигрываться.",
	["Play sound when a whisper is received."] = "Проиграть звук при получении сообщения.",
	["Play special sound for friends."] = "Специальный звук для друзей.",
	["Play special sound for guild members."] = "Специальный звук для членов гильдии.",
	["Play sound when a whisper is sent."] = "Проиграть звук при отправке сообщения.",
	["Allow others to see my talent spec."] = "Позволить другим видеть мои таланты.",
	["Window Strata:"] = "Слой окна",
	["Unlock from Minimap"] = "Открепить от мини-карты",
    ["Press <Tab> to advance to next tell target."] = "Нажмите <Tab> чтобы перейти к следующему собеседнику.",
    ["Colorize names."] = "Окраска имён.",
    
    -- TabManagement.lua --
	["Tab Management"] = "Управление закладками",
	["Automatically manage your open windows and place them into appropriate tab groups."] = "Автоматическое управление открытыми окнами и помещение их в соответствующие вкладки групп.",
	["Automatically group whispers."] = "Автоматически группировать",
	["Place friends in their own group."] = "Помещать друзей в отдельную группу.",
	["Place guild members in their own group."] = "Помещать членов гильдии в отдельную группу.",
	["Does not apply to windows already opened."] = "Не применять если окно уже открыто.",
	
        
    -- Talent Specs --
    ["Affliction"] = "Колдовство",
	["Arcane"] = "Тайная магия",
	["Arms"] = "Оружие",
	["Assassination"] = "Убийство",
	["Balance"] = "Баланс",
	["Beast Mastery"] = "Чувство зверя",
	["Blood"] = "Кровь",
	["Combat"] = "Бой",
	["Demonology"] = "Демонология",
	["Destruction"] = "Разрушение",
	["Discipline"] = "Послушание",
	["Elemental"] = "Укрощение стихии",
	["Enhancement"] = "Совершенствование",
	["Feral Combat"] = "Сила зверя",
	["Fire"] = "Огонь",
	["Frost"] = "Лед",
	["Fury"] = "Неистовство",
	["Holy"] = "Свет",
	["Hybrid"] = "Гибрид",
	["Marksmanship"] = "Стрельба",
	["Protection"] = "Защита",
	["Restoration"] = "Исцеление",
	["Retribution"] = "Возмездие",
	["Shadow"] = "Темная магия",
	["Subtlety"] = "Скрытность",
	["Survival"] = "Выживание",
	["Unholy"] = "Нечестивость",
	
    -- ChangeLog.lua --
    ["Change Log"] = "Список изменений",
    ["View WIM's change log."] = "Просмотр списка изменений WIM'а",
	["Available For Download!"] = "Доступно для скачивания!",
	
    -- Filters.lua --
    ["Show Alert"] = "Показ уведомления",
    ["WIM has blocked a message from %s."] = "WIM заблокировал сообщение от персонажа: %s.",
    ["View Blocked Message"] = "Просмотр заблокированного сообщения",
    ["Blocked Message"] = "Заблокированное сообщение",
	
    -- MinimapIcon.lua
    ["Show Unread Messages"] = "Показать непрочитанные сообщения",
    ["Show All Windows"] = "Показать все окна",
    ["Hide All Windows"] = "Скрыть все окна",
    
    --Emoticons.lua
    ["Also"] = "Также",
    ["More"] = "Еще",
    ["Emoticons"] = "Смайлики",
	
	--Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "Ваши диалоги были скрыты, чтобы очистить экран в то время как в находитесь в бою. Чтобы отключить эту функцию введите",
    ["Expose"] = "Экспонировка",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Экспонировка является инспирической особенностью Mac OS X, которая позволяет быстро очистить экран от окон, а затем восстановить их обратно в их первоначальное положение.",
    ["Auto hide/restore windows during combat."] = "Авто скрывать/открывать окона во время боя.",
    ["Border Size"] = "Размер рамки",
    ["Only while in an instance."] = "Только в подземельях.",
    ["Show Border"] = "Показать рамку",
    ["Animation Direction:"] = "Направления анимации:",
	
    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM будет управлять данным типом чата в рамках своего окна сообщений.",
    ["Show Minimap Alerts"] = "Оповещения у мини-карты",
    ["Never pop-up on my screen."] = "Никогда не всплывать на маём экране.",
    ["Never suppress messages."] = "Никогда не подавлять сообщения.",
    ["Have WIM monitor this channel."] = "Позволить WIMу следить за данным каналом.",
    ["Never Pop"] = "Не всплывать",
    ["Never have this window pop-up on my screen."] = "Никогда не позволять всплывать данному окну на моём экране.",
    ["Never Supress"] = "Не подавлять",
    ["Never suppress messages from the default chat frame."] = "Никогда не подавлять сообщения с стандартного окна чата.",
    ["Show unread message alert on minimap."] = "Показывать у мини-карты оповещение об непрочитанных сообщениях.",
    ["No History"] = "Без истории",
    ["Do not record history for this channel."] = "Не записывать историю для данного канала.",
    ["World Chat"] = "Мировой чат",
    ["Custom Chat"] = "Свой чат",
    ["Chat"] = "Чат",
    ["Play special sound for %s."] = "Проиграть особый звук для %s.",
    ["Play sound when a message is received."] = "Проиграть звук при получении сообщения.",
    ["Play sound when a message is sent."] = "Проиграть звук при отправке сообщения.",
    ["Do not play sounds for this channel."] = "Не проигрывать звук для данного канала.",
    ["No Sound"] = "Без звука",
	["Sensitivity"] = "Чувствительность",
    ["Enable WorldFrame Click Detection."] = "Включить обнаружение клика на мировом фрейме.",
    ["The UI must be reloaded in order to disable this module fully. Reload UI now?"] = "Для полного отключения данного модуля, требуется перезагрузить пользовательский интерфейс. Перезагрузить UI теперь?",
	
	--Misc
    ["WIM has detected that you are playing on a private server. Some servers can not process ChatAddonMessages. Would you like to enable them anyway?"] = "WIM обнаружил, что вы играете на частном сервере. Некоторые серверы не могут обрабатывать ChatAddonMessages. Хотите включить их все равно?",
    
});
