--[[
    Language Localization: zhCN
    Translated by: Junxian <junxian1121@hotmail.com>
]]

WIM.AddLocale("zhCN", {
    ["WIM (WoW Instant Messenger)"] = true,
    ["_Description"] = "WIM 的设计是为了让你在魔兽世界中与人交谈时有更亲切的介面，在这个视窗中您可以自订所有的设定。若您有任何的问题，欢迎各位到官方网页提供意见。\n网址：http://www.WIMAddon.com",

    ["_DemoText"] = "这个视窗可以设定对话视窗出现的预设位置。您可以将这个视窗拖曳到您想要的位置，当您关闭这个视窗的时候，所有的设定将被自动记录下来。",

    ["_DateFormat"] = "%m/%d/%Y",

    ["Yes"] = "是",
    ["No"] = "否",
    ["None"] = "无",
    ["<Right-Click>"] = "<滑鼠右键>",
    ["<Left-Click>"] = "<滑鼠左键>",
    ["OK"] = "确认",
    ["Cancel"] = "取消",
    ["Unknown"] = "未知",
    ["Click to update..."] = "点击更新...",
    ["Usage"] = "使用",
    
    ["state_resting"] = "休息",
    ["state_combat"] = "战斗",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "竞技场",
    ["state_party"] = "组队",
    ["state_raid"] = "团队",
    ["state_other"] = "一般 (其他)",
    
    ["<Shift-Click> to close window."] = "<Shift-左键> 关闭视窗",
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "目前已经有新版的 WIM!\n您可以到http://www.wimaddon.com 下载新版本",
    
    ["Options"] = "选项",
    
    ["Icon Position"] = "小图示/按钮位置",
    ["Font Size"] = "字型大小",
    ["Window Scale (Percent)"] = "缩放视窗(百分比)",
    ["Transparency (Percent)"] = "透明度(百分比)",
    ["Window Width"] = "视窗宽度",
    ["Window Height"] = "视窗高度",
    ["(Limited by shortcut bar)"] = "(受限於捷径列)",
    ["ERROR"] = "错误",
    ["Invalid Name!"] = "无效的名称",
    ["Name is already used!"] = "此名称已经被使用",
    ["Invalid Alias!"] = "无效的别名",
    ["Invalid Keyword/Phrase!"] = "无效的关键字/片词",
    ["Keyword/Phrase is already used!"] = "关键字/片词，已经被使用",
    
    ["Day"] = "日",
    ["Week"] = "周",
    ["Month"] = "月",
    ["Drag to set default spawn/position for message windows."] = "拖曳来设定对话视窗预设位置。",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Ignore"] = "忽略",
    ["Block"] = "封锁",
    ["Enable WIM"] = "开启 WIM",
    
    ["Auto Close Friends after:"] = "好友自动关闭时间:",
    ["Auto Close Non-Friends after:"] = "非好友自动关闭时间:",
    
    ["Display"] = "显示",
    ["Incoming Messages"] = "收到讯息",
    ["Outgoing Messages"] = "发出讯息",
    ["System Messages"] = "系统讯息",
    ["Error Messages"] = "错误讯息",
    ["Web URLs"] = "网址",
    ["Enable"] = "开启",
    ["Disable"] = "关闭",
    ["Enabled"] = "已开启",
    ["Disabled"] = "已关闭",
    ["Display character information."] = "显示人物资讯",
    ["Display time stamps"] = "显示时间标记",
    ["This setting limits the\nwindow's minimum height."] = "此设定受限於视窗最小高度",
    ["Requires /who querying."] = "请输入 /who 查询",
    ["Enable window fading effects."] = "开启视窗淡化效果",
    ["Enable window animations."] = "开启视窗动态效果",
    
    ["Display minimap icon."] = "显示小地图按钮",
    
    ["General"] = "一般",
    ["History"] = "聊天记录",
    ["Filters"] = "过滤条件",
    ["Plugins"] = "插件",
    
    ["Auto focus when window is shown."] = "当对话视窗出现，自动跳到最上层/获得焦点",
    ["Preserve focus after sending messages."] = "送出讯息後，仍将对话视窗保留在最上层/焦点状态",
    ["Display tooltips."] = "显示小秘诀",
    ["Show window when sending a message."] = "当送出讯息时跳出对话视窗",
    ["Show window when message has been received."] = "当收到讯息时跳出对话视窗",
    ["Supress messages from default chat frame."] = true,
    ["Play sound when message is received."] = "当收到讯息播放音效",
    ["Play sound when message is sent."] = "当送出讯息播放音效",
    ["Sort alphabetically."] = "依照字母排序",
    ["Use <Escape> to close windows."] = "使用 <Esc> 键来关闭对话视窗",
    ["Windows will close when opening the world map."] = "当开启世界地图，关闭所有对话视窗",
    ["Intercept slash commands."] = "拦截斜线指令（如/kick）",
    ["Ignore arrow keys while typing."] = "输入讯息时忽略方向键",
    ["Requires using <Alt> to navigate text."] = "需按 <Alt> 键才能送出讯息",
    ["Display emoticons."] = "显示心情符号",
    ["Display URLs as item links."] = "显示网址上的物品连结",
    ["Display floating item links."] = "直接显示物品连结",
    
    ["Cascade windows."] = "视窗层叠显示",
    ["Direction:"] = "方向:",
    ["Tabs"] = "标签列",
    ["Sort tabs by:"] = "依照下列规则切换标签",
    ["Window Created"] = "最先密你的",
    ["Last Activity"] = "最後密你的",
    ["Alphabetical"] = "字母顺序",
    ["Recent Activity"] = "最近使用",
    ["Keep windows on top of your UI."] = "保持对话视窗在介面的最上层",

    
    -- Class Names --
    ["Druid"] = "德鲁伊",
    ["Hunter"] = "猎人",
    ["Mage"] = "法师",
    ["Paladin"] = "圣骑士",
    ["Priest"] = "牧师",
    ["Rogue"] = "潜行者",
    ["Shaman"] = "萨满祭司",
    ["Warlock"] = "术士",
    ["Warrior"] = "战士",
    ["Death Knight"] = "死亡骑士",
    
    -- Female Class Names --
    ["DruidF"] = "Druid",
    ["HunterF"] = "Hunter",
    ["MageF"] = "Mage",
    ["PaladinF"] = "Paladin",
    ["PriestF"] = "Priest",
    ["RogueF"] = "Rogue",
    ["ShamanF"] = "Shaman",
    ["WarlockF"] = "Warlock",
    ["WarriorF"] = "Warrior",
    ["Death KnightF"] = "Death Knight",
    
    ["Game Master"] = "游戏管理者",
    
    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "开启/关闭 WIM",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "开启/关闭 Debugging 模式",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM 已载入。请进入设定页选择样式:",
    
    -- Filters.lua --
    ["Whispers Sent by Addons"] = "由插件所发出的密语",
    ["WhisperSelect Part 1"] = "密语选择 1",
    ["Example Spam Blocker"] = "阻挡的讯息范例",
    ["WhisperSelect Part 2"] = "密语选择 2",
    ["Filter Name"] = "过滤名字",
    ["Filter By"] = "过滤条件",
    ["Pattern"] = "模式",
    ["User Type"] = "玩家状况",
    ["Level"] = "等级",
    ["Friends"] = "好友",
    ["Guild Members"] = "公会成员",
    ["Party Members"] = "队伍成员",
    ["Raid Members"] = "团队成员",
    ["Cross-Realm"] = "敌对阵营",
    ["Everyone"] = "所有人",
    ["User must be at least level:"] = "使用者最低等级:",
    ["Apply to messages received."] = "套用到接收讯息规则",
    ["Apply to messages sent."] = "套用到传送讯息规则",
    ["Action to Perform:"] = "执行动作:",
    ["Allow"] = "允许",
    ["Ignore"] = "忽略",
    ["Blocked"] = "封锁",
    ["Save"] = "储存",
    ["Cancel"] = "取消",
    ["Edit Filter"] = "编辑过滤条件",
    ["Add Filter"] = "增加过滤条件",
    
    -- History.lua --
    ["WIM History Button"] = "WIM 对话纪录按钮",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "按下对话视窗的 %s 按钮将会显示使用者对话纪录。",
    ["Click to view message history."] = true,
    ["WIM pruned %d |4message:messages; from your history."] = true,
    ["History Viewer"] = "对话纪录检视",
    ["Filters"] = "过滤器",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "您确定要删除所有 %s 在 %s 的纪录？",
    ["Search resulted in %d |4message:messages;."] = "搜寻结果於 %d |4message:messages;",
    ["No results found!"] = "没有发现符合的条件!",
    ["Search"] = "搜寻",
    ["Show All"] = "显示全部",
    ["Loading History"] = "载入对话纪录",
    ["Chat View"] = "检视对话",
    ["Text View"] = "检视文字",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM 对话纪录检视可以随时透过下列指令开启:",
    ["WIM History Viewer"] = "检视 WIM 对话纪录",
    ["Display history viewer."] = "显示对话纪录",
    
    -- ldb.lua --
    ["No New Messages"] = "没有新的讯息",
    
    -- Menu.lua --
    ["Whispers"] = "密语",
    ["Chat"] = "聊天讯息",
    
    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM 已有新的更新!",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "目前已经有新版的WIM!\n您可以到 %s 下载新版本",
    
    -- ShortcutBar.lua --
    --["Location"] = "玩家位置",
    ["Player Location"] = "玩家位置",
    ["Unknown"] = "未知",
    ["Click to update..."] = "点击更新资讯...",
    ["Coordinates"] = "玩家座标",
    ["Invite to Party"] = "组队邀请",
    ["Add Friend"] = "加入好友",
    ["Ignore User"] = "加入黑名单",
    ["Are you sure you want to\nignore %s?"] = "您确定您要忽略 %s",
    
    -- Tutorials.lua --
    ["Display WIM tips"] = "显示 WIM 小提示",
    
    -- W2W.lua --
    ["%s is typing..."] = "%s 正在输入讯息...",
    ["W2W Profile"] = "W2W 设定",
    ["Talent Spec"] = "天赋资讯",
    
    -- WhisperEngine.lua --
    ["Whisper Received!"] = "收到密语!",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "您收到一个密语但因为您现在的活动而被隐藏。您可以变更 WIM 的密语设定。",
    
    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "你即将删除所有的 WIM 对话纪录",
    ["This action will reload your user interface."] = "这个动作将重新载入你的使用者介面",
    ["Do you want to continue?"] = "你确定要继续吗?",
    ["You are about to restore WIM's filters to it's default settings!"] = "你即将把 WIM 的过滤选项恢复成预设值!",
    ["Usage"] = "使用",
    ["Clear various WIM data."] = "清除所有 WIM 资料",
    
    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM 指令",
    ["To see a list of available WIM slash commands type:"] = "显示可用的 WIM 指令:",
    ["Display available slash commands."] = "显示可用的 WIM 指令",
    ["Reload User Interface."] = "重新载入使用者介面",
    
    -- TabHandler.lua --
    ["Manipulating Tabs"] = "操作群组标签",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "您可以 <shift-左键> 一个群组标签然後将它拖曳到属於它的视窗。",
    
    -- WindowHandler.lua --
    ["Window Resized!"] = "视窗尺寸已改变",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "若您想要将所有视窗变为此尺寸，您可以至WIM设定选单去对预设视窗做设定。",
    ["Creating Tab Groups"] = "建立群组标签",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "您可以透过 <Shift-左键> 点击一个视窗後，跟其他视窗拖曳在一起，将多个视窗合并成一个",
    ["Resizing Windows"] = "变更视窗尺寸",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "您可以透过按着 <Shift> 键并拖曳视窗右下角来变更视窗大小",
    ["Demo Window"] = "视窗范例",
    ["<Shift-Click> to close window."] = "<Shift-左键> 关闭视窗",
    ["Message Window Hidden"] = "隐藏讯息视窗",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = true,
    ["Default"] = "预设",
    ["%s is Away From Keyboard: %s"] = "%s 目前暂离: %s",
    ["%s does not wish to be disturbed: %s"] = "%s 目前不愿被打扰: %s",
    
    -- Options.lua --
    ["Display WIM's options."] = "显示 WIM 设定选单",
    ["Resetting WIM will clear all of your settings!"] = "重设 WIM 将会清除您所有的设定!",
    ["Reset all options to default."] = "将所有设定恢复为预设值",
    
    -- CoreOptions --
    ["Created by:"] = "作者：",
    ["Special Thanks:"] = "特别感谢：",
    ["Welcome!"] = "欢迎！",
    ["Enable WIM"] = "启用 WIM",
    ["Display Minimap Icon"] = "显示小地图按钮",
    ["<Right-Click> to show unread messages."] = "<右键> 显示未读密语",
    ["Display Tutorials"] = "显示教学",
    ["Reset Tutorials"] = "重设教学",
    ["Credits"] = "版权",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "这一段很长的讯息是给你观看设定後的显示效果用的。 其中包含网址连接与心情符号 8)。 我们的网址是 www.WIMAddon.com.",
    ["Message Formatting"] = "讯息格式",
    ["Manipulate how WIM displays messages."] = "设定 WIM 如何显示讯息格式",
    ["Preview"] = "预览",
    ["Display Time Stamps"] = "显示时间标签",
    ["Display Emoticons"] = "显示心情图示",
    ["Display URLs as Links"] = "显示网址连结",
    ["Indent long messages."] = "缩排长讯息",
    ["Window Behavior"] = "视窗的动作",
    ["You can control how windows behave while you are in different situations."] = "您可以设定讯息视窗在您不同的状态下的动作。",
    ["Intercept Slash Commands"] = "拦截斜线指令",
    ["Use the same rules for all states."] = "所有的状态下都采用相同规则",
    ["Behaviors for state:"] = "此行为套用到下列状态:",
    ["Pop-Up window when message is sent."] = "当送出密语时弹出对话视窗",
    ["Pop-Up window when message is received."] = "当收到密语时弹出对话视窗",
    ["Auto focus a window when it is shown."] = "当视窗弹出时自动获得焦点",
    ["Keep focus on window after sending a message."] = "发送讯息後视窗保持获得焦点状态",
    ["Suppress messages from the default chat frame."] = "过滤系统内建对话框中的密语讯息",
    ["Window Settings"] = "视窗设定",
    ["Some settings may be limited by certain skins."] = "部份设定将会因为套用的布景受到限制",
      ["Default Width"] = "预设宽度",
    ["Default Height"] = "预设高度",
    ["Window Scale"] = "视窗缩放",
    ["Window Alpha"] = "视窗透明度",
    ["Set Window Spawn Location"] = "设定视窗出现位置",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Cascade overlapping windows."] = "视窗重叠",
    ["Ignore arrow keys in message box."] = "在对话视窗中不使用方向键",
    ["Allow <ESC> to hide windows."] = "按下 <Esc> 隐藏所有对话视窗",
    ["Display Settings"] = "显示设定",
    ["Configure general window display settings."] = "设定对话视窗显示细节",
    ["Window Skin:"] = "视窗面版",
    ["Version"] = "版本",
    ["Color: System Messages"] = "颜色: 系统讯息",
    ["Color: Error Messages"] = "颜色: 错误讯息",
    ["Color: URL - Web Addresses"] = "颜色: 网址连结",
    ["Color: History Messages Sent"] = "颜色: 对话纪录-送出",
    ["Color: History Messages Received"] = "颜色: 对话纪录-收到",
    ["Use colors suggested by skin."] = "使用面版建议色彩",
    ["Enable window fading effects."] = "开启视窗淡化效果",
    ["Enable window animation effects."] = "开启视窗动态效果",
    ["Display item links when hovering over them."] = "当滑鼠移至物品连结上时，直接显示物品说明",
    ["Fonts"] = "字型",
    ["Configure the fonts used in WIM's message windows."] = "设定 WIM 讯息视窗中的字型",
    ["Font Outline"] = "字体外框",
    ["Thin"] = "细",
    ["Thick"] = "粗",
    ["Use font suggested by skin."] = "面版建议使用的字型",
    ["Chat Font Size"] = "对话文字大小",
    ["Configure general display settings when dealing with whispers."] = "设定当密语出现时的显示设定",
    ["Color: Messages Sent"] = "颜色: 已传送密语",
    ["Color: Messages Received"] = "颜色: 已接收密语",
    ["Use colors suggested by skin."] = "使用布景主题建议",
    ["Display user class icons and details."] = "显示对方职业图示与资讯",
    ["Requires who lookups."] = "需要用到查询功能",
    ["Display Shortcut Bar"] = "显示功能选单",
    ["Allow"] = "允许",
    ["Ignore"] = "忽略",
    ["Block"] = "封锁",
    ["Filtering"] = "过滤",
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = "在此您可以设定 WIM 的过滤机制",
    ["Enable Filtering"] = "开启过滤功能",
    ["Protected"] = "已保护",
    ["Action:"] = "动作:",
    ["Occurrences:"] = "发生次数:",
    ["Delete Filter"] = "删除过滤",
    ["History"] = "讯息纪录",
    ["WIM can store conversations to be viewed at a later time."] = "WIM 可以储存对话纪录",
    ["Enable History"] = "开启讯息记录",
    ["Messages"] = " 则讯息",
    ["Preview history inside message windows."] = "在对话视窗中显示的讯息数量",
    ["Record Whispers"] = "记录密语",
    ["Record Friends"] = "记录好友",
    ["Record Guild"] = "记录公会",
    ["Record Everyone"] = "记录所有人",
    ["Record Chat"] = "记录对话",
    ["Maintenance"] = "维护",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "当讯息记录档太大时，会影响到游戏的效能。因此我们建议您采用下列的步骤。",
    ["Save a maximum number of messages per person."] = "每个对象的最大密语储存数",
    ["%d |4Week:Weeks;"] = "%d 周",
    ["Automatically delete old messages."] = "自动清除旧讯息",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM 是一个允许不同使用者的WIM彼此通讯的功能。它可以办到密语系统无法办到的事情。",
    ["Enable WIM-2-WIM"] = "开启 WIM-2-WIM",
    ["Privacy"] = "隐私设定",
    ["Restrict the data that is shared."] = "限制分享的资讯",
    ["Allow others to see me typing."] = "让其他人知道我正在输入密语",
    ["Allow others to see my location."] = "让其他人知道我的位置",
    ["Main"] = "主选单",
    ["General"] = "一般功能",
    ["User Level"] = "玩家等级",
    ["Windows will also be hidden when frames such as the world map are shown."] = "当开启世界地图时，对话视窗隐藏",
    ["Sounds"] = "音效",
    ["Configure various sound events and how they are triggered."] = "设定此插件的音效功能",
    ["Play sound when a whisper is received."] = "当收到密语时拨放音效",
    ["Play special sound for friends."] = "设定朋友的特殊音效",
    ["Play special sound for guild members."] = "设定工会成员的特殊音效",
    ["Play sound when a whisper is sent."] = "当送出密语时拨放音效",
    ["Allow others to see my talent spec."] = "让其他人看见我的天赋资讯",
    ["Window Strata:"] = "视窗层级:",
    ["Unlock from Minimap"] = "解锁小地图按钮",
    
    -- TabManagement.lua --
    ["Tab Management"] = "标签管理",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "WIM 会将您的密语对话视窗自动放到适合的群组",
    ["Automatically group whispers."] = "自动群组密语对话视窗",
    ["Place friends in their own group."] = "将好友放在同一个群组",
    ["Place guild members in their own group."] = "将公会成员放在同一个群组",
    ["Does not apply to windows already opened."] = "不要套用到已经开启的对话视窗",

    -- Talent Specs --
        ["Affliction"] = "痛苦",
	["Arcane"] = "奥术",
	["Arms"] = "武器",
	["Assassination"] = "刺杀",
	["Balance"] = "平衡",
	["Beast Mastery"] = "野兽控制",
	["Blood"] = "鲜血",
	["Combat"] = "战斗",
	["Demonology"] = "恶魔学识",
	["Destruction"] = "毁灭",
	["Discipline"] = "戒律",
	["Elemental"] = "元素战斗",
	["Enhancement"] = "增强",
	["Feral Combat"] = "野性战斗",
	["Fire"] = "火焰",
	["Frost"] = "冰霜",
	["Fury"] = "狂怒",
	["Holy"] = "神圣",
	["Hybrid"] = "混合",
	["Marksmanship"] = "射击",
	["Protection"] = "防护",
	["Restoration"] = "恢复",
	["Retribution"] = "惩戒",
	["Shadow"] = "暗影魔法",
	["Subtlety"] = "敏锐",
	["Survival"] = "生存技能",
	["Unholy"] = "邪恶",
    
});