--[[
    Update:2010/07/04
    Language Localization: zhTW 
    Translated by: Junxian <junxian1121@hotmail.com>
]]

WIM.AddLocale("zhTW", {
    ["WIM (WoW Instant Messenger)"] = "WIM (魔獸世界即時通)",
    ["_Description"] = "WIM 的設計是為了讓你在魔獸世界中與人交談時有更親切的介面，在這個視窗中您可以自訂所有的設定。若您有任何的問題，歡迎各位到官方網頁提供意見。\n網址：http://www.WIMAddon.com",

    ["_DemoText"] = "這個視窗可以設定對話視窗出現的預設位置。您可以將這個視窗拖曳到您想要的位置，當您關閉這個視窗的時候，所有的設定將被自動記錄下來。",

    ["_DateFormat"] = "%m/%d/%Y",

    ["Yes"] = "是",
    ["No"] = "否",
    ["None"] = "無",
    ["<Right-Click>"] = "<滑鼠右鍵>",
    ["<Left-Click>"] = "<滑鼠左鍵>",
    ["OK"] = "確認",
    ["Cancel"] = "取消",
    ["Unknown"] = "未知",
    ["Click to update..."] = "點擊更新...",
    ["Usage"] = "使用",
    
    ["state_resting"] = "休息",
    ["state_combat"] = "戰鬥",
    ["state_pvp"] = "PVP",
    ["state_arena"] = "競技場",
    ["state_party"] = "組隊",
    ["state_raid"] = "團隊",
    ["state_other"] = "一般 (其他)",
    
    ["<Shift-Click> to close window."] = "<Shift-左鍵> 關閉視窗",
    
    ["A new version of WIM is available!\nYou can download the latest version by going to:\n\n http://www.wimaddon.com"] = "目前已經有新版的 WIM!\n您可以到http://www.wimaddon.com 下載新版本",
    
    ["Options"] = "選項",
    
    ["Icon Position"] = "小圖示/按鈕位置",
    ["Font Size"] = "字型大小",
    ["Window Scale (Percent)"] = "縮放視窗(百分比)",
    ["Transparency (Percent)"] = "透明度(百分比)",
    ["Window Width"] = "視窗寬度",
    ["Window Height"] = "視窗高度",
    ["(Limited by shortcut bar)"] = "(受限於捷徑列)",
    ["ERROR"] = "錯誤",
    ["Invalid Name!"] = "無效的名稱",
    ["Name is already used!"] = "此名稱已經被使用",
    ["Invalid Alias!"] = "無效的別名",
    ["Invalid Keyword/Phrase!"] = "無效的關鍵字/片詞",
    ["Keyword/Phrase is already used!"] = "關鍵字/片詞，已經被使用",
    
    ["Day"] = "日",
    ["Week"] = "週",
    ["Month"] = "月",
    ["Drag to set default spawn/position for message windows."] = "拖曳來設定對話視窗預設位置。",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Ignore"] = "忽略",
    ["Block"] = "封鎖",
    ["Enable WIM"] = "開啟 WIM",
    
    ["Auto Close Friends after:"] = "好友自動關閉時間:",
    ["Auto Close Non-Friends after:"] = "非好友自動關閉時間:",
    
    ["Display"] = "顯示",
    ["Incoming Messages"] = "收到訊息",
    ["Outgoing Messages"] = "發出訊息",
    ["System Messages"] = "系統訊息",
    ["Error Messages"] = "錯誤訊息",
    ["Web URLs"] = "網址",
    ["Enable"] = "開啟",
    ["Disable"] = "關閉",
    ["Enabled"] = "已開啟",
    ["Disabled"] = "已關閉",
    ["Display character information."] = "顯示人物資訊",
    ["Display time stamps"] = "顯示時間標記",
    ["This setting limits the\nwindow's minimum height."] = "此設定受限於視窗最小高度",
    ["Requires /who querying."] = "請輸入 /who 查詢",
    ["Enable window fading effects."] = "開啟視窗淡化效果",
    ["Enable window animations."] = "開啟視窗動態效果",
    
    ["Display minimap icon."] = "顯示小地圖按鈕",
    
    ["General"] = "一般",
    ["History"] = "聊天記錄",
    ["Filters"] = "過濾條件",
    ["Plugins"] = "插件",
    
    ["Auto focus when window is shown."] = "當對話視窗出現，自動跳到最上層/獲得焦點",
    ["Preserve focus after sending messages."] = "送出訊息後，仍將對話視窗保留在最上層/焦點狀態",
    ["Display tooltips."] = "顯示小秘訣",
    ["Show window when sending a message."] = "當送出訊息時跳出對話視窗",
    ["Show window when message has been received."] = "當收到訊息時跳出對話視窗",
    ["Supress messages from default chat frame."] = true,
    ["Play sound when message is received."] = "當收到訊息播放音效",
    ["Play sound when message is sent."] = "當送出訊息播放音效",
    ["Sort alphabetically."] = "依照字母排序",
    ["Use <Escape> to close windows."] = "使用 <Esc> 鍵來關閉對話視窗",
    ["Windows will close when opening the world map."] = "當開啟世界地圖，關閉所有對話視窗",
    ["Intercept slash commands."] = "攔截斜線指令（如/kick）",
    ["Ignore arrow keys while typing."] = "輸入訊息時忽略方向鍵",
    ["Requires using <Alt> to navigate text."] = "需按 <Alt> 鍵才能送出訊息",
    ["Display emoticons."] = "顯示心情符號",
    ["Display URLs as item links."] = "顯示網址上的物品連結",
    ["Display floating item links."] = "直接顯示物品連結",
    
    ["Cascade windows."] = "視窗層疊顯示",
    ["Direction:"] = "方向:",
    ["Tabs"] = "標籤列",
    ["Sort tabs by:"] = "依照下列規則切換標籤",
    ["Window Created"] = "最先密你的",
    ["Last Activity"] = "最後密你的",
    ["Alphabetical"] = "字母順序",
    ["Recent Activity"] = "最近使用",
    ["Keep windows on top of your UI."] = "保持對話視窗在介面的最上層",
    ["Enable/Disable addon messages."] = "開啟/關閉插件訊息",

    -- Class Names --
    ["Druid"] = "德魯伊",
    ["Hunter"] = "獵人",
    ["Mage"] = "法師",
    ["Paladin"] = "聖騎士",
    ["Priest"] = "牧師",
    ["Rogue"] = "盜賊",
    ["Shaman"] = "薩滿",
    ["Warlock"] = "術士",
    ["Warrior"] = "戰士",
    ["Death Knight"] = "死亡騎士",
    
    -- Female Class Names --
    ["DruidF"] = "德魯伊",
    ["HunterF"] = "獵人",
    ["MageF"] = "法師",
    ["PaladinF"] = "聖騎士",
    ["PriestF"] = "牧師",
    ["RogueF"] = "盜賊",
    ["ShamanF"] = "薩滿",
    ["WarlockF"] = "術士",
    ["WarriorF"] = "戰士",
    ["Death KnightF"] = "死亡騎士",
    
    ["Game Master"] = "遊戲管理者",
    
    -- WIM.lua --
    ["Toggle WIM 'On' and 'Off'."] = "開啟/關閉 WIM",
    ["Toggle Debugging Mode 'On' and 'Off'."] = "開啟/關閉 Debugging 模式",
    ["WIM is currently running. To access WIM's wide array of options type:"] = "WIM 已載入。請進入設定頁選擇樣式:",
    
    -- Filters.lua --
    ["Whispers Sent by Addons"] = "由插件所發出的密語",
    ["WhisperSelect Part 1"] = "密語選擇 1",
    ["Example Spam Blocker"] = "阻擋的訊息範例",
    ["WhisperSelect Part 2"] = "密語選擇 2",
    ["Filter Name"] = "過濾名字",
    ["Filter By"] = "過濾條件",
    ["Pattern"] = "模式",
    ["User Type"] = "玩家狀況",
    ["Level"] = "等級",
    ["Friends"] = "好友",
    ["Guild Members"] = "公會成員",
    ["Party Members"] = "隊伍成員",
    ["Raid Members"] = "團隊成員",
    ["Cross-Realm"] = "敵對陣營",
    ["Everyone"] = "所有人",
    ["User must be at least level:"] = "使用者最低等級:",
    ["Apply to messages received."] = "套用到接收訊息規則",
    ["Apply to messages sent."] = "套用到傳送訊息規則",
    ["Action to Perform:"] = "執行動作:",
    ["Allow"] = "允許",
    ["Ignore"] = "忽略",
    ["Blocked"] = "封鎖",
    ["Save"] = "儲存",
    ["Cancel"] = "取消",
    ["Edit Filter"] = "編輯過濾條件",
    ["Add Filter"] = "增加過濾條件",
    
    -- History.lua --
    ["WIM History Button"] = "WIM 對話記錄按鈕",
    ["Clicking the %s button on the message window will show that user's history in WIM's History Viewer."] = "按下對話視窗的 %s 按鈕將會顯示使用者對話記錄。",
    ["Click to view message history."] = "檢視歷史記錄",
    ["WIM pruned %d |4message:messages; from your history."] = "WIM 刪除 %d |4message:messages; 從你的歷史記錄",
    ["History Viewer"] = "對話記錄檢視",
    ["Filters"] = "過濾器",
    ["Are you sure you want to delete all history saved for %s on %s?"] = "您確定要刪除所有 %s 在 %s 儲存的記錄？",
    ["Search resulted in %d |4message:messages;."] = "搜尋結果於 %d |4message:messages;",
    ["No results found!"] = "沒有發現符合的條件!",
    ["Search"] = "搜尋",
    ["Show All"] = "顯示全部",
    ["Loading History"] = "載入對話記錄",
    ["Chat View"] = "檢視對話",
    ["Text View"] = "檢視文字",
    ["WIM History Viewer can be accessed any time by typing:"] = "WIM 對話記錄檢視可以隨時透過下列指令開啟:",
    ["WIM History Viewer"] = "檢視 WIM 對話記錄",
    ["Display history viewer."] = "顯示對話記錄",
    
    -- ldb.lua --
    ["No New Messages"] = "沒有新的訊息",
    
    -- Menu.lua --
    ["Whispers"] = "密語",
    ["Chat"] = "聊天訊息",
    
    -- Negotiate.lua --
    ["WIM Update Available!"] = "WIM 已有新的更新!",
    ["There is a newer version of WIM available for download. You can download it at %s."] = "目前已經有新版的 WIM!\n您可以到 %s 下載新版本",
    
    -- ShortcutBar.lua --
    ["Location"] = "玩家位置",
    --["Player Location"] = "玩家位置",
    ["Unknown"] = "未知",
    ["Click to update..."] = "點擊更新資訊...",
    ["Coordinates"] = "玩家座標",
    ["Invite to Party"] = "組隊邀請",
    ["Add Friend"] = "加入好友",
    ["Ignore User"] = "加入黑名單",
    ["Are you sure you want to\nignore %s?"] = "您確定您要忽略 %s",
    ["Right-Click for profile links..."] ="右鍵點擊 查看英雄榜",
    ["Profile Links"] = "查看英雄榜",
    
    -- Tutorials.lua --
    ["Display WIM tips"] = "顯示 WIM 小提示",
    
    -- W2W.lua --
    ["%s is typing..."] = "%s 正在輸入訊息...",
    ["W2W Profile"] = "W2W 設定",
    ["Talent Spec"] = "天賦資訊",
    
    -- WhisperEngine.lua --
    ["Whisper Received!"] = "收到密語!",
    ["You received a whisper which was hidden due to your current activity. You can change how whispers behave in WIM's options by typing"] = "您收到一個密語但因為您現在的活動而被隱藏。您可以變更 WIM 的密語設定。",
    ["Recently Sent Messages"] = "最近傳送的訊息",

    -- Clear.lua --
    ["You are about to clear all of WIM's history!"] = "你即將刪除所有的 WIM 對話記錄",
    ["This action will reload your user interface."] = "這個動作將重新載入你的使用者介面",
    ["Do you want to continue?"] = "你確定要繼續嗎?",
    ["You are about to restore WIM's filters to it's default settings!"] = "你即將把 WIM 的過濾選項恢復成預設值!",
    ["Usage"] = "使用",
    ["Clear various WIM data."] = "清除所有 WIM 資料",
    
    -- SlashHandler.lua --
    ["WIM Slash Commands"] = "WIM 指令",
    ["To see a list of available WIM slash commands type:"] = "顯示可用的 WIM 指令:",
    ["Display available slash commands."] = "顯示可用的 WIM 指令",
    ["Reload User Interface."] = "重新載入使用者介面",
    
    -- TabHandler.lua --
    ["Manipulating Tabs"] = "操作群組標籤",
    ["You can <Shift-Click> a tab and drag it out into it's own window."] = "您可以 <shift-左鍵> 一個群組標籤然後將它拖曳到屬於它的視窗。",
    
    -- WindowHandler.lua --
    ["Window Resized!"] = "視窗尺寸已改變",
    ["If you want all windows to be this size, you can set the default window size within WIM's options."] = "若您想要將所有視窗變為此尺寸，您可以至WIM設定選單去對預設視窗做設定。",
    ["Creating Tab Groups"] = "建立群組標籤",
    ["You can group two or many windows together by <Shift-Clicking> a window and dragging it on top of another."] = "您可以透過 <Shift-左鍵> 點擊一個視窗後，跟其他視窗拖曳在一起，將多個視窗合併成一個",
    ["Resizing Windows"] = "變更視窗尺寸",
    ["You can resize a window by holding <Shift> and dragging the bottom right corner of the window."] = "您可以透過按著 <Shift> 鍵並拖曳視窗右下角來變更視窗大小",
    ["Demo Window"] = "視窗範例",
    ["<Shift-Click> to close window."] = "<Shift-左鍵> 關閉視窗",
    ["Message Window Hidden"] = "隱藏訊息視窗",
    ["WIM's message window has been hidden to WIM's Minimap Icon. If you want to end a conversation, you may do so by <Shift-Clicking> the close button."] = true,
    ["Default"] = "預設",
    ["%s is Away From Keyboard: %s"] = "%s 目前暫離: %s",
    ["%s does not wish to be disturbed: %s"] = "%s 目前不願被打擾: %s",
    ["Right-Mouse Click!"] = "滑鼠 右鍵點擊!",
    ["There might be useful tools hidden under the message box. Right-Click to see them!"] = "有可用的工具被隱藏在訊息欄下方，請按滑鼠右鍵開啟",
    
    -- Options.lua --
    ["Display WIM's options."] = "顯示 WIM 設定選單",
    ["Resetting WIM will clear all of your settings!"] = "重設 WIM 將會清除您所有的設定!",
    ["Reset all options to default."] = "將所有設定恢復為預設值",
    
    -- CoreOptions --
    ["Created By:"] = "作者：",
    ["Special Thanks:"] = "特別感謝：",
    ["Welcome!"] = "歡迎！",
    ["Enable WIM"] = "啟用 WIM",
    ["Display Minimap Icon"] = "顯示小地圖按鈕",
    ["<Right-Click> to show unread messages."] = "<右鍵> 顯示未讀密語",
    ["Display Tutorials"] = "顯示教學",
    ["Reset Tutorials"] = "重設教學",
    ["Credits"] = "榮譽",
    ["This is a long message which contains both emoticons and urls 8). WIM's home is www.WIMAddon.com."] = "這一段很長的訊息是給你觀看設定後的顯示效果用的。 其中包含網址連接與心情符號 8)。 我們的網址是 www.WIMAddon.com",
    ["Message Formatting"] = "訊息格式",
    ["Manipulate how WIM displays messages."] = "設定 WIM 如何顯示訊息格式",
    ["Preview"] = "預覽",
    ["Display Time Stamps"] = "顯示時間標籤",
    ["Display Emoticons"] = "顯示心情圖示",
    ["Display URLs as Links"] = "顯示網址連結",
    ["Indent long messages."] = "縮排長訊息",
    ["Window Behavior"] = "視窗的動作",
    ["You can control how windows behave while you are in different situations."] = "您可以設定訊息視窗在您不同的狀態下的動作。",
    ["Intercept Slash Commands"] = "攔截斜線指令",
    ["Behaviors per current state"] ="各種情況動作",
    ["Use the same rules for all states."] = "所有的狀態下都採用相同規則",
    ["Behaviors for state:"] = "此行為套用到下列狀態:",
    ["Pop-Up window when message is sent."] = "當送出密語時彈出對話視窗",
    ["Pop-Up window when message is received."] = "當收到密語時彈出對話視窗",
    ["Auto focus a window when it is shown."] = "當視窗彈出時自動獲得焦點",
    ["Keep focus on window after sending a message."] = "發送訊息後視窗保持獲得焦點狀態",
    ["Suppress messages from the default chat frame."] = "過濾系統內建對話框中的密語訊息",
    ["Window Settings"] = "視窗設定",
    ["Some settings may be limited by certain skins."] = "部份設定將會因為套用的佈景受到限制",
    ["Default Width"] = "預設寬度",
    ["Default Height"] = "預設高度",
    ["Window Scale"] = "視窗縮放",
    ["Window Alpha"] = "視窗透明度",
    ["Set Window Spawn Location"] = "設定視窗出現位置",
    ["Up"] = "上",
    ["Down"] = "下",
    ["Left"] = "左",
    ["Right"] = "右",
    ["Cascade overlapping windows."] = "視窗重疊",
    ["Ignore arrow keys in message box."] = "在對話視窗中不使用方向鍵",
    ["Allow <ESC> to hide windows."] = "按下 <Esc> 隱藏所有對話視窗",
    ["Display Settings"] = "顯示設定",
    ["Configure general window display settings."] = "設定對話視窗顯示細節",
    ["Window Skin:"] = "視窗面版",
    ["Version"] = "版本",
    ["Color: System Messages"] = "顏色: 系統訊息",
    ["Color: Error Messages"] = "顏色: 錯誤訊息",
    ["Color: URL - Web Addresses"] = "顏色: 網址連結",
    ["Color: History Messages Sent"] = "顏色: 對話記錄-送出",
    ["Color: History Messages Received"] = "顏色: 對話記錄-收到",
    ["Use colors suggested by skin."] = "使用面版建議色彩",
    ["Enable window fading effects."] = "開啟視窗淡化效果",
    ["Enable window animation effects."] = "開啟視窗動態效果",
    ["Display item links when hovering over them."] = "當滑鼠移至物品連結上時，直接顯示物品說明",
    ["Fonts"] = "字型",
    ["Configure the fonts used in WIM's message windows."] = "設定 WIM 訊息視窗中的字型",
    ["Font Outline"] = "文字描邊",
    ["Thin"] = "細",
    ["Thick"] = "粗",
    ["Use font suggested by skin."] = "面版建議使用的字型",
    ["Chat Font Size"] = "對話文字大小",
    ["Configure general display settings when dealing with whispers."] = "設定當密語出現時的顯示設定",
    ["Color: Messages Sent"] = "顏色: 已傳送密語",
    ["Color: Messages Received"] = "顏色: 已接收密語",
    ["Color: BNet Messages Sent"] = "顏色: 已傳送 BNet 密語",
    ["Color: BNet Messages Received"] ="顏色: 已接收 BNet 密語",

    ["Use colors suggested by skin."] = "使用佈景主題建議",
    ["Display user class icons and details."] = "顯示對方職業圖示與資訊",
    ["Requires who lookups."] = "需要用到查詢功能",
    ["Display Shortcut Bar"] = "顯示功能選單",
    ["Allow"] = "允許",
    ["Ignore"] = "忽略",
    ["Block"] = "封鎖",
    ["Filtering"] = "過濾",
    ["Filtering allows you to control which messages are handled as well as how they are handlef by WIM."] = "在此您可以設定 WIM 的過濾機制",
    ["Enable Filtering"] = "開啟過濾功能",
    ["Protected"] = "已保護",
    ["Action:"] = "動作:",
    ["Occurrences:"] = "發生次數:",
    ["Delete Filter"] = "刪除過濾",
    ["History"] = "訊息記錄",
    ["WIM can store conversations to be viewed at a later time."] = "WIM 可以儲存對話記錄",
    ["Enable History"] = "開啟訊息記錄",
    ["Messages"] = " 則訊息",
    ["Preview history inside message windows."] = "在對話視窗中顯示的訊息數量",
    ["Record Whispers"] = "記錄密語",
    ["Record Friends"] = "記錄好友",
    ["Record Guild"] = "記錄公會",
    ["Record Everyone"] = "記錄所有人",
    ["Record Chat"] = "記錄對話",
    ["Maintenance"] = "維護",
    ["Allowing your history logs to grow too large will affect the game's performance, therefore it is reccomended that you use the following options."] = "當訊息記錄檔太大時，會影響到遊戲的效能。因此我們建議您採用下列的步驟。",
    ["Save a maximum number of messages per person."] = "每個對象的最大密語儲存數",
    ["%d |4Week:Weeks;"] = "%d 週",
    ["Automatically delete old messages."] = "自動清除舊訊息",
    ["WIM-2-WIM is a feature which allows users with WIM to interact in ways that normal whispering can not."] = "WIM-2-WIM 是一個允許不同使用者的WIM彼此通訊的功能。它可以辦到密語系統無法辦到的事情。",
    ["Enable WIM-2-WIM"] = "開啟 WIM-2-WIM",
    ["Privacy"] = "隱私設定",
    ["Restrict the data that is shared."] = "限制分享的資訊",
    ["Allow others to see me typing."] = "讓其他人知道我正在輸入密語",
    ["Allow others to see my location."] = "讓其他人知道我的位置",
    ["Main"] = "主選單",
    ["General"] = "一般功能",
    ["User Level"] = "玩家等級",
    ["Windows will also be hidden when frames such as the world map are shown."] = "當開啟世界地圖時，對話視窗隱藏",
    ["Sounds"] = "音效",
    ["Configure various sound events and how they are triggered."] = "設定此插件的音效功能",
    ["Play sound when a whisper is received."] = "當收到密語時撥放音效",
    ["Play special sound for friends."] = "設定好友音效",
    ["Play special sound for guild members."] = "設定公會成員音效",
    ["Play sound when a whisper is sent."] = "當送出密語時撥放音效",
    ["Allow others to see my talent spec."] = "讓其他人看見我的天賦資訊",
    ["Play special sound for battle.net friends."] = "設定 battle.net 好友音效",
    ["Window Strata:"] = "視窗層級:",
    ["Unlock from Minimap"] = "解鎖小地圖按鈕",
    ["Press <Tab> to advance to next tell target."] = "按下 <Tab> 切換到下一個對話欄",
    ["Colorize names."] = "名字上色",
    ["Bracket names."] = "名字加上括號",
    ["Clamp window to screen."] = "限制視窗不超出畫面",
    ["Group with whisper windows."] = "群組包含密語視窗",
    
    -- TabManagement.lua --
    ["Tab Management"] = "標籤管理",
    ["Automatically manage your open windows and place them into appropriate tab groups."] = "WIM 會將您的密語對話視窗自動放到適合的群組",
    ["Automatically group whispers."] = "自動群組密語對話視窗",
    ["Place friends in their own group."] = "將好友放在同一個群組",
    ["Place guild members in their own group."] = "將公會成員放在同一個群組",
    ["Automatically group chat windows."] = "自動群組聊天對話視窗",
    ["Does not apply to windows already opened."] = "不要套用到已經開啟的對話視窗",

    -- Talent Specs --
        ["Affliction"] = "痛苦",
	["Arcane"] = "秘法",
	["Arms"] = "武器",
	["Assassination"] = "刺殺",
	["Balance"] = "平衡",
	["Beast Mastery"] = "野獸控制",
	["Blood"] = "血魄",
	["Combat"] = "戰鬥",
	["Demonology"] = "惡魔學識",
	["Destruction"] = "毀滅",
	["Discipline"] = "戒律",
	["Elemental"] = "元素",
	["Enhancement"] = "增強",
	["Feral Combat"] = "野性戰鬥",
	["Fire"] = "火焰",
	["Frost"] = "冰霜",
	["Fury"] = "狂怒",
	["Holy"] = "神聖",
	["Hybrid"] = "混合",
	["Marksmanship"] = "射擊",
	["Protection"] = "防護",
	["Restoration"] = "恢復",
	["Retribution"] = "懲戒",
	["Shadow"] = "暗影",
	["Subtlety"] = "敏銳",
	["Survival"] = "生存",
	["Unholy"] = "穢邪",

    -- ChangeLog.lua --
    ["Change Log"] = "更新日誌",
    ["View WIM's change log."] = "檢視 WIM 的更新日誌",
    ["Available For Download!"] = "有新版本可下載！",
    
    -- Filters.lua --
    ["Show Alert"] = "顯示警告",
    ["WIM has blocked a message from %s."] = "WIM 發現阻檔訊息來自 %s",
    ["View Blocked Message"] = "檢視阻檔訊息",
    ["Blocked Message"] = "阻檔訊息",
    
    -- MinimapIcon.lua
    ["Show Unread Messages"] = "顯示未閱讀訊息",
    ["Show All Windows"] = "顯示所有視窗",
    ["Hide All Windows"] = "隱藏所有視窗",
    
    --Emoticons.lua
    ["Also"] = "並且",
    ["More"] = "更多",
    ["Emoticons"] = "心情符號",
    
    --Expose.lua
    ["Your conversations have been hidden in order to clear your screen while in combat. To disable this feature type"] = "你的對話視窗將在進入戰鬥狀態時被隱藏。要停用這個功能請輸入:",
    ["Expose"] = "Expose",
    ["Expose is a Mac OS X inspired feature which enables you to quickly clear your screen of windows and then restore them back to their original position."] = "Expose 是 Mac OS X 的一個增強功能，當你處於戰鬥時可快速清除畫面上的對話視窗，在戰鬥結束後再恢復顯示對話視窗",
    ["Auto hide/restore windows during combat."] = "戰鬥時自動 隱藏/恢復 對話視窗",
    ["Delay if I am typing a message."] = "如果我正在輸入訊息則延遲關閉",
    ["Border Size"] = "邊框大小",
    ["Only while in an instance."] = "只在副本中",
    ["Show Border"] = "顯示邊框",
    ["Animation Direction:"] = "動畫方向:",

    --ChatEngine.lua
    ["WIM will manage this chat type within its own message windows."] = "WIM 可收集不同頻道的對話並在各自獨立的視窗中呈現",
    ["Show Minimap Alerts"] = "顯示小地圖警示",
    ["Never pop-up on my screen."] = "絕不在我的螢幕上突然彈出",
    ["Never suppress messages."] = "絕不抑制訊息",
    ["Have WIM monitor this channel."] = "WIM 已監視這個頻道",
    ["Never Pop"] = "絕不彈出",
    ["Never have this window pop-up on my screen."] = "這個視窗絕不在我的螢幕上突然彈出",
    ["Never Supress"] = "絕不抑制",
    ["Never suppress messages from the default chat frame."] = "預設的聊天框中絕不抑制訊息",
    ["Show unread message alert on minimap."] = "在小地圖上提示有未閱讀的訊息",
    ["No History"] = "無對話記錄",
    ["Do not record history for this channel."] = "這個頻道不記錄對話內容",
    ["World Chat"] = "一般頻道",
    ["Custom Chat"] = "自定頻道",
    ["Chat"] = "聊天",
    ["Play special sound for %s."] = "對 %s 撥放特別的音效",
    ["Play sound when a message is received."] = "當收到訊息時撥放音效",
    ["Play sound when a message is sent."] = "當發送訊息時撥放音效",
    ["Do not play sounds for this channel."] = "這個頻道不要播放音效",
    ["No Sound"] = "無聲",
    ["Sensitivity"] = "靈敏度",
    ["Enable WorldFrame Click Detection."] = "啟用「世界框架」點擊檢測",
    ["The UI must be reloaded in order to disable this module fully. Reload UI now?"] = "為了使這個 UI 模組完全停用，你必須重新載入所有 UI，你現在要重新載入 UI 嗎？",
    
    --OffScreenTracker.lua
    ["WIM Window Off Screen"] = "關閉 WIM 視窗追蹤",
    ["Click to reposition."] = "點擊 重新定位",
    
    --Misc
    ["WIM has detected that you are playing on a private server. Some servers can not process ChatAddonMessages. Would you like to enable them anyway?"] = "WIM 發現你正在一個私人的伺服器上玩 WOW，某些私人的伺服器並不完全支援 WIM 的模組，你是否仍要嘗試載入 WIM 呢？",

});