-------------------------------------------------------------------------------
-- Simplified Chinese localization 简体中文化 by xingdvd
-------------------------------------------------------------------------------

if GetLocale() == "zhCN" then
	Outfitter.cTitle = "Outfitter"
	Outfitter.cTitleVersion = Outfitter.cTitle.." "..Outfitter.cVersion

	Outfitter.cSingleItemFormat = "%s"
	Outfitter.cTwoItemFormat = "%s 和 %s"
	Outfitter.cMultiItemFormat = "%s{{, %s}} 和 %s"

	Outfitter.cNameLabel = "名称:"
	Outfitter.cCreateUsingTitle = "优化于:"
	Outfitter.cUseCurrentOutfit = "使用当前套装"
	Outfitter.cUseEmptyOutfit = "新建空白套装"
	Outfitter.cAutomationLabel = "自动:"

	Outfitter.cOutfitterTabTitle = "Outfitter"
	Outfitter.cOptionsTabTitle = "选项"
	Outfitter.cAboutTabTitle = "关于"

	Outfitter.cNewOutfit = "新套装"
	Outfitter.cRenameOutfit = "重命名套装"

	Outfitter.cCompleteOutfits = "全部换装"
	Outfitter.cAccessoryOutfits = "补充套装"
	Outfitter.cOddsNEndsOutfits = "零星物件"

	Outfitter.cGlobalCategory = "特殊套装"
	Outfitter.cNormalOutfit = "普通套装"
	Outfitter.cNakedOutfit = "裸体套装"

	Outfitter.cScriptCategoryName = {}
	Outfitter.cScriptCategoryName.PVP = "PvP"
	Outfitter.cScriptCategoryName.TRADE = "激活"
	Outfitter.cScriptCategoryName.GENERAL = "一般"
	Outfitter.cScriptCategoryName.QUEST = "任务"
	Outfitter.cScriptCategoryName.ENTERTAIN = "消遣"

	Outfitter.cArgentDawnOutfit = "银色黎明"
	Outfitter.cCityOutfit = "主城范围"
	Outfitter.cBattlegroundOutfit = "战场"
	Outfitter.cAVOutfit = "战场：奥特兰克山谷"
	Outfitter.cABOutfit = "战场：阿拉希盆地"
	Outfitter.cArenaOutfit = "战场: 竞技场"
	Outfitter.cEotSOutfit = "战场: 风暴之眼"
	Outfitter.cWSGOutfit = "战场：战歌峡谷"
	Outfitter.cSotAOutfit = "战场：远古海滩"
	Outfitter.cIoCOutfit = "战场：征服者之岛"
	Outfitter.cDiningOutfit = "进餐"
	Outfitter.cFishingOutfit = "钓鱼"
	Outfitter.cHerbalismOutfit = "草药学"
	Outfitter.cMiningOutfit = "采矿"
	Outfitter.cFireResistOutfit = "火焰抗性"
	Outfitter.cNatureResistOutfit = "自然抗性"
	Outfitter.cShadowResistOutfit = "暗影抗性"
	Outfitter.cArcaneResistOutfit = "奥术抗性"
	Outfitter.cFrostResistOutfit = "冰霜抗性"
	Outfitter.cRidingOutfit = "骑乘"
	Outfitter.cSkinningOutfit = "剥皮"
	Outfitter.cSwimmingOutfit = "游泳"
	Outfitter.cLowHealthOutfit = "低生命或低法力"
	Outfitter.cHasBuffOutfit = "某增益"
	Outfitter.cHasDebuffOutfit = "某减益"
	Outfitter.cInZonesOutfit = "某地区"
	Outfitter.cSoloOutfit = "单练/小队/团队"
	Outfitter.cFallingOutfit = "跌落"
	Outfitter.cPvPFlaggedOutfit = "PVP指示"
	Outfitter.cInDungeonOutfit = "地下城"
	Outfitter.cArgentTournamentOutfit = "银色锦标赛"
	Outfitter.cMultiphaseSurveyOutfit = "多相数据调查"
	Outfitter.cSpellcastOutfit = "法术施放"
	Outfitter.cRestingOutfit = "旅馆"
	Outfitter.cFlameLeviathanOutfit = "烈焰巨兽"

	Outfitter.cArgentDawnOutfitDescription = "身处瘟疫之地时，自动切换为此套装备"
	Outfitter.cRidingOutfitDescription = "骑乘时，自动切换为此套装备"
	Outfitter.cDiningOutfitDescription = "吃喝时，自动切换为此套装备，直至生命值/法力值超过90%"
	Outfitter.cBattlegroundOutfitDescription = "身处战场时，自动切换为此套装备"
	Outfitter.cArathiBasinOutfitDescription = "身处阿拉希盆地时，自动切换为此套装备"
	Outfitter.cAlteracValleyOutfitDescription = "身处奥特兰克山谷时，自动切换为此套装备"
	Outfitter.cWarsongGulchOutfitDescription = "身处战歌峡谷时，自动切换为此套装备"
	Outfitter.cEotSOutfitDescription = "身处风暴之眼时，自动切换为此套装备"
	Outfitter.cSotAOutfitDescription = "身处远古海滩时，自动切换为此套装备"
	Outfitter.cIoCOutfitDescription = "身处征服者之岛时，自动切换为此套装备"
	Outfitter.cArenaOutfitDescription = "身处竞技场时，自动切换为此套装备"
	Outfitter.cCityOutfitDescription = "身处主城时，自动切换为此套装备"
	Outfitter.cSwimmingOutfitDescription = "游泳时，自动切换为此套装备"
	Outfitter.cFishingOutfitDescription = "进入战斗自动换下装备，并在脱离战斗时重新装备"
	Outfitter.cSpiritOutfitDescription = "精神回魔时，自动切换为此套装备(脱离五秒规则)"
	Outfitter.cHerbalismDescription = "当鼠标滑过某橙色/红色的草药点时，自动切换为此套装备"
	Outfitter.cMiningDescription = "当鼠标滑过某橙色/红色的矿石点时，自动切换为此套装备"
	Outfitter.cLockpickingDescription = "当鼠标滑过某橙色/红色的开锁箱子时，自动切换为此套装备"
	Outfitter.cSkinningDescription = "当鼠标滑过某橙色/红色的可剥皮生物时，自动切换为此套装备"
	Outfitter.cLowHealthDescription = "当生命值/法力值低于设定值时，自动切换为此套装备"
	Outfitter.cHasBuffDescription = "拥有特定增益效果时，自动切换为此套装备"
	Outfitter.cHasDebuffDescription = "拥有特定减益效果时，自动切换为此套装备"
	Outfitter.SpiritRegenOutfitDescription = "精神回魔时，自动切换为此套装备(脱离五秒规则)"
	Outfitter.cDruidCasterFormDescription = "不处在任何德鲁伊变身形态时，自动切换为此套装备"
	Outfitter.cPriestShadowformDescription = "暗影形态时，自动切换为此套装备"
	Outfitter.cShamanGhostWolfDescription = "幽魂之狼时，自动切换为此套装备"
	Outfitter.cHunterMonkeyDescription = "灵猴守护时，自动切换为此套装备"
	Outfitter.cHunterHawkDescription = "雄鹰守护时，自动切换为此套装备"
	Outfitter.cHunterCheetahDescription = "猎豹守护时，自动切换为此套装备"
	Outfitter.cHunterPackDescription = "豹群守护时，自动切换为此套装备"
	Outfitter.cHunterBeastDescription = "野兽守护时，自动切换为此套装备"
	Outfitter.cHunterWildDescription = "野性守护时，自动切换为此套装备"
	Outfitter.cHunterViperDescription = "蝰蛇守护时，自动切换为此套装备"
	Outfitter.cHunterDragonhawkDescription = "龙鹰守护时，自动切换为此套装备"
	Outfitter.cHunterFeignDeathDescription = "假死时，自动切换为此套装备"
	Outfitter.cMageEvocateDescription = "唤醒时，自动切换为此套装备"
	Outfitter.cWarriorBerserkerStanceDescription = "狂暴姿态时，自动切换为此套装备"
	Outfitter.cWarriorDefensiveStanceDescription = "防御姿态时，自动切换为此套装备"
	Outfitter.cWarriorBattleStanceDescription = "战斗姿态时，自动切换为此套装备"
	Outfitter.cInZonesOutfitDescription = "身处以下区域或其子区域时，自动切换为此套装备"
	Outfitter.cSoloOutfitDescription = "依据设置当单练/小队/团队时，自动切换为此套装备"
	Outfitter.cFallingOutfitDescription = "高空坠落时，自动切换为此套装备"
	Outfitter.cPvPFlaggedDescription = "当处于PVP指示时，自动切换为此套装备"
	Outfitter.cInDungeonDescription = "依据设置当处于地下城/团队/战场副本时，自动切换为此套装备"
	Outfitter.cArgentTournamentOutfitDescription = "当鼠标滑过银色锦标赛的坐骑时自动换下装备，并在脱离载具时重新装备"
	Outfitter.cRestingOutfitDescription = "身处旅馆时，自动切换为此套装备"
	Outfitter.cFlameLeviathanOutfitDescription = "当进入烈焰巨兽的载具时自动换下装备，并在脱离载具且战斗结束时重新装备"

	Outfitter.cMountSpeedFormat = "速度提高 (%d+)%%%."; -- For detecting when mounted
	Outfitter.cFlyingMountSpeedFormat = "飞行速度提高 (%d+)%%%."; -- For detecting when mounted

	Outfitter.cBagsFullError = "Outfitter: 背包空间不够，不能卸下物品 %s 。"
	Outfitter.cDepositBagsFullError = "Outfitter: 银行储物柜空间不够，不能寄放物品 %s 。"
	Outfitter.cWithdrawBagsFullError = "Outfitter: 包裹空间不够，不能拿取物品 %s 。"
	Outfitter.cItemNotFoundError = "Outfitter: 未能找到物品 %s。"
	Outfitter.cItemAlreadyUsedError = "Outfitter: 不能将%s放入%s，因其已经存在于另一位置"
	Outfitter.cAddingItem = "Outfitter: 添加 %s 到 %s 套装。"
	Outfitter.cNameAlreadyUsedError = "错误: 套装名已经存在。"
	Outfitter.cNoItemsWithStatError = "警告: 物品不具备该属性。"
	Outfitter.cCantUnequipCompleteError = "Outfitter: 无法换下 %s，因为不能换下全部着装（你必须装备另一套全部着装）。"

	Outfitter.cEnableAll = "启用所有"
	Outfitter.cEnableNone = "禁用所有"

	Outfitter.cConfirmDeleteMsg = "确定删除套装 %s?"
	Outfitter.cConfirmRebuildMsg = "确定重组套装 %s?"
	Outfitter.cRebuild = "重组"

	Outfitter.cSilverwingHold = "银翼要塞"
	Outfitter.cWarsongLumberMill = "战歌伐木场"

	Outfitter.cTotalStatsName = "所有属性"
	Outfitter.cItemLevelName = "物品等级"

	Outfitter.cCombatManaRegenStatName = "5秒回魔(战斗)"
	Outfitter.cCombatHealthRegenStatName = "5秒回血(战斗)"

	Outfitter.cOptionsTitle = "Outfitter 选项"
	Outfitter.cShowMinimapButton = "显示小地图按钮"
	Outfitter.cShowMinimapButtonOnDescription = "禁用（在小地图上隐藏 Outfitter 按钮）"
	Outfitter.cShowMinimapButtonOffDescription = "启用（在小地图上显示 Outfitter 按钮）"
	Outfitter.cAutoSwitch = "禁用套装自动切换"
	Outfitter.cAutoSwitchOnDescription = "启用（装备不自动切换）"
	Outfitter.cAutoSwitchOffDescription = "禁用（装备将自动切换）"
	Outfitter.cTooltipInfo = "显示提示"
	Outfitter.cTooltipInfoOnDescription = "禁用（不在提示上显示' 用于：'信息）"
	Outfitter.cTooltipInfoOffDescription = "启用（在提示上显示'用于：' 信息）"
	Outfitter.cItemComparisons = "物品比较时显示"
	Outfitter.cItemComparisonsOnDescription = "在物品比较时关闭此功能则只包含已装备的物品"
	Outfitter.cItemComparisonsOffDescription = "在物品比较时开启此功能则包含套装的物品"
	Outfitter.cOutfitDisplay = "Outfit 显示"
	Outfitter.cShowHotkeyMessages = "显示快捷键换装信息"
	Outfitter.cShowHotkeyMessagesOnDescription = "禁用（使用快捷键换装时不显示信息）"
	Outfitter.cShowHotkeyMessagesOffDescription = "启用（使用快捷键换装时显示信息）"
	Outfitter.cShowOutfitBar = "显示装备条"
	Outfitter.cShowOutfitBarDescription = "显示装备按钮条以便切换套装"
	Outfitter.cEquipOutfitMessageFormat = "Outfitter: %s 已装备"
	Outfitter.cUnequipOutfitMessageFormat = "Outfitter: %s 未装备"

	Outfitter.cAboutTitle = "关于 Outfitter"
	Outfitter.cAboutAuthor = "John Stephen 设计编写"
	Outfitter.cAboutCopyright = "Copyright 2009, 2010 John Stephen, wobbleworks.com"
	Outfitter.cAboutThanks = "非常感谢所有玩家及支持者！"

	Outfitter.cGermanLocalization = "德语译者"
	Outfitter.cChineseLocalization = "汉语译者"
	Outfitter.cFrenchLocalization = "法语译者"
	Outfitter.cSpanishLocalization = "西班牙语译者"
	Outfitter.cRussianLocalization = "俄语译者"
	Outfitter.cKoreanLocalization = "韩语译者"
	Outfitter.cContributingDeveloper = "开发贡献者"
	Outfitter.cTester = "测试者"
	Outfitter.cGuildCreditFormat = "%s 公会"

	Outfitter.cOpenOutfitter = "打开 Outfitter"

	Outfitter.cKeyBinding = "绑定于"

	BINDING_HEADER_OUTFITTER_TITLE = Outfitter.cTitle
	BINDING_NAME_OUTFITTER_OUTFIT = "打开 Outfitter"

	BINDING_NAME_OUTFITTER_OUTFIT1  = "套装 1"
	BINDING_NAME_OUTFITTER_OUTFIT2  = "套装 2"
	BINDING_NAME_OUTFITTER_OUTFIT3  = "套装 3"
	BINDING_NAME_OUTFITTER_OUTFIT4  = "套装 4"
	BINDING_NAME_OUTFITTER_OUTFIT5  = "套装 5"
	BINDING_NAME_OUTFITTER_OUTFIT6  = "套装 6"
	BINDING_NAME_OUTFITTER_OUTFIT7  = "套装 7"
	BINDING_NAME_OUTFITTER_OUTFIT8  = "套装 8"
	BINDING_NAME_OUTFITTER_OUTFIT9  = "套装 9"
	BINDING_NAME_OUTFITTER_OUTFIT10 = "套装 10"

	BINDING_NAME_OUTFITTER_ENABLEAUTOMATION = "启用自动换装"
	BINDING_NAME_OUTFITTER_DISABLEAUTOMATION = "禁用自动换装"

	Outfitter.cShow = "显示"
	Outfitter.cHide = "隐藏"
	Outfitter.cDontChange = "不做改变"

	Outfitter.cHelm = "头盔"
	Outfitter.cCloak = "披风"
	Outfitter.cPlayerTitle = "头衔"

	Outfitter.cMore = "更多"

	Outfitter.cAutomation = "自动"

	Outfitter.cDisableOutfit = "禁用套装"
	Outfitter.cDisableAlways = "总是禁用"
	Outfitter.cDisableOutfitInBG = "在战场禁用套装"
	Outfitter.cDisableOutfitInCombat = "战斗中禁用套装"
	Outfitter.cDisableOutfitInAQ40 = "在安其拉禁用套装"
	Outfitter.cDisableOutfitInNaxx = "在纳克萨玛斯禁用套装"
	Outfitter.cDisabledOutfitName = "%s (关闭)"

	Outfitter.cOutfitBar = "装备条"
	Outfitter.cShowInOutfitBar = "在装备条上显示"
	Outfitter.cChangeIcon = "选择图标..."

	Outfitter.cMinimapButtonTitle = "Outfitter 小地图按钮"
	Outfitter.cMinimapButtonDescription = "单击左键选择不同的套装或左键拖曳重新定位小地图按钮。"

	Outfitter.cClassName = {}
	Outfitter.cClassName.DRUID = "德鲁伊"
	Outfitter.cClassName.HUNTER = "猎人"
	Outfitter.cClassName.MAGE = "法师"
	Outfitter.cClassName.PALADIN = "圣骑士"
	Outfitter.cClassName.PRIEST = "牧师"
	Outfitter.cClassName.ROGUE = "潜行者"
	Outfitter.cClassName.SHAMAN = "萨满祭司"
	Outfitter.cClassName.WARLOCK = "术士"
	Outfitter.cClassName.WARRIOR = "战士"

	Outfitter.cBattleStance = "战斗姿态"
	Outfitter.cDefensiveStance = "防御姿态"
	Outfitter.cBerserkerStance = "狂暴姿态"

	Outfitter.cWarriorBattleStance = "战士: 战斗姿态"
	Outfitter.cWarriorDefensiveStance = "战士: 防御姿态"
	Outfitter.cWarriorBerserkerStance = "战士: 狂暴姿态"

	Outfitter.cDruidCasterForm = "德鲁伊：施法形态"
	Outfitter.cDruidBearForm = "德鲁伊：熊形态"
	Outfitter.cDruidCatForm = "德鲁伊：猎豹形态"
	Outfitter.cDruidAquaticForm = "德鲁伊：水栖形态"
	Outfitter.cDruidTravelForm = "德鲁伊：旅行形态"
	Outfitter.cDruidMoonkinForm = "德鲁伊：枭兽形态"
	Outfitter.cDruidFlightForm = "德鲁伊：飞行形态"
	Outfitter.cDruidSwiftFlightForm = "德鲁伊：迅捷飞行形态"
	Outfitter.cDruidTreeOfLifeForm = "德鲁伊：生命之树"
	Outfitter.cDruidProwl = "德鲁伊：潜行"
	Outfitter.cProwl = "潜行"

	Outfitter.cPriestShadowform = "牧师: 暗影形态"

	Outfitter.cRogueStealth = "潜行者: 潜行"
	Outfitter.cLockpickingOutfit = "潜行者: 开锁"

	Outfitter.cShamanGhostWolf = "萨满祭司：幽魂之狼"

	Outfitter.cHunterMonkey = "猎人：灵猴"
	Outfitter.cHunterHawk =  "猎人：雄鹰"
	Outfitter.cHunterCheetah =  "猎人：猎豹"
	Outfitter.cHunterPack =  "猎人：豹群"
	Outfitter.cHunterBeast =  "猎人：野兽"
	Outfitter.cHunterWild =  "猎人：野性"
	Outfitter.cHunterViper = "猎人: 蝰蛇"
	Outfitter.cHunterDragonhawk = "猎人: 龙鹰"
	Outfitter.cHunterFeignDeath = "猎人: 假死"

	Outfitter.cMageEvocate = "法师：唤醒"

	Outfitter.cDeathknightBlood = "死亡骑士：鲜血灵气"
	Outfitter.cDeathknightFrost = "死亡骑士：冰霜灵气"
	Outfitter.cDeathknightUnholy = "死亡骑士：邪恶灵气"

	Outfitter.cCompleteCategoryDescription = "全部换装：每个位置都有自定义装备，换装时将换掉所有位置的装备。"
	Outfitter.cAccessoryCategoryDescription = "补充套装：只定义了一部分而不是全部位置。不象部分换装，你可以为其选择尽可能多的喜欢的套装，他们将会联合在一起并会在需要时覆盖当前选择的全部换装和部分换装。"
	Outfitter.cOddsNEndsCategoryDescription = "零星物件是所有未见于任何套装的装备列表。主要用处是可以让你确认使用了所有装备或者没有携带多余的装备。"

	Outfitter.cRebuildOutfitFormat = "重组于 %s"
	Outfitter.cRebuildFor = "重组于..."

	Outfitter.cSlotEnableTitle = "位置设置"
	Outfitter.cSlotEnableDescription = "勾选：切换套装时，更换此位置的装备；未勾选：切换套装时，此位置不会有任何改变。"

	Outfitter.cFinger0SlotName = "戒指(上)"
	Outfitter.cFinger1SlotName = "戒指(下)"

	Outfitter.cTrinket0SlotName = "饰品(上)"
	Outfitter.cTrinket1SlotName = "饰品(下)"

	Outfitter.cOutfitCategoryTitle = "类别"
	Outfitter.cBankCategoryTitle = "银行"
	Outfitter.cDepositToBank = "将所有物品存入银行"
	Outfitter.cDepositUniqueToBank = "将唯一物品存入银行"
	Outfitter.cDepositOthersToBank = "将其他套装存入银行"
	Outfitter.cWithdrawFromBank = "从银行取出物品"
	Outfitter.cWithdrawOthersFromBank = "从银行取出其他套装"

	Outfitter.cMissingItemsLabel = "缺少的物品: "
	Outfitter.cBankedItemsLabel = "寄放在银行的物品: "

	Outfitter.cResistCategory = "抗性"
	Outfitter.cTradeCategory = "商业技能"

	Outfitter.cTankPoints = "坦克点"
	Outfitter.cCustom = "自定义"

	Outfitter.cScriptFormat = "脚本 (%s)"
	Outfitter.cScriptSettings = "设置..."
	Outfitter.cNoScript = "无"
	Outfitter.cDisableScript = "禁用脚本"
	Outfitter.cDisableIn = "禁用更多"
	Outfitter.cEditScriptTitle = "套装：%s 的脚本"
	Outfitter.cEditScriptEllide = "编辑脚本..."
	Outfitter.cEventsLabel = "事件:"
	Outfitter.cScriptLabel = "脚本:"
	Outfitter.cSetCurrentItems = "更新当前装备"
	Outfitter.cConfirmSetCurrentMsg = "确定将当前装备用于套装：%s？注：只有当前启用的位置才会被更新 -- 你也可以在以后启用其它位置。"
	Outfitter.cSetCurrent = "更新"
	Outfitter.cTyping = "输入..."
	Outfitter.cScriptErrorFormat = "错误发生在 %d 行: %s"
	Outfitter.cExtractErrorFormat = "%[字符串 \"Outfit Script\"%]:(%d+):(.*)"
	Outfitter.cPresetScript = "预设脚本:"
	Outfitter.cCustomScript = "自定义"
	Outfitter.cSettings = "设置"
	Outfitter.cSource = "源"
	Outfitter.cInsertFormat = "<- %s"

	Outfitter.cNone = "无"
	Outfitter.cTooltipMultibuffSeparator1 = " 和 "
	Outfitter.cTooltipMultibuffSeparator2 = " / "
	Outfitter.cNoScriptSettings = "此脚本没有设置选项。"
	Outfitter.cMissingItemsSeparator = ", "
	Outfitter.cUnequipOthers = "装备后，换下其他附属着装"

	Outfitter.cConfirmResetMsg = "确定要重置此角色的Outfitter设置？将会删除所有着装并重建默认着装。"
	Outfitter.cReset = "重置"

	Outfitter.cIconFilterLabel = "搜索："
	Outfitter.cIconSetLabel = "图标："

	Outfitter.cCantReloadUI = "你必须重新启动游戏来完成 Outfitter 的此次版本更新"
	Outfitter.cChooseIconTitle = "为 %s 套装选择一个图标"
	Outfitter.cOutfitterDecides = "Outfitter 将为你选择一个图标"

	Outfitter.cSuggestedIcons = "建议使用图标"
	Outfitter.cSpellbookIcons = "你的技能书"
	Outfitter.cYourItemIcons = "你的背包"
	Outfitter.cEveryIcon = "全部图标"
	Outfitter.cItemIcons = "全部图标(只包含物品)"
	Outfitter.cAbilityIcons = "全部图标(只包含技能)"

	Outfitter.cRequiresLockpicking = "需要开锁"
	Outfitter.cUseTooltipLineFormat = "^使用:.*"
	Outfitter.cUseDurationTooltipLineFormat = "^使用:.*持续 (%d+) 秒"
	Outfitter.cUseDurationTooltipLineFormat2 = "^使用:.*持续 (%d+) 秒"

	Outfitter.cOutfitBarSizeLabel = "尺寸"
	Outfitter.cOutfitBarSmallSizeLabel = "小"
	Outfitter.cOutfitBarLargeSizeLabel = "大"
	Outfitter.cOutfitBarAlphaLabel = "透明度"
	Outfitter.cOutfitBarCombatAlphaLabel = "战斗透明度"
	Outfitter.cOutfitBarVerticalLabel = "垂直排列"
	Outfitter.cOutfitBarLockPositionLabel = "锁定位置"
	Outfitter.cOutfitBarHideBackgroundLabel = "隐藏背景"

	Outfitter.cPositionLockedError = "Outfit Bar 不能被移动因为你已经锁定了它的位置"

	Outfitter.cMustBeAtBankError = "你必须保持你的银行为打开状态来创建一个遗失物品列表"
	Outfitter.cMissingItemReportIntro = "遗失物品(如果一件物品被多个套装使用它将在列表中出现多次):"
	Outfitter.cNoMissingItems = "无装备遗失"

	Outfitter.cAutoChangesDisabled = "自动换装已禁用"
	Outfitter.cAutoChangesEnabled = "自动换装已启用"

	-- OutfitterFu strings

	Outfitter.cFuHint = "左键：打开 Outfitter 设置窗口"
	Outfitter.cFuHideMissing = "隐藏遗失"
	Outfitter.cFuHideMissingDesc = "隐藏遗失某物品的套装"
	Outfitter.cFuRemovePrefixes = "移除前缀"
	Outfitter.cFuRemovePrefixesDesc = "在 FuBar 上，删除套装名称前缀以缩短显示文字"
	Outfitter.cFuMaxTextLength = "最大文本长度"
	Outfitter.cFuMaxTextLengthDesc = "在 FuBar 上显示的最大文本长度"
	Outfitter.cFuHideMinimapButton = "隐藏微缩地图按钮"
	Outfitter.cFuHideMinimapButtonDesc = "隐藏 Outfitter 微缩地图按钮"
	Outfitter.cFuInitializing = "初始化"

	Outfitter.cStoreOnServer = "装备管理"
	Outfitter.cStoreOnServerOnDescription = "禁用装备管理，装备方案将保存于本地且其他计算机无法使用该方案。"
	Outfitter.cStoreOnServerOffDescription = "启用装备管理，装备方案将保存于服务器且最多保存10组方案。"
	Outfitter.cTooManyServerOutfits = "服务器上保存的装备方案不能超过 %d 组。"

	Outfitter.cCantSetIcon = "装备管理无法在切换装备方案时更换图标。"
	Outfitter.cChangeIcon = "更换图标"
	
	Outfitter.cNoItemsWithStat = "Couldn't generate an outfit because no items with that stat were found"
end