-------------------------------------------------------------------------------
-- Traditional Chinese localization 繁體中文化 by andy52005
-------------------------------------------------------------------------------

if GetLocale() == "zhTW" then
	Outfitter.cTitle = "換裝管理"
	Outfitter.cTitleVersion = Outfitter.cTitle.." "..Outfitter.cVersion

	Outfitter.cSingleItemFormat = "%s"
	Outfitter.cTwoItemFormat = "%s 和 %s"
	Outfitter.cMultiItemFormat = "%s{{, %s}} 和 %s"

	Outfitter.cNameLabel = "名稱:"
	Outfitter.cCreateUsingTitle = "最佳化:"
	Outfitter.cUseCurrentOutfit = "使用目前配裝"
	Outfitter.cUseEmptyOutfit = "建立新配裝"
	Outfitter.cAutomationLabel = "自動換裝:"

	Outfitter.cOutfitterTabTitle = "Outfitter"
	Outfitter.cOptionsTabTitle = "選項"
	Outfitter.cAboutTabTitle = "關於"

	Outfitter.cNewOutfit = "新配裝"
	Outfitter.cRenameOutfit = "變更配裝名稱"

	Outfitter.cCompleteOutfits = "完整配裝"
	Outfitter.cAccessoryOutfits = "零散配裝"
	Outfitter.cOddsNEndsOutfits = "零星裝備"

	Outfitter.cGlobalCategory = "特殊配裝"
	Outfitter.cNormalOutfit = "平常裝"
	Outfitter.cNakedOutfit = "生日裝"

	Outfitter.cScriptCategoryName = {}
	Outfitter.cScriptCategoryName.PVP = "PvP"
	Outfitter.cScriptCategoryName.TRADE = "活動"
	Outfitter.cScriptCategoryName.GENERAL = "一般"
	Outfitter.cScriptCategoryName.QUEST = "任務"
	Outfitter.cScriptCategoryName.ENTERTAIN = "休閒"

	Outfitter.cArgentDawnOutfit = "銀色黎明"
	Outfitter.cCityOutfit = "主城"
	Outfitter.cBattlegroundOutfit = "戰場"
	Outfitter.cAVOutfit = "戰場: 奧特蘭克山谷"
	Outfitter.cABOutfit = "戰場: 阿拉希盆地"
	Outfitter.cArenaOutfit = "戰場: 競技場"
	Outfitter.cEotSOutfit = "戰場: 暴風之眼"
	Outfitter.cWSGOutfit = "戰場: 戰歌峽谷"
	Outfitter.cSotAOutfit = "戰場: 遠祖灘頭"
	Outfitter.cIoCOutfit = "戰場: 征服之島"
	Outfitter.cDiningOutfit = "飲食"
	Outfitter.cFishingOutfit = "釣魚"
	Outfitter.cHerbalismOutfit = "採草"
	Outfitter.cMiningOutfit = "採礦"
	Outfitter.cFireResistOutfit = "抗性: 火焰"
	Outfitter.cNatureResistOutfit = "抗性: 自然"
	Outfitter.cShadowResistOutfit = "抗性: 暗影"
	Outfitter.cArcaneResistOutfit = "抗性: 秘法"
	Outfitter.cFrostResistOutfit = "抗性: 冰霜"
	Outfitter.cRidingOutfit = "騎乘"
	Outfitter.cSkinningOutfit = "剝皮"
	Outfitter.cSwimmingOutfit = "游泳"
	Outfitter.cLowHealthOutfit = "低生命力或法力"
	Outfitter.cHasBuffOutfit = "玩家的增益效果"
	Outfitter.cInZonesOutfit = "在特定區域"
	Outfitter.cSoloOutfit = "單練/小隊/團隊"
	Outfitter.cFallingOutfit = "墜落"
	Outfitter.cPvPFlaggedOutfit = "插旗PK"
	Outfitter.cInDungeonOutfit = "在特定副本"
	Outfitter.cArgentTournamentOutfit = "銀白聯賽"
	Outfitter.cMultiphaseSurveyOutfit = "多相測量"
	Outfitter.cSpellcastOutfit = "施放法術"
	Outfitter.cRestingOutfit = "靜止的"
	Outfitter.cFlameLeviathanOutfit = "烈焰戰輪"

	Outfitter.cArgentDawnOutfitDescription = "位在瘟疫之地時換上此配裝"
	Outfitter.cRidingOutfitDescription = "在坐騎上時換上此配裝"
	Outfitter.cDiningOutfitDescription = "進食或飲水時換上此配裝，直到生命力/法力超過 90%"
	Outfitter.cBattlegroundOutfitDescription = "位在任何戰場時換上此配裝"
	Outfitter.cArathiBasinOutfitDescription = "位在阿拉希盆地戰場時換上此配裝"
	Outfitter.cAlteracValleyOutfitDescription = "位在奧特蘭克山谷戰場時換上此配裝"
	Outfitter.cWarsongGulchOutfitDescription = "位在戰歌峽谷戰場時換上此配裝"
	Outfitter.cEotSOutfitDescription = "位在暴風之眼戰場時換上此配裝"
	Outfitter.cSotAOutfitDescription = "位在遠祖灘頭戰場時換上此配裝"
	Outfitter.cIoCOutfitDescription = "位在征服之島戰場時換上此配裝"
	Outfitter.cArenaOutfitDescription = "位在任何競技場時換上此配裝"
	Outfitter.cCityOutfitDescription = "位在任何友好主城時換上此配裝"
	Outfitter.cSwimmingOutfitDescription = "游泳時換上此配裝"
	Outfitter.cFishingOutfitDescription = "進入戰鬥時換下此配裝，戰鬥結束後重新換上"
	Outfitter.cSpiritOutfitDescription = "精神回魔時換上此配裝(脫離五秒規則時)"
	Outfitter.cHerbalismDescription = "當滑鼠游標移到一個橘色或紅色的草點上時換上此配裝"
	Outfitter.cMiningDescription = "當滑鼠游標移到一個橘色或紅色的礦點上時換上此配裝"
	Outfitter.cLockpickingDescription = "當滑鼠游標移到一個橘色或紅色的鎖上時換上此配裝"
	Outfitter.cSkinningDescription = "當滑鼠游標移到一個橘色或紅色的可剝皮生物上時換上此配裝"
	Outfitter.cLowHealthDescription = "當生命力或法力低於設定值時換上此配裝"
	Outfitter.cHasBuffDescription = "擁有特定的增益效果時換上此配裝"
	Outfitter.SpiritRegenOutfitDescription = "精神回魔時換上此配裝(脫離五秒規則時)"
	Outfitter.cDruidCasterFormDescription = "不處在任何德魯伊變身形態時換上此配裝"
	Outfitter.cPriestShadowformDescription = "進入暗影形態時換上此配裝"
	Outfitter.cShamanGhostWolfDescription = "變成鬼魂之狼時換上此配裝"
	Outfitter.cHunterMonkeyDescription = "靈猴守護時換上此配裝"
	Outfitter.cHunterHawkDescription = "雄鷹守護時換上此配裝"
	Outfitter.cHunterCheetahDescription = "獵豹守護時換上此配裝"
	Outfitter.cHunterPackDescription = "豹群守護時換上此配裝"
	Outfitter.cHunterBeastDescription = "野獸守護時換上此配裝"
	Outfitter.cHunterWildDescription = "野性守護時換上此配裝"
	Outfitter.cHunterViperDescription = "蝮蛇守護時換上此配裝"
	Outfitter.cHunterDragonhawkDescription = "龍鷹守護時換上此配裝"
	Outfitter.cHunterFeignDeathDescription = "假死時換上此配裝"
	Outfitter.cMageEvocateDescription = "喚醒時換上此配裝"
	Outfitter.cWarriorBerserkerStanceDescription = "狂暴姿態時換上此配裝"
	Outfitter.cWarriorDefensiveStanceDescription = "防禦姿態時換上此配裝"
	Outfitter.cWarriorBattleStanceDescription = "戰鬥姿態時換上此配裝"
	Outfitter.cInZonesOutfitDescription = "位在以下區域或其子區域時換上此配裝"
	Outfitter.cSoloOutfitDescription = "依設定在單練、小隊或團隊時換上此配裝"
	Outfitter.cFallingOutfitDescription = "墜落時換上此配裝"
	Outfitter.cPvPFlaggedDescription = "插旗PK時換上此配裝"
	Outfitter.cInDungeonDescription = "在副本/團隊或戰場副本時換上此配裝"
	Outfitter.cArgentTournamentOutfitDescription = "當滑鼠點到銀白聯賽的坐騎時換上此配裝，當離開此載具時則卸下配裝"
	Outfitter.cRestingOutfitDescription = "當進入旅館時換上此配裝"
	Outfitter.cFlameLeviathanOutfitDescription = "當進入烈焰戰輪的載具時換上此配裝，當離開或戰鬥結束時則卸下配裝"

	Outfitter.cMountSpeedFormat = "速度提高(%d+)%%%。"; -- For detecting when mounted
	Outfitter.cFlyingMountSpeedFormat = "飛行速度提高(%d+)%%%。"; -- For detecting when mounted

	Outfitter.cBagsFullError = "無法卸下 %s，因為所有包包已滿"
	Outfitter.cDepositBagsFullError = "無法存入 %s，因為所有銀行欄位已滿"
	Outfitter.cWithdrawBagsFullError = "無法提領 %s，因為所有包包已滿"
	Outfitter.cItemNotFoundError = "無法找到物品 %s"
	Outfitter.cItemAlreadyUsedError = "無法將 %s 裝在 %s 部位，因為它已用於其他部位"
	Outfitter.cAddingItem = "新增 %s 至 %s 配裝"
	Outfitter.cNameAlreadyUsedError = "錯誤: 這個名稱已被使用"
	Outfitter.cNoItemsWithStatError = "警告: 你沒有任何物品擁有該屬性"
	Outfitter.cCantUnequipCompleteError = "無法卸下 %s，因為完整配裝無法被卸下(你必須改用裝上另一套完整配裝的方式)"

	Outfitter.cEnableAll = "全部啟用"
	Outfitter.cEnableNone = "全部停用"

	Outfitter.cConfirmDeleteMsg = "確定刪除配裝設定: %s?"
	Outfitter.cConfirmRebuildMsg = "確定重建配裝設定: %s?"
	Outfitter.cRebuild = "重建"

	Outfitter.cSilverwingHold = "銀翼要塞"
	Outfitter.cWarsongLumberMill = "戰歌伐木場"

	Outfitter.cTotalStatsName = "全部屬性"
	Outfitter.cItemLevelName = "物品等級"

	Outfitter.cCombatManaRegenStatName = "每5秒恢復法力(戰鬥中)"
	Outfitter.cCombatHealthRegenStatName = "每5秒恢復生命力(戰鬥中)"

	Outfitter.cOptionsTitle = "換裝管理 選項"
	Outfitter.cShowMinimapButton = "顯示小地圖按鈕"
	Outfitter.cShowMinimapButtonOnDescription = "取消以隱藏 換裝管理 小地圖按鈕"
	Outfitter.cShowMinimapButtonOffDescription = "勾選以顯示 換裝管理 小地圖按鈕"
	Outfitter.cAutoSwitch = "停用自動換裝"
	Outfitter.cAutoSwitchOnDescription = "取消以啟用自動換裝功能"
	Outfitter.cAutoSwitchOffDescription = "勾選以停用自動換裝功能"
	Outfitter.cTooltipInfo = "在物品提示顯示配裝"
	Outfitter.cTooltipInfoOnDescription = "如果在滑鼠移到可裝備物品上時，遇到效能問題，取消此選項"
	Outfitter.cTooltipInfoOffDescription = "勾選以在物品提示中顯示裝備用在哪些配裝"
	Outfitter.cItemComparisons = "在裝備比較中顯示"
	Outfitter.cItemComparisonsOnDescription = "在裝備比較中若關閉此功能則只包含已裝備的物品"
	Outfitter.cItemComparisonsOffDescription = "在裝備比較的提示訊息中開啟此功能則包含你的配裝上的物品"
	Outfitter.cOutfitDisplay = "顯示配裝"
	Outfitter.cShowHotkeyMessages = "以按鍵換裝時顯示訊息"
	Outfitter.cShowHotkeyMessagesOnDescription = "取消以在按鍵換裝時不顯示訊息"
	Outfitter.cShowHotkeyMessagesOffDescription = "勾選以在按鍵換裝時顯示訊息"
	Outfitter.cShowOutfitBar = "顯示換裝列"
	Outfitter.cShowOutfitBarDescription = "顯示一列按鈕讓你點擊換裝"
	Outfitter.cEquipOutfitMessageFormat = "換裝管理: %s 裝上"
	Outfitter.cUnequipOutfitMessageFormat = "換裝管理: %s 卸下"

	Outfitter.cAboutTitle = "關於 換裝管理"
	Outfitter.cAuthor = "作者: John Stephen, contributions 及其他參與者 %s"
	Outfitter.cTestersTitle = "換裝管理測試者"
	Outfitter.cTestersNames = "%s"
	Outfitter.cSpecialThanksTitle = "特別感謝"
	Outfitter.cSpecialThanksNames = "%s"
	Outfitter.cTranslationCredit = "翻譯 %s"
	Outfitter.cURL = "wobbleworks.com"

	Outfitter.cOpenOutfitter = "開啟 換裝管理"

	Outfitter.cKeyBinding = "按鍵設定"

	BINDING_HEADER_OUTFITTER_TITLE = Outfitter.cTitle
	BINDING_NAME_OUTFITTER_OUTFIT = "開啟 換裝管理"

	BINDING_NAME_OUTFITTER_OUTFIT1  = "配裝 1"
	BINDING_NAME_OUTFITTER_OUTFIT2  = "配裝 2"
	BINDING_NAME_OUTFITTER_OUTFIT3  = "配裝 3"
	BINDING_NAME_OUTFITTER_OUTFIT4  = "配裝 4"
	BINDING_NAME_OUTFITTER_OUTFIT5  = "配裝 5"
	BINDING_NAME_OUTFITTER_OUTFIT6  = "配裝 6"
	BINDING_NAME_OUTFITTER_OUTFIT7  = "配裝 7"
	BINDING_NAME_OUTFITTER_OUTFIT8  = "配裝 8"
	BINDING_NAME_OUTFITTER_OUTFIT9  = "配裝 9"
	BINDING_NAME_OUTFITTER_OUTFIT10 = "配裝 10"

BINDING_NAME_OUTFITTER_ENABLEAUTOMATION = "啟用自動換裝"
BINDING_NAME_OUTFITTER_DISABLEAUTOMATION = "停用自動換裝"

	Outfitter.cShow = "顯示"
	Outfitter.cHide = "隱藏"
	Outfitter.cDontChange = "不改變"

	Outfitter.cHelm = "頭盔"
	Outfitter.cCloak = "披風"
	Outfitter.cPlayerTitle = "頭銜"

	Outfitter.cMore = "更多"

	Outfitter.cAutomation = "自動換裝"

	Outfitter.cDisableOutfit = "停用"
	Outfitter.cDisableAlways = "永遠"
	Outfitter.cDisableOutfitInBG = "戰場中"
	Outfitter.cDisableOutfitInCombat = "戰鬥中停用"
	Outfitter.cDisableOutfitInAQ40 = "在安其拉神廟"
	Outfitter.cDisableOutfitInNaxx = "在納克薩瑪斯"
	Outfitter.cDisabledOutfitName = "%s (停用)"

	Outfitter.cOutfitBar = "換裝列"
	Outfitter.cShowInOutfitBar = "顯示在換裝列"
	Outfitter.cChangeIcon = "選擇圖示..."

	Outfitter.cMinimapButtonTitle = "換裝管理 小地圖按鈕"
	Outfitter.cMinimapButtonDescription = "點擊選取另一配裝，或者拖曳變更位置"

	Outfitter.cClassName = {}
	Outfitter.cClassName.DRUID = "德魯伊"
	Outfitter.cClassName.HUNTER = "獵人"
	Outfitter.cClassName.MAGE = "法師"
	Outfitter.cClassName.PALADIN = "聖騎士"
	Outfitter.cClassName.PRIEST = "牧師"
	Outfitter.cClassName.ROGUE = "盜賊"
	Outfitter.cClassName.SHAMAN = "薩滿"
	Outfitter.cClassName.WARLOCK = "術士"
	Outfitter.cClassName.WARRIOR = "戰士"

	Outfitter.cBattleStance = "戰鬥姿態"
	Outfitter.cDefensiveStance = "防禦姿態"
	Outfitter.cBerserkerStance = "狂暴姿態"

	Outfitter.cWarriorBattleStance = "戰士: 戰鬥姿態"
	Outfitter.cWarriorDefensiveStance = "戰士: 防禦姿態"
	Outfitter.cWarriorBerserkerStance = "戰士: 狂暴姿態"

	Outfitter.cDruidCasterForm = "德魯伊: 人形態"
	Outfitter.cDruidBearForm = "德魯伊: 熊形態"
	Outfitter.cDruidCatForm = "德魯伊: 獵豹形態"
	Outfitter.cDruidAquaticForm = "德魯伊: 水棲形態"
	Outfitter.cDruidTravelForm = "德魯伊: 旅行形態"
	Outfitter.cDruidMoonkinForm = "德魯伊: 梟獸形態"
	Outfitter.cDruidFlightForm = "德魯伊: 飛行形態"
	Outfitter.cDruidSwiftFlightForm = "德魯伊: 迅捷飛行形態"
	Outfitter.cDruidTreeOfLifeForm = "德魯伊: 生命之樹形態"
	Outfitter.cDruidProwl = "德魯伊: 潛行"
	Outfitter.cProwl = "潛行"

	Outfitter.cPriestShadowform = "牧師: 暗影形態"

	Outfitter.cRogueStealth = "盜賊: 潛行"
	Outfitter.cLockpickingOutfit = "盜賊: 開鎖"

	Outfitter.cShamanGhostWolf = "薩滿: 鬼魂之狼"

	Outfitter.cHunterMonkey = "獵人: 靈猴守護"
	Outfitter.cHunterHawk =  "獵人: 雄鷹守護"
	Outfitter.cHunterCheetah =  "獵人: 獵豹守護"
	Outfitter.cHunterPack =  "獵人: 豹群守護"
	Outfitter.cHunterBeast =  "獵人: 野獸守護"
	Outfitter.cHunterWild =  "獵人: 野性守護"
	Outfitter.cHunterViper = "獵人: 蝮蛇守護"
	Outfitter.cHunterDragonhawk = "獵人: 龍鷹守護"
	Outfitter.cHunterFeignDeath = "獵人: 假死"

	Outfitter.cMageEvocate = "法師: 喚醒"

	Outfitter.cDeathknightBlood = "死亡騎士: 血魄領域"
	Outfitter.cDeathknightFrost = "死亡騎士: 冰霜領域"
	Outfitter.cDeathknightUnholy = "死亡騎士: 穢邪領域"

	Outfitter.cCompleteCategoryDescription = "完整配裝表示所有欄位都有設定物品。當完整配裝裝備時，其他所有配裝都會自動被卸下。"
	Outfitter.cAccessoryCategoryDescription = "零散配裝表示只有某些欄位有設定物品。零散配裝可以隨意地多套同時裝備上。"
	Outfitter.cOddsNEndsCategoryDescription = "零星裝備所列的是未被設定在任何配裝的裝備。這對於確認是否有用到所有物品，以及避免攜帶不必要的物品，可能會有幫助。"

	Outfitter.cRebuildOutfitFormat = "以 %s 重建"

	Outfitter.cSlotEnableTitle = "啟用欄位"
	Outfitter.cSlotEnableDescription = "勾選以讓此欄位物品，在更換到所選配裝時被裝上。如果沒有勾選，則在更換到所選配裝時，此欄位不會被更換。"

	Outfitter.cFinger0SlotName = "第一戒指欄"
	Outfitter.cFinger1SlotName = "第二戒指欄"

	Outfitter.cTrinket0SlotName = "第一飾品欄"
	Outfitter.cTrinket1SlotName = "第二飾品欄"

	Outfitter.cOutfitCategoryTitle = "類別"
	Outfitter.cBankCategoryTitle = "銀行"
	Outfitter.cDepositToBank = "將全部物品存入銀行"
	Outfitter.cDepositUniqueToBank = "將唯一物品存入銀行"
	Outfitter.cDepositOthersToBank = "將其他裝備存入銀行"
	Outfitter.cWithdrawFromBank = "從銀行提領物品"
	Outfitter.cWithdrawOthersFromBank = "從銀行提領其他裝備"

	Outfitter.cMissingItemsLabel = "找不到物品: "
	Outfitter.cBankedItemsLabel = "銀行物品: "

	Outfitter.cResistCategory = "抗性"
	Outfitter.cTradeCategory = "技能"

	Outfitter.cTankPoints = "坦克點數"
	Outfitter.cCustom = "自訂"

	Outfitter.cScriptFormat = "指令碼 (%s)"
	Outfitter.cScriptSettings = "設定..."
	Outfitter.cNoScript = "無"
	Outfitter.cDisableScript = "停用"
	Outfitter.cDisableIn = "停用其餘"
	Outfitter.cEditScriptTitle = "%s 配裝的指令碼"
	Outfitter.cEditScriptEllide = "自訂..."
	Outfitter.cEventsLabel = "事件:"
	Outfitter.cScriptLabel = "指令碼:"
	Outfitter.cSetCurrentItems = "更新為目前裝備物品"
	Outfitter.cConfirmSetCurrentMsg = "確定將配裝 %s 更新為目前裝備的物品? 注意: 只有配裝中目前被啟用的欄位會被更新 -- 你可以在稍後啟用更多欄位"
	Outfitter.cSetCurrent = "更新"
	Outfitter.cTyping = "輸入..."
	Outfitter.cScriptErrorFormat = "錯誤位於第 %d 行: %s"
	Outfitter.cExtractErrorFormat = "%[string \"Outfit Script\"%]:(%d+):(.*)"
	Outfitter.cPresetScript = "預設的指令碼:"
	Outfitter.cCustomScript = "自訂"
	Outfitter.cSettings = "設定"
	Outfitter.cSource = "源始碼"
	Outfitter.cInsertFormat = "<- %s"

	Outfitter.cNone = "無"
	Outfitter.cTooltipMultibuffSeparator1 = " 和 "
	Outfitter.cTooltipMultibuffSeparator2 = " / "
	Outfitter.cNoScriptSettings = "此指令碼沒有可供設定項目"
	Outfitter.cMissingItemsSeparator = ", "
	Outfitter.cUnequipOthers = "當裝備時, 卸下其他零散配裝。"

	Outfitter.cConfirmResetMsg = "確定要重置目前角色的 換裝管理 設定?  所有配裝將會被刪除，而預設配裝會被重建。"
	Outfitter.cReset = "重置"

	Outfitter.cIconFilterLabel = "搜尋:"
	Outfitter.cIconSetLabel = "圖示:"

	Outfitter.cCantReloadUI = "必須完全重新啟動魔獸世界，才能更新Outfitter版本"
	Outfitter.cChooseIconTitle = "為 %s 配裝選擇一個圖示"
	Outfitter.cOutfitterDecides = "換裝管理 將為你選擇一個圖示"

	Outfitter.cSuggestedIcons = "建議的配裝圖示"
	Outfitter.cSpellbookIcons = "你的法術書"
	Outfitter.cYourItemIcons = "你的包包"
	Outfitter.cEveryIcon = "全部圖示"
	Outfitter.cItemIcons = "全部圖示(只有物品)"
	Outfitter.cAbilityIcons = "全部圖示(只有法術)"

	Outfitter.cRequiresLockpicking = "需要開鎖"
	Outfitter.cUseTooltipLineFormat = "^使用:.*"
	Outfitter.cUseDurationTooltipLineFormat = "^使用: .* 持續 (%d+) 秒"
	Outfitter.cUseDurationTooltipLineFormat2 = "^使用: .* 持續 (%d+) 秒"

	Outfitter.cOutfitBarSizeLabel = "大小"
	Outfitter.cOutfitBarSmallSizeLabel = "小"
	Outfitter.cOutfitBarLargeSizeLabel = "大"
	Outfitter.cOutfitBarAlphaLabel = "不透明程度"
	Outfitter.cOutfitBarCombatAlphaLabel = "戰鬥時不透明程度"
	Outfitter.cOutfitBarVerticalLabel = "垂直"
	Outfitter.cOutfitBarLockPositionLabel = "鎖定位置"
	Outfitter.cOutfitBarHideBackgroundLabel = "隱藏背景"

	Outfitter.cPositionLockedError = "換裝列無法移動，因為你已鎖定它的位置"

	Outfitter.cMustBeAtBankError = "你要保持銀行開啟才能產生遺失物品的報告"
	Outfitter.cMissingItemReportIntro = "遺失物品 (物品如果用在多個配裝中，可能會出現多次):"
	Outfitter.cNoMissingItems = "沒有遺失物品"

	Outfitter.cAutoChangesDisabled = "關閉自動換裝功能"
	Outfitter.cAutoChangesEnabled = "開啟自動換裝功能"

	-- OutfitterFu strings

	Outfitter.cFuHint = "左鍵點擊開啟Outfitter設定視窗。"
	Outfitter.cFuHideMissing = "隱藏遺失"
	Outfitter.cFuHideMissingDesc = "隱藏配裝和遺失物品。"
	Outfitter.cFuRemovePrefixes = "移除前綴"
	Outfitter.cFuRemovePrefixesDesc = "在FuBar上，刪除配裝的前綴，以縮短顯示文字。"
	Outfitter.cFuMaxTextLength = "最大文字長度"
	Outfitter.cFuMaxTextLengthDesc = "在FuBar上，顯示最大的文字長度。"
	Outfitter.cFuHideMinimapButton = "隱藏小地圖按鈕"
	Outfitter.cFuHideMinimapButtonDesc = "隱藏Outfitter的小地圖按鈕。"
	Outfitter.cFuInitializing = "初始化"

	Outfitter.cStoreOnServer = "裝備管理員"
	Outfitter.cStoreOnServerOnDescription = "關閉裝備管理員並移除本地儲存的配裝。這將與其他電腦的配裝不相容。"
	Outfitter.cStoreOnServerOffDescription = "開啟裝備管理員這將與其他電腦上的配裝相容。但最多只能儲存10組配裝。"
	Outfitter.cTooManyServerOutfits = "你無法存取超過%d組配裝。"
	
	Outfitter.cNoItemsWithStat = "Couldn't generate an outfit because no items with that stat were found"
end
