if true then return end

ZPetAttack = CreateFrame("button", "ZPetAttack", nil, "SecureActionButtonTemplate")
ZPetAttack:SetAttribute("type", "macro")
ZPetAttack:SetAttribute("macrotext", "/petattack\n/petfollow [target=pettarget,exists]")

ZPetObey = CreateFrame("button", "ZPetObey", nil, "SecureActionButtonTemplate")
ZPetObey:SetAttribute("type", "macro")
ZPetObey:SetAttribute("macrotext1", "/petstay")
ZPetObey:SetAttribute("macrotext2", "/petfollow")
ZPetObey:SetAttribute("statebutton", "0:LeftButton;1:RightButton")
ZPetObey:SetAttribute("newstate", "1:0;*:1")
ZPetObey.parent = CreateFrame("button", "ZPetObeyParent", nil, "SecureUnitButtonTemplate, SecureStateHeaderTemplate")
ZPetObey.parent:SetAttribute("AddChild", ZPetObey)
ZPetObey.parent:SetAttribute("unit", "pet")
ZPetObey.parent:SetAttribute("statemap-unitexists-false", "0")
ZPetObey.parent:SetAttribute("statemap-unitexists-true", "0")
RegisterUnitWatch(ZPetObey.parent, true)

--ZPetObey.parent:ClearAllPoints()
--ZPetObey.parent:SetPoint("CENTER", UIParent, "CENTER", 0, 0)
--ZPetObey:Show()
--ZPetObey:RegisterForClicks("AnyUp")
--ZPetObey:ClearAllPoints()
--ZPetObey:SetPoint("CENTER", UIParent, "CENTER", 0, 0)
--ZPetObey:SetHeight(40)
--ZPetObey:SetWidth(40)
--ZPetObey.texture = ZPetObey:CreateTexture()
--ZPetObey.texture:SetAllPoints(ZPetObey)
--ZPetObey.texture:SetTexture("Interface\\TargetingFrame\\UI-StatusBar")
--ZPetObey.texture:Show()