local L = LibStub("AceLocale-3.0"):NewLocale("Proximo", "deDE", false)

if L then
--options
L["Colors"] = "Farben"
L["Frame"] = "Fenster"
L["Misc"] = "Sonst."
L["FrameColor"] = "Frame-Farbe"
L["ManaColor"] = "Mana-Farbe"
L["FontSize"] = "Schriftgr\195\182\195\159e"
L["Font"] = "Schrift"
L["BarWidth"] = "Balkenbreite"
L["BarHeight"] = "Balkenh\195\182he"
L["BarTexture"] = "Balkentextur"
L["Padding"] = "Abstand"
L["Scale"] = "Skalierung"
L["LowHealth"] = "Wenig Gesundheit"
L["LowHealthSound"] = "Wenig Gesundheit - Sound"
L["LowHealthDesc"] = "Warnungen f\195\188r wenig Gesundheit anzeigen"
L["Announce"] = "Gegnerank\195\188ndigungen"
L["MainAssist"] = "Main-Assist festlegen"
L["RightClick"] = "Rechtsklick festlegen"
L["LeftClick"] = "Linksklick festlegen"
L["CastSpell"] = "Zauber wirken"
L["CastSpellName"] = "Zauber/Makro Rechts festlegen"
L["CastSpellNameLeft"] = "Zauber/Makro Links festlegen"
L["CastSpellNameDesc"] = "F\195\188r Zauber, gib den Zaubernamen ein wie du es f\195\188r ein Makro machen w\195\188rdest.\nBeispiel: Dispel, Dispel(Rank 1)\n\nF\195\188r Makros, verwende ; f\195\188r den Zeilenumbruch und *t um den Namen des Ziels einzuf\195\188gen.\nBeispiel: /target *t;/cast Dispel"
L["Focus"] = "Fokus via Rechtsklick festlegen"
L["Header"] = "Header anzeigen"
L["ClassText"] = "Klassentext aktivieren"
L["Talents"] = "Enable Talent Text Display"
L["Sync"] = "Syncing aktivieren"
L["SyncDesc"] = "Das Senden und Empfangen von synchronisierten Gegnernamen, Klassen und Gesundheit aktivieren"
L["Test"] = "Test anzeigen"
L["TestDesc"] = "Fenster anzeigen und mit Testgegner f\195\188llen"
L["PartyTargets"] = "Gruppen-Ziele anzeigen"
L["PartyTargetsHeight"] = "H\195\182he Gruppen-Ziele"
L["Mana"] = "Manabalken anzeigen"
L["ManaHeight"] = "H\195\182he Manabalken"
L["Highlight"] = "Highlight Main Assist Type"
L["HighlightColor"] = "Highlight Color"
L["HighlightSolid"] = "Solid"
L["HighlightTooltip"] = "Tooltip"
L["HighlightTarget"] = "Dein Ziel hervorheben"
L["VersionCheck"] = "Versionscheck"
L["VersionCheckDesc"] = "F\195\188hre einen Versionscheck durch..."
L["HelpTip"] = "ALT-Linksklick um den Header zu verschieben. Rechtsklick auf den Header um die Optionen aufzurufen."

--bindings
L["Tar1Left"] = "Gegner 1 anvisieren"
L["Tar2Left"] = "Gegner 2 anvisieren"
L["Tar3Left"] = "Gegner 3 anvisieren"
L["Tar4Left"] = "Gegner 4 anvisieren"
L["Tar5Left"] = "Gegner 5 anvisieren"
L["Tar1Right"] = "Gegner 1 Rechtsklick"
L["Tar2Right"] = "Gegner 2 Rechtsklick"
L["Tar3Right"] = "Gegner 3 Rechtsklick"
L["Tar4Right"] = "Gegner 4 Rechtsklick"
L["Tar5Right"] = "Gegner 5 Rechtsklick"

end